/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Typed dictionary for alert notes.

Each note represents a message/action in the alert history.
 */
export type AlertNote = {
  timestamp: string;
  userId: string;
  userName: string;
  userRole: string;
  content: string;
};
