/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Category of a screening alert.

Used to classify alerts raised during the screening process.
Helps supervisors prioritize and filter alerts.
 */
export type AlertCategory = (typeof AlertCategory)[keyof typeof AlertCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlertCategory = {
  DOCUMENT: "DOCUMENT",
  DATA: "DATA",
  BEHAVIOR: "BEHAVIOR",
  COMPLIANCE: "COMPLIANCE",
  QUALIFICATION: "QUALIFICATION",
  OTHER: "OTHER",
} as const;
