/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { BankAccountResponseAgencyDigit } from "./bankAccountResponseAgencyDigit.js";
import type { BankAccountResponseAccountDigit } from "./bankAccountResponseAccountDigit.js";
import type { AccountType } from "./accountType.js";
import type { BankAccountResponsePixKeyType } from "./bankAccountResponsePixKeyType.js";
import type { BankAccountResponsePixKey } from "./bankAccountResponsePixKey.js";
import type { BankAccountResponseBank } from "./bankAccountResponseBank.js";
import type { BankAccountResponseCreatedAt } from "./bankAccountResponseCreatedAt.js";
import type { BankAccountResponseUpdatedAt } from "./bankAccountResponseUpdatedAt.js";

/**
 * Schema for bank account response.
 */
export type BankAccountResponse = {
  id: string;
  agency: string;
  agencyDigit?: BankAccountResponseAgencyDigit;
  accountNumber: string;
  accountDigit?: BankAccountResponseAccountDigit;
  accountType: AccountType;
  holderName: string;
  holderDocument: string;
  pixKeyType?: BankAccountResponsePixKeyType;
  pixKey?: BankAccountResponsePixKey;
  isPrimary: boolean;
  isActive: boolean;
  isVerified?: boolean;
  bank?: BankAccountResponseBank;
  createdAt?: BankAccountResponseCreatedAt;
  updatedAt?: BankAccountResponseUpdatedAt;
};
