/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { BankAccountInputId } from "./bankAccountInputId";
import type { BankAccountInputAgencyDigit } from "./bankAccountInputAgencyDigit";
import type { BankAccountInputAccountDigit } from "./bankAccountInputAccountDigit";
import type { BankAccountInputPixKeyType } from "./bankAccountInputPixKeyType";
import type { BankAccountInputPixKey } from "./bankAccountInputPixKey";

/**
 * Input schema for bank account.
 */
export type BankAccountInput = {
  /** Existing bank account ID */
  id?: BankAccountInputId;
  /**
   * Bank code
   * @maxLength 10
   */
  bankCode: string;
  /** @maxLength 10 */
  agencyNumber: string;
  agencyDigit?: BankAccountInputAgencyDigit;
  /** @maxLength 20 */
  accountNumber: string;
  accountDigit?: BankAccountInputAccountDigit;
  /** @maxLength 255 */
  accountHolderName: string;
  /**
   * CPF (11) or CNPJ (14)
   * @pattern ^[0-9]{11}([0-9]{3})?$
   */
  accountHolderDocument: string;
  pixKeyType?: BankAccountInputPixKeyType;
  pixKey?: BankAccountInputPixKey;
  isPrimary?: boolean;
  isCompanyAccount?: boolean;
};
