/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { BankInfoShortName } from "./bankInfoShortName";

/**
 * Embedded bank information.
 */
export type BankInfo = {
  id: string;
  code: string;
  name: string;
  shortName?: BankInfoShortName;
};
