/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { BodyUploadDocumentByTokenApiV1PublicScreeningTokenDocumentsDocumentIdUploadPostExpiresAt } from "./bodyUploadDocumentByTokenApiV1PublicScreeningTokenDocumentsDocumentIdUploadPostExpiresAt.js";
import type { BodyUploadDocumentByTokenApiV1PublicScreeningTokenDocumentsDocumentIdUploadPostNotes } from "./bodyUploadDocumentByTokenApiV1PublicScreeningTokenDocumentsDocumentIdUploadPostNotes.js";

export type BodyUploadDocumentByTokenApiV1PublicScreeningTokenDocumentsDocumentIdUploadPost =
  {
    /** Arquivo do documento (PDF, JPEG, PNG, WebP) */
    file: Blob;
    /** Data de validade do documento (UTC) */
    expiresAt?: BodyUploadDocumentByTokenApiV1PublicScreeningTokenDocumentsDocumentIdUploadPostExpiresAt;
    /** Observações sobre o documento */
    notes?: BodyUploadDocumentByTokenApiV1PublicScreeningTokenDocumentsDocumentIdUploadPostNotes;
  };
