/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { BodyUploadDocumentApiV1ScreeningsScreeningIdDocumentsDocumentIdUploadPostExpiresAt } from "./bodyUploadDocumentApiV1ScreeningsScreeningIdDocumentsDocumentIdUploadPostExpiresAt.js";
import type { BodyUploadDocumentApiV1ScreeningsScreeningIdDocumentsDocumentIdUploadPostNotes } from "./bodyUploadDocumentApiV1ScreeningsScreeningIdDocumentsDocumentIdUploadPostNotes.js";

export type BodyUploadDocumentApiV1ScreeningsScreeningIdDocumentsDocumentIdUploadPost =
  {
    /** Arquivo do documento (PDF, JPEG, PNG, WebP) */
    file: Blob;
    /** Data de validade do documento (UTC) */
    expiresAt?: BodyUploadDocumentApiV1ScreeningsScreeningIdDocumentsDocumentIdUploadPostExpiresAt;
    /** Observações sobre o documento */
    notes?: BodyUploadDocumentApiV1ScreeningsScreeningIdDocumentsDocumentIdUploadPostNotes;
  };
