/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of change in a professional version diff.

Used in ProfessionalChangeDiff to categorize field changes.
 */
export type ChangeType = (typeof ChangeType)[keyof typeof ChangeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeType = {
  ADDED: "ADDED",
  MODIFIED: "MODIFIED",
  REMOVED: "REMOVED",
} as const;
