/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { CompanyDetailInfoCnpj } from "./companyDetailInfoCnpj.js";
import type { CompanyDetailInfoTradeName } from "./companyDetailInfoTradeName.js";
import type { CompanyDetailInfoEmail } from "./companyDetailInfoEmail.js";
import type { CompanyDetailInfoPhone } from "./companyDetailInfoPhone.js";
import type { CompanyDetailInfoStreet } from "./companyDetailInfoStreet.js";
import type { CompanyDetailInfoStreetNumber } from "./companyDetailInfoStreetNumber.js";
import type { CompanyDetailInfoComplement } from "./companyDetailInfoComplement.js";
import type { CompanyDetailInfoNeighborhood } from "./companyDetailInfoNeighborhood.js";
import type { CompanyDetailInfoCity } from "./companyDetailInfoCity.js";
import type { CompanyDetailInfoStateCode } from "./companyDetailInfoStateCode.js";
import type { CompanyDetailInfoPostalCode } from "./companyDetailInfoPostalCode.js";
import type { BankAccountResponse } from "./bankAccountResponse.js";

/**
 * Detailed company information with bank accounts.
 */
export type CompanyDetailInfo = {
  id: string;
  cnpj?: CompanyDetailInfoCnpj;
  legalName: string;
  tradeName?: CompanyDetailInfoTradeName;
  email?: CompanyDetailInfoEmail;
  phone?: CompanyDetailInfoPhone;
  street?: CompanyDetailInfoStreet;
  streetNumber?: CompanyDetailInfoStreetNumber;
  complement?: CompanyDetailInfoComplement;
  neighborhood?: CompanyDetailInfoNeighborhood;
  city?: CompanyDetailInfoCity;
  stateCode?: CompanyDetailInfoStateCode;
  postalCode?: CompanyDetailInfoPostalCode;
  bankAccounts?: BankAccountResponse[];
};
