/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { CompanyInputId } from "./companyInputId";
import type { CompanyInputCompanyId } from "./companyInputCompanyId";
import type { CompanyInputNomeFantasia } from "./companyInputNomeFantasia";
import type { CompanyInputInscricaoEstadual } from "./companyInputInscricaoEstadual";
import type { CompanyInputInscricaoMunicipal } from "./companyInputInscricaoMunicipal";
import type { CompanyInputAddress } from "./companyInputAddress";
import type { CompanyInputNumber } from "./companyInputNumber";
import type { CompanyInputComplement } from "./companyInputComplement";
import type { CompanyInputNeighborhood } from "./companyInputNeighborhood";
import type { CompanyInputCity } from "./companyInputCity";
import type { CompanyInputStateCode } from "./companyInputStateCode";
import type { CompanyInputPostalCode } from "./companyInputPostalCode";
import type { CompanyInputStartedAt } from "./companyInputStartedAt";
import type { CompanyInputEndedAt } from "./companyInputEndedAt";

/**
 * Input schema for professional company.
 */
export type CompanyInput = {
  /** Existing ProfessionalCompany ID */
  id?: CompanyInputId;
  /** Existing Company ID */
  companyId?: CompanyInputCompanyId;
  /**
   * CNPJ (14 digits)
   * @pattern ^[0-9]{14}$
   */
  cnpj: string;
  /** @maxLength 255 */
  razaoSocial: string;
  nomeFantasia?: CompanyInputNomeFantasia;
  inscricaoEstadual?: CompanyInputInscricaoEstadual;
  inscricaoMunicipal?: CompanyInputInscricaoMunicipal;
  address?: CompanyInputAddress;
  number?: CompanyInputNumber;
  complement?: CompanyInputComplement;
  neighborhood?: CompanyInputNeighborhood;
  city?: CompanyInputCity;
  stateCode?: CompanyInputStateCode;
  postalCode?: CompanyInputPostalCode;
  startedAt?: CompanyInputStartedAt;
  endedAt?: CompanyInputEndedAt;
};
