/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { CompanyDetailInfoCnpj } from "./companyDetailInfoCnpj";
import type { CompanyDetailInfoTradeName } from "./companyDetailInfoTradeName";
import type { CompanyDetailInfoEmail } from "./companyDetailInfoEmail";
import type { CompanyDetailInfoPhone } from "./companyDetailInfoPhone";
import type { CompanyDetailInfoStreet } from "./companyDetailInfoStreet";
import type { CompanyDetailInfoStreetNumber } from "./companyDetailInfoStreetNumber";
import type { CompanyDetailInfoComplement } from "./companyDetailInfoComplement";
import type { CompanyDetailInfoNeighborhood } from "./companyDetailInfoNeighborhood";
import type { CompanyDetailInfoCity } from "./companyDetailInfoCity";
import type { CompanyDetailInfoStateCode } from "./companyDetailInfoStateCode";
import type { CompanyDetailInfoPostalCode } from "./companyDetailInfoPostalCode";
import type { BankAccountResponse } from "./bankAccountResponse";

/**
 * Detailed company information with bank accounts.
 */
export type CompanyDetailInfo = {
  id: string;
  cnpj?: CompanyDetailInfoCnpj;
  legalName: string;
  tradeName?: CompanyDetailInfoTradeName;
  email?: CompanyDetailInfoEmail;
  phone?: CompanyDetailInfoPhone;
  street?: CompanyDetailInfoStreet;
  streetNumber?: CompanyDetailInfoStreetNumber;
  complement?: CompanyDetailInfoComplement;
  neighborhood?: CompanyDetailInfoNeighborhood;
  city?: CompanyDetailInfoCity;
  stateCode?: CompanyDetailInfoStateCode;
  postalCode?: CompanyDetailInfoPostalCode;
  bankAccounts?: BankAccountResponse[];
};
