/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { CompanyInfoCnpj } from "./companyInfoCnpj.js";
import type { CompanyInfoTradeName } from "./companyInfoTradeName.js";

/**
 * Embedded company information.
 */
export type CompanyInfo = {
  id: string;
  cnpj?: CompanyInfoCnpj;
  legalName: string;
  tradeName?: CompanyInfoTradeName;
};
