/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentConfigItem } from "./documentConfigItem.js";

/**
 * Request schema for configuring documents in the upload step.
 */
export type ConfigureDocumentsRequest = {
  /**
   * List of documents to configure for upload
   * @minItems 1
   */
  documents: DocumentConfigItem[];
};
