/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ConversationOutcome } from "./conversationOutcome.js";

/**
 * Request schema for completing conversation step.
 */
export type ConversationStepCompleteRequest = {
  /**
   * Notas da conversa telefônica com o profissional
   * @minLength 10
   * @maxLength 4000
   */
  notes: string;
  /** Resultado da conversa: PROCEED (prosseguir) ou REJECT (rejeitar) */
  outcome: ConversationOutcome;
};
