/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { StepType } from "./stepType";
import type { StepStatus } from "./stepStatus";
import type { ConversationStepResponseAssignedTo } from "./conversationStepResponseAssignedTo";
import type { ConversationStepResponseReviewNotes } from "./conversationStepResponseReviewNotes";
import type { ConversationStepResponseRejectionReason } from "./conversationStepResponseRejectionReason";
import type { ConversationStepResponseStartedAt } from "./conversationStepResponseStartedAt";
import type { ConversationStepResponseCompletedAt } from "./conversationStepResponseCompletedAt";
import type { ConversationStepResponseCompletedBy } from "./conversationStepResponseCompletedBy";
import type { ConversationStepResponseReviewedAt } from "./conversationStepResponseReviewedAt";
import type { ConversationStepResponseReviewedBy } from "./conversationStepResponseReviewedBy";
import type { ConversationStepResponseNotes } from "./conversationStepResponseNotes";
import type { ConversationStepResponseOutcome } from "./conversationStepResponseOutcome";

/**
 * Response schema for conversation step.

Includes conversation-specific fields: notes and outcome.
 */
export type ConversationStepResponse = {
  id: string;
  stepType: StepType;
  order: number;
  status: StepStatus;
  assignedTo?: ConversationStepResponseAssignedTo;
  reviewNotes?: ConversationStepResponseReviewNotes;
  rejectionReason?: ConversationStepResponseRejectionReason;
  createdAt: Date;
  updatedAt: Date;
  startedAt?: ConversationStepResponseStartedAt;
  completedAt?: ConversationStepResponseCompletedAt;
  completedBy?: ConversationStepResponseCompletedBy;
  reviewedAt?: ConversationStepResponseReviewedAt;
  reviewedBy?: ConversationStepResponseReviewedBy;
  notes?: ConversationStepResponseNotes;
  outcome?: ConversationStepResponseOutcome;
};
