/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Outcome of the initial conversation step.

Determines whether the screening proceeds or is rejected early.
 */
export type ConversationOutcome =
  (typeof ConversationOutcome)[keyof typeof ConversationOutcome];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConversationOutcome = {
  PROCEED: "PROCEED",
  REJECT: "REJECT",
} as const;
