/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { StepType } from "./stepType.js";
import type { StepStatus } from "./stepStatus.js";
import type { ConversationStepResponseAssignedTo } from "./conversationStepResponseAssignedTo.js";
import type { ConversationStepResponseReviewNotes } from "./conversationStepResponseReviewNotes.js";
import type { ConversationStepResponseRejectionReason } from "./conversationStepResponseRejectionReason.js";
import type { ConversationStepResponseStartedAt } from "./conversationStepResponseStartedAt.js";
import type { ConversationStepResponseCompletedAt } from "./conversationStepResponseCompletedAt.js";
import type { ConversationStepResponseCompletedBy } from "./conversationStepResponseCompletedBy.js";
import type { ConversationStepResponseReviewedAt } from "./conversationStepResponseReviewedAt.js";
import type { ConversationStepResponseReviewedBy } from "./conversationStepResponseReviewedBy.js";
import type { ConversationStepResponseNotes } from "./conversationStepResponseNotes.js";
import type { ConversationStepResponseOutcome } from "./conversationStepResponseOutcome.js";

/**
 * Response schema for conversation step.

Includes conversation-specific fields: notes and outcome.
 */
export type ConversationStepResponse = {
  id: string;
  stepType: StepType;
  order: number;
  status: StepStatus;
  assignedTo?: ConversationStepResponseAssignedTo;
  reviewNotes?: ConversationStepResponseReviewNotes;
  rejectionReason?: ConversationStepResponseRejectionReason;
  createdAt: Date;
  updatedAt: Date;
  startedAt?: ConversationStepResponseStartedAt;
  completedAt?: ConversationStepResponseCompletedAt;
  completedBy?: ConversationStepResponseCompletedBy;
  reviewedAt?: ConversationStepResponseReviewedAt;
  reviewedBy?: ConversationStepResponseReviewedBy;
  notes?: ConversationStepResponseNotes;
  outcome?: ConversationStepResponseOutcome;
};
