/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Types of professional councils in Brazil.

Each healthcare profession has its own regulatory council
responsible for registration and oversight.
 */
export type CouncilType = (typeof CouncilType)[keyof typeof CouncilType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CouncilType = {
  CRM: "CRM",
  COREN: "COREN",
  CRF: "CRF",
  CRO: "CRO",
  CREFITO: "CREFITO",
  CRP: "CRP",
  CRN: "CRN",
  CRBM: "CRBM",
} as const;
