/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentCategory } from "./documentCategory.js";
import type { DocumentTypeCreateDescription } from "./documentTypeCreateDescription.js";
import type { DocumentTypeCreateHelpText } from "./documentTypeCreateHelpText.js";
import type { DocumentTypeCreateValidationInstructions } from "./documentTypeCreateValidationInstructions.js";
import type { DocumentTypeCreateValidationUrl } from "./documentTypeCreateValidationUrl.js";
import type { DocumentTypeCreateDefaultValidityDays } from "./documentTypeCreateDefaultValidityDays.js";
import type { DocumentTypeCreateRequiredForProfessionalTypes } from "./documentTypeCreateRequiredForProfessionalTypes.js";

/**
 * Schema for creating a document type configuration.
 */
export type DocumentTypeCreate = {
  /**
   * Display name in Portuguese
   * @maxLength 255
   */
  name: string;
  /** Document category (PROFILE, QUALIFICATION, SPECIALTY) */
  category: DocumentCategory;
  /** Brief description of this document */
  description?: DocumentTypeCreateDescription;
  /** Detailed help text on how to obtain this document */
  helpText?: DocumentTypeCreateHelpText;
  /** Instructions for reviewers on how to validate */
  validationInstructions?: DocumentTypeCreateValidationInstructions;
  /** URL where this document can be validated */
  validationUrl?: DocumentTypeCreateValidationUrl;
  /** Whether this document type has an expiration date */
  requiresExpiration?: boolean;
  /** Default validity period in days */
  defaultValidityDays?: DocumentTypeCreateDefaultValidityDays;
  /** List of ProfessionalType values this doc is required for */
  requiredForProfessionalTypes?: DocumentTypeCreateRequiredForProfessionalTypes;
  /**
   * Order for displaying in lists
   * @minimum 0
   */
  displayOrder?: number;
};
