/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Source type for professional documents.

Indicates how/where a document was created.
 */
export type DocumentSourceType =
  (typeof DocumentSourceType)[keyof typeof DocumentSourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentSourceType = {
  DIRECT: "DIRECT",
  SCREENING: "SCREENING",
} as const;
