/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentConfigItemDescription } from "./documentConfigItemDescription";

/**
 * Single document configuration for the upload step.
 */
export type DocumentConfigItem = {
  /** ID of the document type to require */
  documentTypeId: string;
  /** Whether this document is mandatory */
  isRequired?: boolean;
  /**
   * Display order (0 = first)
   * @minimum 0
   */
  order?: number;
  /** Custom instructions for uploading this document */
  description?: DocumentConfigItemDescription;
};
