/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { StepType } from "./stepType.js";
import type { StepStatus } from "./stepStatus.js";
import type { DocumentReviewStepResponseAssignedTo } from "./documentReviewStepResponseAssignedTo.js";
import type { DocumentReviewStepResponseReviewNotes } from "./documentReviewStepResponseReviewNotes.js";
import type { DocumentReviewStepResponseRejectionReason } from "./documentReviewStepResponseRejectionReason.js";
import type { DocumentReviewStepResponseStartedAt } from "./documentReviewStepResponseStartedAt.js";
import type { DocumentReviewStepResponseCompletedAt } from "./documentReviewStepResponseCompletedAt.js";
import type { DocumentReviewStepResponseCompletedBy } from "./documentReviewStepResponseCompletedBy.js";
import type { DocumentReviewStepResponseReviewedAt } from "./documentReviewStepResponseReviewedAt.js";
import type { DocumentReviewStepResponseReviewedBy } from "./documentReviewStepResponseReviewedBy.js";
import type { DocumentReviewStepResponseUploadStepId } from "./documentReviewStepResponseUploadStepId.js";
import type { DocumentForReview } from "./documentForReview.js";

/**
 * Response schema for document review step.

Includes review counts and document list.
 */
export type DocumentReviewStepResponse = {
  id: string;
  stepType: StepType;
  order: number;
  status: StepStatus;
  assignedTo?: DocumentReviewStepResponseAssignedTo;
  reviewNotes?: DocumentReviewStepResponseReviewNotes;
  rejectionReason?: DocumentReviewStepResponseRejectionReason;
  createdAt: Date;
  updatedAt: Date;
  startedAt?: DocumentReviewStepResponseStartedAt;
  completedAt?: DocumentReviewStepResponseCompletedAt;
  completedBy?: DocumentReviewStepResponseCompletedBy;
  reviewedAt?: DocumentReviewStepResponseReviewedAt;
  reviewedBy?: DocumentReviewStepResponseReviewedBy;
  uploadStepId?: DocumentReviewStepResponseUploadStepId;
  totalToReview?: number;
  reviewedCount?: number;
  approvedCount?: number;
  correctionNeededCount?: number;
  reviewProgress?: number;
  allApproved?: boolean;
  hasCorrectionsNeeded?: boolean;
  documents?: DocumentForReview[];
};
