/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentCategory } from "./documentCategory.js";
import type { DocumentTypeResponseDescription } from "./documentTypeResponseDescription.js";
import type { DocumentTypeResponseHelpText } from "./documentTypeResponseHelpText.js";
import type { DocumentTypeResponseValidationInstructions } from "./documentTypeResponseValidationInstructions.js";
import type { DocumentTypeResponseValidationUrl } from "./documentTypeResponseValidationUrl.js";
import type { DocumentTypeResponseDefaultValidityDays } from "./documentTypeResponseDefaultValidityDays.js";
import type { DocumentTypeResponseRequiredForProfessionalTypes } from "./documentTypeResponseRequiredForProfessionalTypes.js";
import type { DocumentTypeResponseUpdatedAt } from "./documentTypeResponseUpdatedAt.js";

/**
 * Schema for document type configuration response.
 */
export type DocumentTypeResponse = {
  id: string;
  name: string;
  category: DocumentCategory;
  description: DocumentTypeResponseDescription;
  helpText: DocumentTypeResponseHelpText;
  validationInstructions: DocumentTypeResponseValidationInstructions;
  validationUrl: DocumentTypeResponseValidationUrl;
  requiresExpiration: boolean;
  defaultValidityDays: DocumentTypeResponseDefaultValidityDays;
  requiredForProfessionalTypes: DocumentTypeResponseRequiredForProfessionalTypes;
  isActive: boolean;
  displayOrder: number;
  organizationId: string;
  createdAt: Date;
  updatedAt: DocumentTypeResponseUpdatedAt;
};
