/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { StepType } from "./stepType";
import type { StepStatus } from "./stepStatus";
import type { DocumentUploadStepResponseAssignedTo } from "./documentUploadStepResponseAssignedTo";
import type { DocumentUploadStepResponseReviewNotes } from "./documentUploadStepResponseReviewNotes";
import type { DocumentUploadStepResponseRejectionReason } from "./documentUploadStepResponseRejectionReason";
import type { DocumentUploadStepResponseStartedAt } from "./documentUploadStepResponseStartedAt";
import type { DocumentUploadStepResponseCompletedAt } from "./documentUploadStepResponseCompletedAt";
import type { DocumentUploadStepResponseCompletedBy } from "./documentUploadStepResponseCompletedBy";
import type { DocumentUploadStepResponseReviewedAt } from "./documentUploadStepResponseReviewedAt";
import type { DocumentUploadStepResponseReviewedBy } from "./documentUploadStepResponseReviewedBy";
import type { ScreeningDocumentSummary } from "./screeningDocumentSummary";

/**
 * Response schema for document upload step.

Includes document counts and optional document list.
 */
export type DocumentUploadStepResponse = {
  id: string;
  stepType: StepType;
  order: number;
  status: StepStatus;
  assignedTo?: DocumentUploadStepResponseAssignedTo;
  reviewNotes?: DocumentUploadStepResponseReviewNotes;
  rejectionReason?: DocumentUploadStepResponseRejectionReason;
  createdAt: Date;
  updatedAt: Date;
  startedAt?: DocumentUploadStepResponseStartedAt;
  completedAt?: DocumentUploadStepResponseCompletedAt;
  completedBy?: DocumentUploadStepResponseCompletedBy;
  reviewedAt?: DocumentUploadStepResponseReviewedAt;
  reviewedBy?: DocumentUploadStepResponseReviewedBy;
  totalDocuments?: number;
  requiredDocuments?: number;
  uploadedDocuments?: number;
  uploadProgress?: number;
  allRequiredUploaded?: boolean;
  documents?: ScreeningDocumentSummary[];
};
