/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentUploadStepCompleteRequestNotes } from "./documentUploadStepCompleteRequestNotes.js";

/**
 * Request schema for completing document upload step.

This step is completed when all required documents have been uploaded.
The system validates that all required documents have status = UPLOADED.
 */
export type DocumentUploadStepCompleteRequest = {
  /** Notas opcionais sobre os documentos enviados */
  notes?: DocumentUploadStepCompleteRequestNotes;
};
