/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Document category based on which entity it relates to.

Used to group documents by their relation to professional data.
 */
export type DocumentCategory =
  (typeof DocumentCategory)[keyof typeof DocumentCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentCategory = {
  PROFILE: "PROFILE",
  QUALIFICATION: "QUALIFICATION",
  SPECIALTY: "SPECIALTY",
} as const;
