/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentReviewStepCompleteRequestNotes } from "./documentReviewStepCompleteRequestNotes";

/**
 * Request schema for completing document review step.

This step is completed when all documents have been reviewed.
The system validates that no documents have status = UPLOADED (all must be APPROVED or REJECTED).
 */
export type DocumentReviewStepCompleteRequest = {
  /** Notas opcionais sobre a revisão */
  notes?: DocumentReviewStepCompleteRequestNotes;
};
