/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Education ID (required for update, omit for create, send only ID to keep unchanged)
 */
export type EducationNestedUpdateId = string | null;
