/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { EducationNestedUpdateId } from "./educationNestedUpdateId.js";
import type { EducationNestedUpdateLevel } from "./educationNestedUpdateLevel.js";
import type { EducationNestedUpdateCourseName } from "./educationNestedUpdateCourseName.js";
import type { EducationNestedUpdateInstitution } from "./educationNestedUpdateInstitution.js";
import type { EducationNestedUpdateStartYear } from "./educationNestedUpdateStartYear.js";
import type { EducationNestedUpdateEndYear } from "./educationNestedUpdateEndYear.js";
import type { EducationNestedUpdateIsCompleted } from "./educationNestedUpdateIsCompleted.js";
import type { EducationNestedUpdateWorkloadHours } from "./educationNestedUpdateWorkloadHours.js";
import type { EducationNestedUpdateCertificateUrl } from "./educationNestedUpdateCertificateUrl.js";
import type { EducationNestedUpdateNotes } from "./educationNestedUpdateNotes.js";

/**
 * Schema for updating an education within a composite operation.
 */
export type EducationNestedUpdate = {
  /** Education ID (required for update, omit for create, send only ID to keep unchanged) */
  id?: EducationNestedUpdateId;
  /** Education level */
  level?: EducationNestedUpdateLevel;
  /** Name of the course/degree */
  courseName?: EducationNestedUpdateCourseName;
  /** Educational institution name */
  institution?: EducationNestedUpdateInstitution;
  /** Year started */
  startYear?: EducationNestedUpdateStartYear;
  /** Year completed */
  endYear?: EducationNestedUpdateEndYear;
  /** Whether the education is completed */
  isCompleted?: EducationNestedUpdateIsCompleted;
  /** Total workload in hours (for courses) */
  workloadHours?: EducationNestedUpdateWorkloadHours;
  /** URL to certificate/diploma */
  certificateUrl?: EducationNestedUpdateCertificateUrl;
  /** Additional notes */
  notes?: EducationNestedUpdateNotes;
};
