/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Education level types.

Covers technical courses through doctoral degrees.
 */
export type EducationLevel =
  (typeof EducationLevel)[keyof typeof EducationLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EducationLevel = {
  TECHNICAL: "TECHNICAL",
  UNDERGRADUATE: "UNDERGRADUATE",
  SPECIALIZATION: "SPECIALIZATION",
  MASTERS: "MASTERS",
  DOCTORATE: "DOCTORATE",
  POSTDOC: "POSTDOC",
  COURSE: "COURSE",
  FELLOWSHIP: "FELLOWSHIP",
} as const;
