/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { EducationLevel } from "./educationLevel";
import type { EducationNestedCreateStartYear } from "./educationNestedCreateStartYear";
import type { EducationNestedCreateEndYear } from "./educationNestedCreateEndYear";
import type { EducationNestedCreateWorkloadHours } from "./educationNestedCreateWorkloadHours";
import type { EducationNestedCreateCertificateUrl } from "./educationNestedCreateCertificateUrl";
import type { EducationNestedCreateNotes } from "./educationNestedCreateNotes";

/**
 * Schema for creating an education within a composite operation.
 */
export type EducationNestedCreate = {
  /** Education level (undergraduate, masters, etc.) */
  level: EducationLevel;
  /**
   * Name of the course/degree
   * @maxLength 255
   */
  courseName: string;
  /**
   * Educational institution name
   * @maxLength 255
   */
  institution: string;
  /** Year started */
  startYear?: EducationNestedCreateStartYear;
  /** Year completed (null if ongoing) */
  endYear?: EducationNestedCreateEndYear;
  /** Whether the education is completed */
  isCompleted?: boolean;
  /** Total workload in hours (for courses) */
  workloadHours?: EducationNestedCreateWorkloadHours;
  /** URL to certificate/diploma */
  certificateUrl?: EducationNestedCreateCertificateUrl;
  /** Additional notes */
  notes?: EducationNestedCreateNotes;
};
