/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { EducationInputId } from "./educationInputId";
import type { EducationLevel } from "./educationLevel";
import type { EducationInputStartYear } from "./educationInputStartYear";
import type { EducationInputEndYear } from "./educationInputEndYear";
import type { EducationInputWorkloadHours } from "./educationInputWorkloadHours";
import type { EducationInputCertificateUrl } from "./educationInputCertificateUrl";
import type { EducationInputNotes } from "./educationInputNotes";

/**
 * Input schema for professional education.
 */
export type EducationInput = {
  /** Existing education ID */
  id?: EducationInputId;
  /** Education level */
  level: EducationLevel;
  /** @maxLength 255 */
  courseName: string;
  /** @maxLength 255 */
  institution: string;
  startYear?: EducationInputStartYear;
  endYear?: EducationInputEndYear;
  isCompleted?: boolean;
  workloadHours?: EducationInputWorkloadHours;
  certificateUrl?: EducationInputCertificateUrl;
  notes?: EducationInputNotes;
};
