/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ErrorResponseDetails } from "./errorResponseDetails";

/**
 * Standard error response.
 */
export type ErrorResponse = {
  /** Error code */
  code: string;
  /** Human-readable error message */
  message: string;
  /** Additional error details */
  details?: ErrorResponseDetails;
};
