/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

export type ListProfessionalVersionsApiV1ProfessionalsProfessionalIdVersionsGetParams =
  {
    page?: number | null;
    pageSize?: number | null;
    /**
     * Filter by current version status
     */
    isCurrent?: boolean | null;
    /**
     * Lookup operator for is_current (e.g. exact, icontains)
     */
    "is_current[lookup]"?: string | null;
    /**
     * Filter by applied status (has applied_at)
     */
    isApplied?: boolean | null;
    /**
     * Lookup operator for is_applied (e.g. exact, icontains)
     */
    "is_applied[lookup]"?: string | null;
    /**
     * Filter by rejected status (has rejected_at)
     */
    isRejected?: boolean | null;
    /**
     * Lookup operator for is_rejected (e.g. exact, icontains)
     */
    "is_rejected[lookup]"?: string | null;
    /**
 * List of fields to sort by (format: field:asc or field:desc).

**Available fields**
- `id`: ID (UUID v7 is time-ordered)
- `version_number`: Version number
- `created_at`: Creation date
- `applied_at`: Application date

**Default:** versionNumber:desc
 */
    sortBy?: string[] | null;
  };
