/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

export type ListProfessionalsSummaryApiV1ProfessionalsSummaryGetParams = {
  page?: number | null;
  pageSize?: number | null;
  /**
   * Search by name, email or CPF (partial, case-insensitive)
   */
  search?: string | null;
  /**
   * Lookup operator for search (e.g. exact, icontains)
   */
  "search[lookup]"?: string | null;
  /**
   * Filter by gender (MALE, FEMALE)
   */
  gender?: string[] | null;
  /**
   * Filter by marital status
   */
  maritalStatus?: string[] | null;
  /**
   * Filter by professional type (DOCTOR, NURSE, NURSING_TECH, etc.)
   */
  professionalType?: string[] | null;
  /**
 * List of fields to sort by (format: field:asc or field:desc).

**Available fields**
- `id`: ID (UUID v7 is time-ordered)
- `full_name`: Full name
- `email`: Email
- `created_at`: Creation date

**Default:** id:asc
 */
  sortBy?: string[] | null;
};
