/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

export type ListDocumentsApiV1ProfessionalsProfessionalIdDocumentsGetParams = {
  page?: number | null;
  pageSize?: number | null;
  /**
   * Search by file name (partial, case-insensitive)
   */
  search?: string | null;
  /**
   * Lookup operator for search (e.g. exact, icontains)
   */
  "search[lookup]"?: string | null;
  /**
   * Filter by document type ID
   */
  documentTypeId?: string[] | null;
  /**
   * Filter by document category
   */
  documentCategory?: string[] | null;
  /**
   * Filter by verification status
   */
  isVerified?: boolean | null;
  /**
   * Lookup operator for is_verified (e.g. exact, icontains)
   */
  "is_verified[lookup]"?: string | null;
  /**
 * List of fields to sort by (format: field:asc or field:desc).

**Available fields**
- `id`: ID (UUID v7 is time-ordered)
- `document_type`: Document type
- `file_name`: File name
- `expires_at`: Expiration date
- `created_at`: Creation date

**Default:** id:asc
 */
  sortBy?: string[] | null;
};
