/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

export type ListScreeningProcessesApiV1ScreeningsGetParams = {
  page?: number | null;
  pageSize?: number | null;
  /**
   * Relationships to expand (eager load).
   */
  expand?: string[] | null;
  /**
   * Only include these relationships or columns.
   */
  only?: string[] | null;
  /**
   * Relationships or columns to omit.
   */
  omit?: string[] | null;
  /**
   * Filter by search
   */
  search?: string | null;
  /**
   * Filter by status
   */
  status?: string | null;
  /**
   * Filter by actor_id
   */
  actorId?: string | null;
  /**
   * Filter by client_company_id
   */
  clientCompanyId?: string | null;
  /**
   * Filter by is_active
   */
  isActive?: string | null;
  /**
 * List of fields to sort by (format: field:asc or field:desc).

**Available fields**
- `id`: ID (UUID v7 is time-ordered)
- `created_at`: Creation date
- `updated_at`: Last update date
- `status`: Screening status
- `professional_name`: Professional name

**Default:** id:desc
 */
  sortBy?: string[] | null;
};
