/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

export type ListDocumentTypesApiV1DocumentTypesGetParams = {
  page?: number | null;
  pageSize?: number | null;
  /**
   * Relationships to expand (eager load).
   */
  expand?: string[] | null;
  /**
   * Only include these relationships or columns.
   */
  only?: string[] | null;
  /**
   * Relationships or columns to omit.
   */
  omit?: string[] | null;
  /**
   * Search by name (partial, case-insensitive, accent-insensitive)
   */
  search?: string | null;
  /**
   * Lookup operator for search (e.g. exact, icontains)
   */
  "search[lookup]"?: string | null;
  /**
   * Filter by document category (PROFILE, QUALIFICATION, SPECIALTY)
   */
  category?: string | null;
  /**
   * Exclude specific categories (NOT IN clause)
   */
  excludeCategories?: string | null;
  /**
   * Filter by active status
   */
  isActive?: string | null;
  /**
 * List of fields to sort by (format: field:asc or field:desc).

**Available fields**
- `id`: ID (UUID v7 is time-ordered)
- `name`: Document type name
- `display_order`: Display order
- `created_at`: Creation date

**Default:** displayOrder:asc, name:asc
 */
  sortBy?: string[] | null;
};
