/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

export type ListSpecialtiesApiV1SpecialtiesGetParams = {
  page?: number | null;
  pageSize?: number | null;
  /**
   * Relationships to expand (eager load).
   */
  expand?: string[] | null;
  /**
   * Only include these relationships or columns.
   */
  only?: string[] | null;
  /**
   * Relationships or columns to omit.
   */
  omit?: string[] | null;
  /**
   * Search by code or name (partial, case-insensitive, accent-insensitive)
   */
  search?: string | null;
  /**
   * Lookup operator for search (e.g. exact, icontains)
   */
  "search[lookup]"?: string | null;
  /**
 * List of fields to sort by (format: field:asc or field:desc).

**Available fields**
- `id`: ID (UUID v7 is time-ordered)
- `code`: Specialty code
- `name`: Specialty name

**Default:** name:asc
 */
  sortBy?: string[] | null;
};
