/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

export type ListQualificationsApiV1ProfessionalsProfessionalIdQualificationsGetParams =
  {
    page?: number | null;
    pageSize?: number | null;
    /**
     * Search by council number (partial, case-insensitive)
     */
    search?: string | null;
    /**
     * Lookup operator for search (e.g. exact, icontains)
     */
    "search[lookup]"?: string | null;
    /**
     * Filter by professional type (DOCTOR, NURSE, etc.)
     */
    professionalType?: string[] | null;
    /**
     * Filter by council type (CRM, COREN, etc.)
     */
    councilType?: string[] | null;
    /**
     * Filter by council state (2-char UF)
     */
    councilState?: string | null;
    /**
     * Lookup operator for council_state (e.g. exact, icontains)
     */
    "council_state[lookup]"?: string | null;
    /**
     * Filter by primary qualification flag
     */
    isPrimary?: boolean | null;
    /**
     * Lookup operator for is_primary (e.g. exact, icontains)
     */
    "is_primary[lookup]"?: string | null;
    /**
     * Filter by verification status
     */
    isVerified?: boolean | null;
    /**
     * Lookup operator for is_verified (e.g. exact, icontains)
     */
    "is_verified[lookup]"?: string | null;
    /**
 * List of fields to sort by (format: field:asc or field:desc).

**Available fields**
- `id`: ID (UUID v7 is time-ordered)
- `professional_type`: Professional type
- `council_state`: Council state
- `graduation_year`: Graduation year
- `created_at`: Creation date

**Default:** id:asc
 */
    sortBy?: string[] | null;
  };
