/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

export type ListUsersSummaryApiV1UsersSummaryGetParams = {
  page?: number | null;
  pageSize?: number | null;
  /**
   * Relationships to expand (eager load).
   */
  expand?: string[] | null;
  /**
   * Only include these relationships or columns.
   */
  only?: string[] | null;
  /**
   * Relationships or columns to omit.
   */
  omit?: string[] | null;
  /**
   * Search by user name or email (partial, case-insensitive)
   */
  search?: string | null;
  /**
   * Lookup operator for search (e.g. exact, icontains)
   */
  "search[lookup]"?: string | null;
  /**
   * Filter by role ID
   */
  roleId?: string[] | null;
  /**
   * Filter by active status
   */
  isActive?: string | null;
  /**
   * Filter by pending invitation status
   */
  isPending?: string | null;
  /**
   * List of fields to sort by (format: field:asc or field:desc).
   */
  sortBy?: string[] | null;
};
