/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

export type ListEducationsApiV1ProfessionalsProfessionalIdEducationsGetParams =
  {
    page?: number | null;
    pageSize?: number | null;
    /**
     * Search by course name or institution (partial, case-insensitive)
     */
    search?: string | null;
    /**
     * Lookup operator for search (e.g. exact, icontains)
     */
    "search[lookup]"?: string | null;
    /**
     * Filter by education level
     */
    level?: string[] | null;
    /**
     * Filter by completion status
     */
    isCompleted?: boolean | null;
    /**
     * Lookup operator for is_completed (e.g. exact, icontains)
     */
    "is_completed[lookup]"?: string | null;
    /**
     * Filter by verification status
     */
    isVerified?: boolean | null;
    /**
     * Lookup operator for is_verified (e.g. exact, icontains)
     */
    "is_verified[lookup]"?: string | null;
    /**
 * List of fields to sort by (format: field:asc or field:desc).

**Available fields**
- `id`: ID (UUID v7 is time-ordered)
- `level`: Education level
- `end_year`: End year
- `created_at`: Creation date

**Default:** id:asc
 */
    sortBy?: string[] | null;
  };
