/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

export type ListSpecialtiesApiV1ProfessionalsProfessionalIdSpecialtiesGetParams =
  {
    page?: number | null;
    pageSize?: number | null;
    /**
     * Relationships to expand (eager load).
     */
    expand?: string[] | null;
    /**
     * Only include these relationships or columns.
     */
    only?: string[] | null;
    /**
     * Relationships or columns to omit.
     */
    omit?: string[] | null;
    /**
     * Search by RQE number (partial, case-insensitive)
     */
    search?: string | null;
    /**
     * Lookup operator for search (e.g. exact, icontains)
     */
    "search[lookup]"?: string | null;
    /**
     * Filter by qualification ID
     */
    qualificationId?: string[] | null;
    /**
     * Filter by verification status
     */
    isVerified?: boolean | null;
    /**
     * Lookup operator for is_verified (e.g. exact, icontains)
     */
    "is_verified[lookup]"?: string | null;
    /**
 * List of fields to sort by (format: field:asc or field:desc).

**Available fields**
- `id`: ID (UUID v7 is time-ordered)
- `acquisition_date`: Acquisition date
- `created_at`: Creation date

**Default:** id:asc
 */
    sortBy?: string[] | null;
  };
