/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Marital status options.
 */
export type MaritalStatus = (typeof MaritalStatus)[keyof typeof MaritalStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MaritalStatus = {
  SINGLE: "SINGLE",
  MARRIED: "MARRIED",
  DIVORCED: "DIVORCED",
  WIDOWED: "WIDOWED",
  SEPARATED: "SEPARATED",
  CIVIL_UNION: "CIVIL_UNION",
} as const;
