/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationProfessionalResponseEmail } from "./organizationProfessionalResponseEmail";
import type { OrganizationProfessionalResponsePhone } from "./organizationProfessionalResponsePhone";
import type { OrganizationProfessionalResponseCpf } from "./organizationProfessionalResponseCpf";
import type { OrganizationProfessionalResponseBirthDate } from "./organizationProfessionalResponseBirthDate";
import type { OrganizationProfessionalResponseNationality } from "./organizationProfessionalResponseNationality";
import type { OrganizationProfessionalResponseGender } from "./organizationProfessionalResponseGender";
import type { OrganizationProfessionalResponseMaritalStatus } from "./organizationProfessionalResponseMaritalStatus";
import type { OrganizationProfessionalResponseAvatarUrl } from "./organizationProfessionalResponseAvatarUrl";
import type { OrganizationProfessionalResponseAddress } from "./organizationProfessionalResponseAddress";
import type { OrganizationProfessionalResponseNumber } from "./organizationProfessionalResponseNumber";
import type { OrganizationProfessionalResponseComplement } from "./organizationProfessionalResponseComplement";
import type { OrganizationProfessionalResponseNeighborhood } from "./organizationProfessionalResponseNeighborhood";
import type { OrganizationProfessionalResponseCity } from "./organizationProfessionalResponseCity";
import type { OrganizationProfessionalResponseStateCode } from "./organizationProfessionalResponseStateCode";
import type { OrganizationProfessionalResponsePostalCode } from "./organizationProfessionalResponsePostalCode";
import type { OrganizationProfessionalResponseVerifiedAt } from "./organizationProfessionalResponseVerifiedAt";
import type { OrganizationProfessionalResponseCreatedAt } from "./organizationProfessionalResponseCreatedAt";
import type { OrganizationProfessionalResponseUpdatedAt } from "./organizationProfessionalResponseUpdatedAt";

/**
 * Schema for organization professional response.
 */
export type OrganizationProfessionalResponse = {
  id: string;
  organizationId: string;
  fullName: string;
  email?: OrganizationProfessionalResponseEmail;
  phone?: OrganizationProfessionalResponsePhone;
  cpf?: OrganizationProfessionalResponseCpf;
  birthDate?: OrganizationProfessionalResponseBirthDate;
  nationality?: OrganizationProfessionalResponseNationality;
  gender?: OrganizationProfessionalResponseGender;
  maritalStatus?: OrganizationProfessionalResponseMaritalStatus;
  avatarUrl?: OrganizationProfessionalResponseAvatarUrl;
  address?: OrganizationProfessionalResponseAddress;
  number?: OrganizationProfessionalResponseNumber;
  complement?: OrganizationProfessionalResponseComplement;
  neighborhood?: OrganizationProfessionalResponseNeighborhood;
  city?: OrganizationProfessionalResponseCity;
  stateCode?: OrganizationProfessionalResponseStateCode;
  postalCode?: OrganizationProfessionalResponsePostalCode;
  verifiedAt?: OrganizationProfessionalResponseVerifiedAt;
  createdAt?: OrganizationProfessionalResponseCreatedAt;
  updatedAt?: OrganizationProfessionalResponseUpdatedAt;
};
