/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationUserListItemAvatarUrl } from "./organizationUserListItemAvatarUrl";

/**
 * Simplified response for listing organization users.
 */
export type OrganizationUserListItem = {
  /** Membership ID */
  id: string;
  /** User ID */
  userId: string;
  /** User's full name */
  fullName: string;
  /** User's email */
  email: string;
  /** User's avatar URL */
  avatarUrl?: OrganizationUserListItemAvatarUrl;
  /** Role code */
  roleCode: string;
  /** Role name */
  roleName: string;
  /** Whether membership is active */
  isActive: boolean;
  /** Whether invitation is pending */
  isPending: boolean;
  /** Membership creation timestamp */
  createdAt: Date;
};
