/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { UserInfo } from "./userInfo.js";
import type { SrcModulesUsersDomainSchemasOrganizationUserRoleInfo } from "./srcModulesUsersDomainSchemasOrganizationUserRoleInfo.js";
import type { OrganizationUserResponseInvitedAt } from "./organizationUserResponseInvitedAt.js";
import type { OrganizationUserResponseAcceptedAt } from "./organizationUserResponseAcceptedAt.js";
import type { OrganizationUserResponseExpiresAt } from "./organizationUserResponseExpiresAt.js";

/**
 * Response schema for organization user (membership).
 */
export type OrganizationUserResponse = {
  /** Membership ID */
  id: string;
  /** User information */
  user: UserInfo;
  /** Assigned role */
  role: SrcModulesUsersDomainSchemasOrganizationUserRoleInfo;
  /** Organization ID */
  organizationId: string;
  /** Whether membership is active */
  isActive: boolean;
  /** Whether invitation is pending */
  isPending: boolean;
  /** When invitation was sent */
  invitedAt?: OrganizationUserResponseInvitedAt;
  /** When invitation was accepted */
  acceptedAt?: OrganizationUserResponseAcceptedAt;
  /** When role was granted */
  grantedAt: Date;
  /** When role expires */
  expiresAt?: OrganizationUserResponseExpiresAt;
  /** Record creation timestamp */
  createdAt: Date;
};
