/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { QualificationNestedUpdate } from "./qualificationNestedUpdate.js";

/**
 * The professional's qualification with specialties and educations (null = no changes)
 */
export type OrganizationProfessionalCompositeUpdateQualification =
  QualificationNestedUpdate | null;
