/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationUserUpdateRoleId } from "./organizationUserUpdateRoleId.js";
import type { OrganizationUserUpdateIsActive } from "./organizationUserUpdateIsActive.js";

/**
 * Schema for updating a user's role in an organization.
 */
export type OrganizationUserUpdate = {
  /** New role ID to assign */
  roleId?: OrganizationUserUpdateRoleId;
  /** Whether the membership is active */
  isActive?: OrganizationUserUpdateIsActive;
};
