/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationProfessionalListItemAvatarUrl } from "./organizationProfessionalListItemAvatarUrl.js";
import type { OrganizationProfessionalListItemCity } from "./organizationProfessionalListItemCity.js";
import type { OrganizationProfessionalListItemStateCode } from "./organizationProfessionalListItemStateCode.js";
import type { OrganizationProfessionalListItemCpf } from "./organizationProfessionalListItemCpf.js";
import type { OrganizationProfessionalListItemPhone } from "./organizationProfessionalListItemPhone.js";
import type { OrganizationProfessionalListItemEmail } from "./organizationProfessionalListItemEmail.js";
import type { OrganizationProfessionalListItemQualification } from "./organizationProfessionalListItemQualification.js";
import type { SpecialtySummary } from "./specialtySummary.js";

/**
 * Simplified schema for professional list responses.
 */
export type OrganizationProfessionalListItem = {
  id: string;
  avatarUrl?: OrganizationProfessionalListItemAvatarUrl;
  fullName: string;
  city?: OrganizationProfessionalListItemCity;
  stateCode?: OrganizationProfessionalListItemStateCode;
  cpf?: OrganizationProfessionalListItemCpf;
  phone?: OrganizationProfessionalListItemPhone;
  email?: OrganizationProfessionalListItemEmail;
  qualification?: OrganizationProfessionalListItemQualification;
  specialties?: SpecialtySummary[];
};
