/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationProfessionalCreateEmail } from "./organizationProfessionalCreateEmail.js";
import type { OrganizationProfessionalCreatePhone } from "./organizationProfessionalCreatePhone.js";
import type { OrganizationProfessionalCreateCpf } from "./organizationProfessionalCreateCpf.js";
import type { OrganizationProfessionalCreateBirthDate } from "./organizationProfessionalCreateBirthDate.js";
import type { OrganizationProfessionalCreateNationality } from "./organizationProfessionalCreateNationality.js";
import type { OrganizationProfessionalCreateGender } from "./organizationProfessionalCreateGender.js";
import type { OrganizationProfessionalCreateMaritalStatus } from "./organizationProfessionalCreateMaritalStatus.js";
import type { OrganizationProfessionalCreateAvatarUrl } from "./organizationProfessionalCreateAvatarUrl.js";
import type { OrganizationProfessionalCreateStateCode } from "./organizationProfessionalCreateStateCode.js";
import type { OrganizationProfessionalCreateAddress } from "./organizationProfessionalCreateAddress.js";
import type { OrganizationProfessionalCreateNumber } from "./organizationProfessionalCreateNumber.js";
import type { OrganizationProfessionalCreateComplement } from "./organizationProfessionalCreateComplement.js";
import type { OrganizationProfessionalCreateNeighborhood } from "./organizationProfessionalCreateNeighborhood.js";

/**
 * Schema for creating an organization professional.
 */
export type OrganizationProfessionalCreate = {
  /**
   * Professional's full name
   * @maxLength 255
   */
  fullName: string;
  /** Professional's email address */
  email?: OrganizationProfessionalCreateEmail;
  /** Phone number (E.164 format) */
  phone?: OrganizationProfessionalCreatePhone;
  /** Brazilian CPF (11 digits, no formatting) */
  cpf?: OrganizationProfessionalCreateCpf;
  /** Date of birth (YYYY-MM-DD) */
  birthDate?: OrganizationProfessionalCreateBirthDate;
  /** Nationality */
  nationality?: OrganizationProfessionalCreateNationality;
  /** Gender */
  gender?: OrganizationProfessionalCreateGender;
  /** Marital status */
  maritalStatus?: OrganizationProfessionalCreateMaritalStatus;
  /** Profile picture URL */
  avatarUrl?: OrganizationProfessionalCreateAvatarUrl;
  /**
   * City name
   * @maxLength 100
   */
  city: string;
  /**
   * State code (e.g., SP, RJ)
   * @pattern ^[A-Z]{2}$
   */
  stateCode: OrganizationProfessionalCreateStateCode;
  /**
   * Postal code (CEP)
   * @maxLength 10
   */
  postalCode: string;
  address?: OrganizationProfessionalCreateAddress;
  number?: OrganizationProfessionalCreateNumber;
  complement?: OrganizationProfessionalCreateComplement;
  neighborhood?: OrganizationProfessionalCreateNeighborhood;
};
