/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationUserInviteFullName } from "./organizationUserInviteFullName";

/**
 * Schema for inviting a user to an organization.
 */
export type OrganizationUserInvite = {
  /** Email address of the user to invite */
  email: string;
  /** Role to assign to the user */
  roleId: string;
  /** Name of the invitee (optional, for new users) */
  fullName?: OrganizationUserInviteFullName;
};
