/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationProfessionalCompositeCreateEmail } from "./organizationProfessionalCompositeCreateEmail.js";
import type { OrganizationProfessionalCompositeCreatePhone } from "./organizationProfessionalCompositeCreatePhone.js";
import type { OrganizationProfessionalCompositeCreateCpf } from "./organizationProfessionalCompositeCreateCpf.js";
import type { OrganizationProfessionalCompositeCreateBirthDate } from "./organizationProfessionalCompositeCreateBirthDate.js";
import type { OrganizationProfessionalCompositeCreateNationality } from "./organizationProfessionalCompositeCreateNationality.js";
import type { OrganizationProfessionalCompositeCreateGender } from "./organizationProfessionalCompositeCreateGender.js";
import type { OrganizationProfessionalCompositeCreateMaritalStatus } from "./organizationProfessionalCompositeCreateMaritalStatus.js";
import type { OrganizationProfessionalCompositeCreateAvatarUrl } from "./organizationProfessionalCompositeCreateAvatarUrl.js";
import type { OrganizationProfessionalCompositeCreateStateCode } from "./organizationProfessionalCompositeCreateStateCode.js";
import type { OrganizationProfessionalCompositeCreateAddress } from "./organizationProfessionalCompositeCreateAddress.js";
import type { OrganizationProfessionalCompositeCreateNumber } from "./organizationProfessionalCompositeCreateNumber.js";
import type { OrganizationProfessionalCompositeCreateComplement } from "./organizationProfessionalCompositeCreateComplement.js";
import type { OrganizationProfessionalCompositeCreateNeighborhood } from "./organizationProfessionalCompositeCreateNeighborhood.js";
import type { QualificationNestedCreate } from "./qualificationNestedCreate.js";

/**
 * Schema for creating a professional with one qualification and nested entities.

Creates in a single transaction:
- Professional (basic info + address)
- One qualification (council registration)
- Specialties for the qualification
- Educations for the qualification
 */
export type OrganizationProfessionalCompositeCreate = {
  /**
   * Professional's full name
   * @maxLength 255
   */
  fullName: string;
  /** Professional's email address */
  email?: OrganizationProfessionalCompositeCreateEmail;
  /** Phone number (E.164 format) */
  phone?: OrganizationProfessionalCompositeCreatePhone;
  /** Brazilian CPF (11 digits, no formatting) */
  cpf?: OrganizationProfessionalCompositeCreateCpf;
  /** Date of birth (YYYY-MM-DD) */
  birthDate?: OrganizationProfessionalCompositeCreateBirthDate;
  /** Nationality */
  nationality?: OrganizationProfessionalCompositeCreateNationality;
  /** Gender */
  gender?: OrganizationProfessionalCompositeCreateGender;
  /** Marital status */
  maritalStatus?: OrganizationProfessionalCompositeCreateMaritalStatus;
  /** Profile picture URL */
  avatarUrl?: OrganizationProfessionalCompositeCreateAvatarUrl;
  /**
   * City name
   * @maxLength 100
   */
  city: string;
  /**
   * State code (e.g., SP, RJ)
   * @pattern ^[A-Z]{2}$
   */
  stateCode: OrganizationProfessionalCompositeCreateStateCode;
  /**
   * Postal code (CEP)
   * @maxLength 10
   */
  postalCode: string;
  address?: OrganizationProfessionalCompositeCreateAddress;
  number?: OrganizationProfessionalCompositeCreateNumber;
  complement?: OrganizationProfessionalCompositeCreateComplement;
  neighborhood?: OrganizationProfessionalCompositeCreateNeighborhood;
  /** The professional's qualification with specialties and educations */
  qualification: QualificationNestedCreate;
};
