/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationProfessionalResponseEmail } from "./organizationProfessionalResponseEmail.js";
import type { OrganizationProfessionalResponsePhone } from "./organizationProfessionalResponsePhone.js";
import type { OrganizationProfessionalResponseCpf } from "./organizationProfessionalResponseCpf.js";
import type { OrganizationProfessionalResponseBirthDate } from "./organizationProfessionalResponseBirthDate.js";
import type { OrganizationProfessionalResponseNationality } from "./organizationProfessionalResponseNationality.js";
import type { OrganizationProfessionalResponseGender } from "./organizationProfessionalResponseGender.js";
import type { OrganizationProfessionalResponseMaritalStatus } from "./organizationProfessionalResponseMaritalStatus.js";
import type { OrganizationProfessionalResponseAvatarUrl } from "./organizationProfessionalResponseAvatarUrl.js";
import type { OrganizationProfessionalResponseAddress } from "./organizationProfessionalResponseAddress.js";
import type { OrganizationProfessionalResponseNumber } from "./organizationProfessionalResponseNumber.js";
import type { OrganizationProfessionalResponseComplement } from "./organizationProfessionalResponseComplement.js";
import type { OrganizationProfessionalResponseNeighborhood } from "./organizationProfessionalResponseNeighborhood.js";
import type { OrganizationProfessionalResponseCity } from "./organizationProfessionalResponseCity.js";
import type { OrganizationProfessionalResponseStateCode } from "./organizationProfessionalResponseStateCode.js";
import type { OrganizationProfessionalResponsePostalCode } from "./organizationProfessionalResponsePostalCode.js";
import type { OrganizationProfessionalResponseVerifiedAt } from "./organizationProfessionalResponseVerifiedAt.js";
import type { OrganizationProfessionalResponseCreatedAt } from "./organizationProfessionalResponseCreatedAt.js";
import type { OrganizationProfessionalResponseUpdatedAt } from "./organizationProfessionalResponseUpdatedAt.js";

/**
 * Schema for organization professional response.
 */
export type OrganizationProfessionalResponse = {
  id: string;
  organizationId: string;
  fullName: string;
  email?: OrganizationProfessionalResponseEmail;
  phone?: OrganizationProfessionalResponsePhone;
  cpf?: OrganizationProfessionalResponseCpf;
  birthDate?: OrganizationProfessionalResponseBirthDate;
  nationality?: OrganizationProfessionalResponseNationality;
  gender?: OrganizationProfessionalResponseGender;
  maritalStatus?: OrganizationProfessionalResponseMaritalStatus;
  avatarUrl?: OrganizationProfessionalResponseAvatarUrl;
  address?: OrganizationProfessionalResponseAddress;
  number?: OrganizationProfessionalResponseNumber;
  complement?: OrganizationProfessionalResponseComplement;
  neighborhood?: OrganizationProfessionalResponseNeighborhood;
  city?: OrganizationProfessionalResponseCity;
  stateCode?: OrganizationProfessionalResponseStateCode;
  postalCode?: OrganizationProfessionalResponsePostalCode;
  verifiedAt?: OrganizationProfessionalResponseVerifiedAt;
  createdAt?: OrganizationProfessionalResponseCreatedAt;
  updatedAt?: OrganizationProfessionalResponseUpdatedAt;
};
