/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { SrcModulesUsersDomainSchemasUserRoleInfo } from "./srcModulesUsersDomainSchemasUserRoleInfo.js";
import type { OrganizationMembershipInfoParent } from "./organizationMembershipInfoParent.js";

/**
 * Organization membership info for user response.

Roles are grouped by organization - a user can have multiple roles
in the same organization.
 */
export type OrganizationMembershipInfo = {
  organizationId: string;
  organizationName: string;
  isActive: boolean;
  roles?: SrcModulesUsersDomainSchemasUserRoleInfo[];
  parent?: OrganizationMembershipInfoParent;
};
