/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationProfessionalUpdateFullName } from "./organizationProfessionalUpdateFullName.js";
import type { OrganizationProfessionalUpdateEmail } from "./organizationProfessionalUpdateEmail.js";
import type { OrganizationProfessionalUpdatePhone } from "./organizationProfessionalUpdatePhone.js";
import type { OrganizationProfessionalUpdateCpf } from "./organizationProfessionalUpdateCpf.js";
import type { OrganizationProfessionalUpdateBirthDate } from "./organizationProfessionalUpdateBirthDate.js";
import type { OrganizationProfessionalUpdateNationality } from "./organizationProfessionalUpdateNationality.js";
import type { OrganizationProfessionalUpdateGender } from "./organizationProfessionalUpdateGender.js";
import type { OrganizationProfessionalUpdateMaritalStatus } from "./organizationProfessionalUpdateMaritalStatus.js";
import type { OrganizationProfessionalUpdateAvatarUrl } from "./organizationProfessionalUpdateAvatarUrl.js";
import type { OrganizationProfessionalUpdateAddress } from "./organizationProfessionalUpdateAddress.js";
import type { OrganizationProfessionalUpdateNumber } from "./organizationProfessionalUpdateNumber.js";
import type { OrganizationProfessionalUpdateComplement } from "./organizationProfessionalUpdateComplement.js";
import type { OrganizationProfessionalUpdateNeighborhood } from "./organizationProfessionalUpdateNeighborhood.js";
import type { OrganizationProfessionalUpdateCity } from "./organizationProfessionalUpdateCity.js";
import type { OrganizationProfessionalUpdateStateCode } from "./organizationProfessionalUpdateStateCode.js";
import type { OrganizationProfessionalUpdatePostalCode } from "./organizationProfessionalUpdatePostalCode.js";

/**
 * Schema for updating an organization professional (PATCH - partial update).
 */
export type OrganizationProfessionalUpdate = {
  /** Professional's full name */
  fullName?: OrganizationProfessionalUpdateFullName;
  /** Professional's email address */
  email?: OrganizationProfessionalUpdateEmail;
  /** Phone number (E.164 format) */
  phone?: OrganizationProfessionalUpdatePhone;
  /** Brazilian CPF (11 digits, no formatting) */
  cpf?: OrganizationProfessionalUpdateCpf;
  /** Date of birth (YYYY-MM-DD) */
  birthDate?: OrganizationProfessionalUpdateBirthDate;
  /** Nationality */
  nationality?: OrganizationProfessionalUpdateNationality;
  /** Gender */
  gender?: OrganizationProfessionalUpdateGender;
  /** Marital status */
  maritalStatus?: OrganizationProfessionalUpdateMaritalStatus;
  /** Profile picture URL */
  avatarUrl?: OrganizationProfessionalUpdateAvatarUrl;
  address?: OrganizationProfessionalUpdateAddress;
  number?: OrganizationProfessionalUpdateNumber;
  complement?: OrganizationProfessionalUpdateComplement;
  neighborhood?: OrganizationProfessionalUpdateNeighborhood;
  city?: OrganizationProfessionalUpdateCity;
  stateCode?: OrganizationProfessionalUpdateStateCode;
  postalCode?: OrganizationProfessionalUpdatePostalCode;
};
