/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationProfessionalDetailResponseEmail } from "./organizationProfessionalDetailResponseEmail";
import type { OrganizationProfessionalDetailResponsePhone } from "./organizationProfessionalDetailResponsePhone";
import type { OrganizationProfessionalDetailResponseCpf } from "./organizationProfessionalDetailResponseCpf";
import type { OrganizationProfessionalDetailResponseBirthDate } from "./organizationProfessionalDetailResponseBirthDate";
import type { OrganizationProfessionalDetailResponseNationality } from "./organizationProfessionalDetailResponseNationality";
import type { OrganizationProfessionalDetailResponseGender } from "./organizationProfessionalDetailResponseGender";
import type { OrganizationProfessionalDetailResponseMaritalStatus } from "./organizationProfessionalDetailResponseMaritalStatus";
import type { OrganizationProfessionalDetailResponseAvatarUrl } from "./organizationProfessionalDetailResponseAvatarUrl";
import type { OrganizationProfessionalDetailResponseAddress } from "./organizationProfessionalDetailResponseAddress";
import type { OrganizationProfessionalDetailResponseNumber } from "./organizationProfessionalDetailResponseNumber";
import type { OrganizationProfessionalDetailResponseComplement } from "./organizationProfessionalDetailResponseComplement";
import type { OrganizationProfessionalDetailResponseNeighborhood } from "./organizationProfessionalDetailResponseNeighborhood";
import type { OrganizationProfessionalDetailResponseCity } from "./organizationProfessionalDetailResponseCity";
import type { OrganizationProfessionalDetailResponseStateCode } from "./organizationProfessionalDetailResponseStateCode";
import type { OrganizationProfessionalDetailResponsePostalCode } from "./organizationProfessionalDetailResponsePostalCode";
import type { ProfessionalQualificationDetailResponse } from "./professionalQualificationDetailResponse";
import type { ProfessionalDocumentResponse } from "./professionalDocumentResponse";
import type { ProfessionalCompanyDetailResponse } from "./professionalCompanyDetailResponse";
import type { BankAccountResponse } from "./bankAccountResponse";
import type { OrganizationProfessionalDetailResponseVerifiedAt } from "./organizationProfessionalDetailResponseVerifiedAt";
import type { OrganizationProfessionalDetailResponseCreatedAt } from "./organizationProfessionalDetailResponseCreatedAt";
import type { OrganizationProfessionalDetailResponseUpdatedAt } from "./organizationProfessionalDetailResponseUpdatedAt";

/**
 * Schema for organization professional with all nested data.

Includes:
- qualifications with specialties (including specialty info), educations, and documents
- documents (profile-level only - qualification_id and specialty_id are None)
- professional_companies with company details and bank accounts
- bank_accounts (professional's direct bank accounts)
 */
export type OrganizationProfessionalDetailResponse = {
  id: string;
  organizationId: string;
  fullName: string;
  email?: OrganizationProfessionalDetailResponseEmail;
  phone?: OrganizationProfessionalDetailResponsePhone;
  cpf?: OrganizationProfessionalDetailResponseCpf;
  birthDate?: OrganizationProfessionalDetailResponseBirthDate;
  nationality?: OrganizationProfessionalDetailResponseNationality;
  gender?: OrganizationProfessionalDetailResponseGender;
  maritalStatus?: OrganizationProfessionalDetailResponseMaritalStatus;
  avatarUrl?: OrganizationProfessionalDetailResponseAvatarUrl;
  address?: OrganizationProfessionalDetailResponseAddress;
  number?: OrganizationProfessionalDetailResponseNumber;
  complement?: OrganizationProfessionalDetailResponseComplement;
  neighborhood?: OrganizationProfessionalDetailResponseNeighborhood;
  city?: OrganizationProfessionalDetailResponseCity;
  stateCode?: OrganizationProfessionalDetailResponseStateCode;
  postalCode?: OrganizationProfessionalDetailResponsePostalCode;
  qualifications?: ProfessionalQualificationDetailResponse[];
  documents?: ProfessionalDocumentResponse[];
  companies?: ProfessionalCompanyDetailResponse[];
  bankAccounts?: BankAccountResponse[];
  verifiedAt?: OrganizationProfessionalDetailResponseVerifiedAt;
  createdAt?: OrganizationProfessionalDetailResponseCreatedAt;
  updatedAt?: OrganizationProfessionalDetailResponseUpdatedAt;
};
