/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationProfessionalDetailResponseEmail } from "./organizationProfessionalDetailResponseEmail.js";
import type { OrganizationProfessionalDetailResponsePhone } from "./organizationProfessionalDetailResponsePhone.js";
import type { OrganizationProfessionalDetailResponseCpf } from "./organizationProfessionalDetailResponseCpf.js";
import type { OrganizationProfessionalDetailResponseBirthDate } from "./organizationProfessionalDetailResponseBirthDate.js";
import type { OrganizationProfessionalDetailResponseNationality } from "./organizationProfessionalDetailResponseNationality.js";
import type { OrganizationProfessionalDetailResponseGender } from "./organizationProfessionalDetailResponseGender.js";
import type { OrganizationProfessionalDetailResponseMaritalStatus } from "./organizationProfessionalDetailResponseMaritalStatus.js";
import type { OrganizationProfessionalDetailResponseAvatarUrl } from "./organizationProfessionalDetailResponseAvatarUrl.js";
import type { OrganizationProfessionalDetailResponseAddress } from "./organizationProfessionalDetailResponseAddress.js";
import type { OrganizationProfessionalDetailResponseNumber } from "./organizationProfessionalDetailResponseNumber.js";
import type { OrganizationProfessionalDetailResponseComplement } from "./organizationProfessionalDetailResponseComplement.js";
import type { OrganizationProfessionalDetailResponseNeighborhood } from "./organizationProfessionalDetailResponseNeighborhood.js";
import type { OrganizationProfessionalDetailResponseCity } from "./organizationProfessionalDetailResponseCity.js";
import type { OrganizationProfessionalDetailResponseStateCode } from "./organizationProfessionalDetailResponseStateCode.js";
import type { OrganizationProfessionalDetailResponsePostalCode } from "./organizationProfessionalDetailResponsePostalCode.js";
import type { ProfessionalQualificationDetailResponse } from "./professionalQualificationDetailResponse.js";
import type { ProfessionalDocumentResponse } from "./professionalDocumentResponse.js";
import type { ProfessionalCompanyDetailResponse } from "./professionalCompanyDetailResponse.js";
import type { BankAccountResponse } from "./bankAccountResponse.js";
import type { OrganizationProfessionalDetailResponseVerifiedAt } from "./organizationProfessionalDetailResponseVerifiedAt.js";
import type { OrganizationProfessionalDetailResponseCreatedAt } from "./organizationProfessionalDetailResponseCreatedAt.js";
import type { OrganizationProfessionalDetailResponseUpdatedAt } from "./organizationProfessionalDetailResponseUpdatedAt.js";

/**
 * Schema for organization professional with all nested data.

Includes:
- qualifications with specialties (including specialty info), educations, and documents
- documents (profile-level only - qualification_id and specialty_id are None)
- professional_companies with company details and bank accounts
- bank_accounts (professional's direct bank accounts)
 */
export type OrganizationProfessionalDetailResponse = {
  id: string;
  organizationId: string;
  fullName: string;
  email?: OrganizationProfessionalDetailResponseEmail;
  phone?: OrganizationProfessionalDetailResponsePhone;
  cpf?: OrganizationProfessionalDetailResponseCpf;
  birthDate?: OrganizationProfessionalDetailResponseBirthDate;
  nationality?: OrganizationProfessionalDetailResponseNationality;
  gender?: OrganizationProfessionalDetailResponseGender;
  maritalStatus?: OrganizationProfessionalDetailResponseMaritalStatus;
  avatarUrl?: OrganizationProfessionalDetailResponseAvatarUrl;
  address?: OrganizationProfessionalDetailResponseAddress;
  number?: OrganizationProfessionalDetailResponseNumber;
  complement?: OrganizationProfessionalDetailResponseComplement;
  neighborhood?: OrganizationProfessionalDetailResponseNeighborhood;
  city?: OrganizationProfessionalDetailResponseCity;
  stateCode?: OrganizationProfessionalDetailResponseStateCode;
  postalCode?: OrganizationProfessionalDetailResponsePostalCode;
  qualifications?: ProfessionalQualificationDetailResponse[];
  documents?: ProfessionalDocumentResponse[];
  companies?: ProfessionalCompanyDetailResponse[];
  bankAccounts?: BankAccountResponse[];
  verifiedAt?: OrganizationProfessionalDetailResponseVerifiedAt;
  createdAt?: OrganizationProfessionalDetailResponseCreatedAt;
  updatedAt?: OrganizationProfessionalDetailResponseUpdatedAt;
};
