/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationProfessionalCompositeUpdateFullName } from "./organizationProfessionalCompositeUpdateFullName.js";
import type { OrganizationProfessionalCompositeUpdateEmail } from "./organizationProfessionalCompositeUpdateEmail.js";
import type { OrganizationProfessionalCompositeUpdatePhone } from "./organizationProfessionalCompositeUpdatePhone.js";
import type { OrganizationProfessionalCompositeUpdateCpf } from "./organizationProfessionalCompositeUpdateCpf.js";
import type { OrganizationProfessionalCompositeUpdateBirthDate } from "./organizationProfessionalCompositeUpdateBirthDate.js";
import type { OrganizationProfessionalCompositeUpdateNationality } from "./organizationProfessionalCompositeUpdateNationality.js";
import type { OrganizationProfessionalCompositeUpdateGender } from "./organizationProfessionalCompositeUpdateGender.js";
import type { OrganizationProfessionalCompositeUpdateMaritalStatus } from "./organizationProfessionalCompositeUpdateMaritalStatus.js";
import type { OrganizationProfessionalCompositeUpdateAvatarUrl } from "./organizationProfessionalCompositeUpdateAvatarUrl.js";
import type { OrganizationProfessionalCompositeUpdateAddress } from "./organizationProfessionalCompositeUpdateAddress.js";
import type { OrganizationProfessionalCompositeUpdateNumber } from "./organizationProfessionalCompositeUpdateNumber.js";
import type { OrganizationProfessionalCompositeUpdateComplement } from "./organizationProfessionalCompositeUpdateComplement.js";
import type { OrganizationProfessionalCompositeUpdateNeighborhood } from "./organizationProfessionalCompositeUpdateNeighborhood.js";
import type { OrganizationProfessionalCompositeUpdateCity } from "./organizationProfessionalCompositeUpdateCity.js";
import type { OrganizationProfessionalCompositeUpdateStateCode } from "./organizationProfessionalCompositeUpdateStateCode.js";
import type { OrganizationProfessionalCompositeUpdatePostalCode } from "./organizationProfessionalCompositeUpdatePostalCode.js";
import type { OrganizationProfessionalCompositeUpdateQualification } from "./organizationProfessionalCompositeUpdateQualification.js";

/**
 * Schema for updating a professional with qualification and nested entities.

Supports partial updates with the following strategy:
- Professional fields: PATCH semantics (only update provided fields)
- Qualification: identified by ID, update provided fields
- Specialties/Educations:
  - With ID: update existing entity
  - Without ID: create new entity
  - IDs not in list: soft delete (if not None)
  - None list: no changes to that entity type
 */
export type OrganizationProfessionalCompositeUpdate = {
  /** Professional's full name */
  fullName?: OrganizationProfessionalCompositeUpdateFullName;
  /** Professional's email address */
  email?: OrganizationProfessionalCompositeUpdateEmail;
  /** Phone number (E.164 format) */
  phone?: OrganizationProfessionalCompositeUpdatePhone;
  /** Brazilian CPF (11 digits, no formatting) */
  cpf?: OrganizationProfessionalCompositeUpdateCpf;
  /** Date of birth (YYYY-MM-DD) */
  birthDate?: OrganizationProfessionalCompositeUpdateBirthDate;
  /** Nationality */
  nationality?: OrganizationProfessionalCompositeUpdateNationality;
  /** Gender */
  gender?: OrganizationProfessionalCompositeUpdateGender;
  /** Marital status */
  maritalStatus?: OrganizationProfessionalCompositeUpdateMaritalStatus;
  /** Profile picture URL */
  avatarUrl?: OrganizationProfessionalCompositeUpdateAvatarUrl;
  address?: OrganizationProfessionalCompositeUpdateAddress;
  number?: OrganizationProfessionalCompositeUpdateNumber;
  complement?: OrganizationProfessionalCompositeUpdateComplement;
  neighborhood?: OrganizationProfessionalCompositeUpdateNeighborhood;
  city?: OrganizationProfessionalCompositeUpdateCity;
  /** State code (e.g., SP, RJ) */
  stateCode?: OrganizationProfessionalCompositeUpdateStateCode;
  postalCode?: OrganizationProfessionalCompositeUpdatePostalCode;
  /** The professional's qualification with specialties and educations (null = no changes) */
  qualification?: OrganizationProfessionalCompositeUpdateQualification;
};
