/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationProfessionalSummaryCpf } from "./organizationProfessionalSummaryCpf.js";
import type { OrganizationProfessionalSummaryPhone } from "./organizationProfessionalSummaryPhone.js";
import type { OrganizationProfessionalSummaryEmail } from "./organizationProfessionalSummaryEmail.js";
import type { OrganizationProfessionalSummaryAvatarUrl } from "./organizationProfessionalSummaryAvatarUrl.js";

/**
 * Summary of an organization professional for screening responses.
 */
export type OrganizationProfessionalSummary = {
  id: string;
  fullName: string;
  cpf?: OrganizationProfessionalSummaryCpf;
  phone?: OrganizationProfessionalSummaryPhone;
  email?: OrganizationProfessionalSummaryEmail;
  avatarUrl?: OrganizationProfessionalSummaryAvatarUrl;
};
