/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { PersonalInfoInputEmail } from "./personalInfoInputEmail.js";
import type { PersonalInfoInputPhone } from "./personalInfoInputPhone.js";
import type { PersonalInfoInputCpf } from "./personalInfoInputCpf.js";
import type { PersonalInfoInputBirthDate } from "./personalInfoInputBirthDate.js";
import type { PersonalInfoInputNationality } from "./personalInfoInputNationality.js";
import type { PersonalInfoInputGender } from "./personalInfoInputGender.js";
import type { PersonalInfoInputMaritalStatus } from "./personalInfoInputMaritalStatus.js";
import type { PersonalInfoInputAvatarUrl } from "./personalInfoInputAvatarUrl.js";
import type { PersonalInfoInputAddress } from "./personalInfoInputAddress.js";
import type { PersonalInfoInputNumber } from "./personalInfoInputNumber.js";
import type { PersonalInfoInputComplement } from "./personalInfoInputComplement.js";
import type { PersonalInfoInputNeighborhood } from "./personalInfoInputNeighborhood.js";
import type { PersonalInfoInputCity } from "./personalInfoInputCity.js";
import type { PersonalInfoInputStateCode } from "./personalInfoInputStateCode.js";
import type { PersonalInfoInputPostalCode } from "./personalInfoInputPostalCode.js";

/**
 * Input schema for professional personal information.
 */
export type PersonalInfoInput = {
  /**
   * Professional's full name
   * @maxLength 255
   */
  fullName: string;
  /** Email address */
  email?: PersonalInfoInputEmail;
  /** Phone (E.164 format) */
  phone?: PersonalInfoInputPhone;
  /** CPF (11 digits) */
  cpf?: PersonalInfoInputCpf;
  /** Date of birth */
  birthDate?: PersonalInfoInputBirthDate;
  nationality?: PersonalInfoInputNationality;
  gender?: PersonalInfoInputGender;
  maritalStatus?: PersonalInfoInputMaritalStatus;
  /** Profile picture */
  avatarUrl?: PersonalInfoInputAvatarUrl;
  address?: PersonalInfoInputAddress;
  number?: PersonalInfoInputNumber;
  complement?: PersonalInfoInputComplement;
  neighborhood?: PersonalInfoInputNeighborhood;
  city?: PersonalInfoInputCity;
  stateCode?: PersonalInfoInputStateCode;
  postalCode?: PersonalInfoInputPostalCode;
  isVerified?: boolean;
};
