/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalDocumentResponseQualificationId } from "./professionalDocumentResponseQualificationId";
import type { ProfessionalDocumentResponseSpecialtyId } from "./professionalDocumentResponseSpecialtyId";
import type { ProfessionalDocumentResponseFileSize } from "./professionalDocumentResponseFileSize";
import type { ProfessionalDocumentResponseMimeType } from "./professionalDocumentResponseMimeType";
import type { ProfessionalDocumentResponseExpiresAt } from "./professionalDocumentResponseExpiresAt";
import type { ProfessionalDocumentResponseNotes } from "./professionalDocumentResponseNotes";
import type { ProfessionalDocumentResponseDocumentTypeCode } from "./professionalDocumentResponseDocumentTypeCode";
import type { ProfessionalDocumentResponseDocumentTypeName } from "./professionalDocumentResponseDocumentTypeName";
import type { ProfessionalDocumentResponseDocumentCategory } from "./professionalDocumentResponseDocumentCategory";
import type { DocumentSourceType } from "./documentSourceType";
import type { ProfessionalDocumentResponseScreeningId } from "./professionalDocumentResponseScreeningId";
import type { ProfessionalDocumentResponsePromotedAt } from "./professionalDocumentResponsePromotedAt";
import type { ProfessionalDocumentResponsePromotedBy } from "./professionalDocumentResponsePromotedBy";
import type { ProfessionalDocumentResponseCreatedAt } from "./professionalDocumentResponseCreatedAt";
import type { ProfessionalDocumentResponseUpdatedAt } from "./professionalDocumentResponseUpdatedAt";

/**
 * Schema for professional document response.
 */
export type ProfessionalDocumentResponse = {
  id: string;
  organizationProfessionalId: string;
  documentTypeId: string;
  qualificationId?: ProfessionalDocumentResponseQualificationId;
  specialtyId?: ProfessionalDocumentResponseSpecialtyId;
  fileUrl: string;
  fileName: string;
  fileSize?: ProfessionalDocumentResponseFileSize;
  mimeType?: ProfessionalDocumentResponseMimeType;
  expiresAt?: ProfessionalDocumentResponseExpiresAt;
  notes?: ProfessionalDocumentResponseNotes;
  documentTypeCode?: ProfessionalDocumentResponseDocumentTypeCode;
  documentTypeName?: ProfessionalDocumentResponseDocumentTypeName;
  documentCategory?: ProfessionalDocumentResponseDocumentCategory;
  isVerified?: boolean;
  isPending?: boolean;
  sourceType?: DocumentSourceType;
  screeningId?: ProfessionalDocumentResponseScreeningId;
  promotedAt?: ProfessionalDocumentResponsePromotedAt;
  promotedBy?: ProfessionalDocumentResponsePromotedBy;
  createdAt?: ProfessionalDocumentResponseCreatedAt;
  updatedAt?: ProfessionalDocumentResponseUpdatedAt;
};
