/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Types of healthcare professionals.

Defines the main category of healthcare worker.
 */
export type ProfessionalType =
  (typeof ProfessionalType)[keyof typeof ProfessionalType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfessionalType = {
  DOCTOR: "DOCTOR",
  NURSE: "NURSE",
  NURSING_TECH: "NURSING_TECH",
  PHARMACIST: "PHARMACIST",
  DENTIST: "DENTIST",
  PHYSIOTHERAPIST: "PHYSIOTHERAPIST",
  PSYCHOLOGIST: "PSYCHOLOGIST",
  NUTRITIONIST: "NUTRITIONIST",
  BIOMEDIC: "BIOMEDIC",
} as const;
