/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { SourceType } from "./sourceType";
import type { ProfessionalVersionListResponseAppliedAt } from "./professionalVersionListResponseAppliedAt";
import type { ProfessionalVersionListResponseRejectedAt } from "./professionalVersionListResponseRejectedAt";

/**
 * Response schema for version list item.
 */
export type ProfessionalVersionListResponse = {
  id: string;
  versionNumber: number;
  isCurrent: boolean;
  sourceType: SourceType;
  appliedAt?: ProfessionalVersionListResponseAppliedAt;
  rejectedAt?: ProfessionalVersionListResponseRejectedAt;
  createdAt: Date;
  isApplied: boolean;
  isRejected: boolean;
  isPending: boolean;
  /** Number of changes in this version */
  changesCount: number;
};
