/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalSpecialtyCreateRqeNumber } from "./professionalSpecialtyCreateRqeNumber.js";
import type { ProfessionalSpecialtyCreateRqeState } from "./professionalSpecialtyCreateRqeState.js";
import type { ResidencyStatus } from "./residencyStatus.js";
import type { ProfessionalSpecialtyCreateResidencyInstitution } from "./professionalSpecialtyCreateResidencyInstitution.js";
import type { ProfessionalSpecialtyCreateResidencyExpectedCompletion } from "./professionalSpecialtyCreateResidencyExpectedCompletion.js";
import type { ProfessionalSpecialtyCreateCertificateUrl } from "./professionalSpecialtyCreateCertificateUrl.js";

/**
 * Schema for creating a professional specialty.
 */
export type ProfessionalSpecialtyCreate = {
  /** The specialty UUID */
  specialtyId: string;
  /** Whether this is the primary specialty */
  isPrimary?: boolean;
  /** RQE number (for doctors) */
  rqeNumber?: ProfessionalSpecialtyCreateRqeNumber;
  /** State where RQE is registered (e.g., SP, RJ) */
  rqeState?: ProfessionalSpecialtyCreateRqeState;
  /** Current residency/training status */
  residencyStatus?: ResidencyStatus;
  /** Institution where residency is being done */
  residencyInstitution?: ProfessionalSpecialtyCreateResidencyInstitution;
  /** Expected residency completion date (YYYY-MM-DD) */
  residencyExpectedCompletion?: ProfessionalSpecialtyCreateResidencyExpectedCompletion;
  /** URL to specialty certificate */
  certificateUrl?: ProfessionalSpecialtyCreateCertificateUrl;
};
