/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalType } from "./professionalType";
import type { ProfessionalQualificationCreateGraduationYear } from "./professionalQualificationCreateGraduationYear";
import type { CouncilType } from "./councilType";
import type { ProfessionalQualificationCreateCouncilState } from "./professionalQualificationCreateCouncilState";

/**
 * Schema for creating a professional qualification.
 */
export type ProfessionalQualificationCreate = {
  /** Type of healthcare professional (DOCTOR, NURSE, etc.) */
  professionalType: ProfessionalType;
  /** Whether this is the primary qualification */
  isPrimary?: boolean;
  /** Year of graduation */
  graduationYear?: ProfessionalQualificationCreateGraduationYear;
  /** Council type (CRM, COREN, etc.) */
  councilType: CouncilType;
  /**
   * Council registration number
   * @maxLength 20
   */
  councilNumber: string;
  /**
   * State where the council registration is valid (2 chars, e.g., SP, RJ)
   * @pattern ^[A-Z]{2}$
   */
  councilState: ProfessionalQualificationCreateCouncilState;
};
