/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { EducationLevel } from "./educationLevel.js";
import type { ProfessionalEducationCreateStartYear } from "./professionalEducationCreateStartYear.js";
import type { ProfessionalEducationCreateEndYear } from "./professionalEducationCreateEndYear.js";
import type { ProfessionalEducationCreateWorkloadHours } from "./professionalEducationCreateWorkloadHours.js";
import type { ProfessionalEducationCreateCertificateUrl } from "./professionalEducationCreateCertificateUrl.js";
import type { ProfessionalEducationCreateNotes } from "./professionalEducationCreateNotes.js";

/**
 * Schema for creating a professional education record.
 */
export type ProfessionalEducationCreate = {
  /** Education level (undergraduate, masters, etc.) */
  level: EducationLevel;
  /**
   * Name of the course/degree
   * @maxLength 255
   */
  courseName: string;
  /**
   * Educational institution name
   * @maxLength 255
   */
  institution: string;
  /** Year started */
  startYear?: ProfessionalEducationCreateStartYear;
  /** Year completed (null if ongoing) */
  endYear?: ProfessionalEducationCreateEndYear;
  /** Whether the education is completed */
  isCompleted?: boolean;
  /** Total workload in hours (for courses) */
  workloadHours?: ProfessionalEducationCreateWorkloadHours;
  /** URL to certificate/diploma */
  certificateUrl?: ProfessionalEducationCreateCertificateUrl;
  /** Additional notes */
  notes?: ProfessionalEducationCreateNotes;
};
