/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { StepType } from "./stepType";
import type { StepStatus } from "./stepStatus";
import type { ProfessionalDataStepResponseAssignedTo } from "./professionalDataStepResponseAssignedTo";
import type { ProfessionalDataStepResponseReviewNotes } from "./professionalDataStepResponseReviewNotes";
import type { ProfessionalDataStepResponseRejectionReason } from "./professionalDataStepResponseRejectionReason";
import type { ProfessionalDataStepResponseStartedAt } from "./professionalDataStepResponseStartedAt";
import type { ProfessionalDataStepResponseCompletedAt } from "./professionalDataStepResponseCompletedAt";
import type { ProfessionalDataStepResponseCompletedBy } from "./professionalDataStepResponseCompletedBy";
import type { ProfessionalDataStepResponseReviewedAt } from "./professionalDataStepResponseReviewedAt";
import type { ProfessionalDataStepResponseReviewedBy } from "./professionalDataStepResponseReviewedBy";
import type { ProfessionalDataStepResponseProfessionalId } from "./professionalDataStepResponseProfessionalId";
import type { ProfessionalDataStepResponseProfessionalVersionId } from "./professionalDataStepResponseProfessionalVersionId";

/**
 * Response schema for professional data step.

Includes reference to the professional record.
 */
export type ProfessionalDataStepResponse = {
  id: string;
  stepType: StepType;
  order: number;
  status: StepStatus;
  assignedTo?: ProfessionalDataStepResponseAssignedTo;
  reviewNotes?: ProfessionalDataStepResponseReviewNotes;
  rejectionReason?: ProfessionalDataStepResponseRejectionReason;
  createdAt: Date;
  updatedAt: Date;
  startedAt?: ProfessionalDataStepResponseStartedAt;
  completedAt?: ProfessionalDataStepResponseCompletedAt;
  completedBy?: ProfessionalDataStepResponseCompletedBy;
  reviewedAt?: ProfessionalDataStepResponseReviewedAt;
  reviewedBy?: ProfessionalDataStepResponseReviewedBy;
  professionalId?: ProfessionalDataStepResponseProfessionalId;
  professionalVersionId?: ProfessionalDataStepResponseProfessionalVersionId;
};
