/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ChangeType } from "./changeType.js";
import type { ProfessionalChangeDiffResponseOldValue } from "./professionalChangeDiffResponseOldValue.js";
import type { ProfessionalChangeDiffResponseNewValue } from "./professionalChangeDiffResponseNewValue.js";

/**
 * Response schema for a single change diff.
 */
export type ProfessionalChangeDiffResponse = {
  id: string;
  fieldPath: string;
  changeType: ChangeType;
  oldValue?: ProfessionalChangeDiffResponseOldValue;
  newValue?: ProfessionalChangeDiffResponseNewValue;
  /** Whether this is a nested entity change */
  isNestedChange: boolean;
  /** Root field name */
  rootField: string;
};
