/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalEducationUpdateLevel } from "./professionalEducationUpdateLevel";
import type { ProfessionalEducationUpdateCourseName } from "./professionalEducationUpdateCourseName";
import type { ProfessionalEducationUpdateInstitution } from "./professionalEducationUpdateInstitution";
import type { ProfessionalEducationUpdateStartYear } from "./professionalEducationUpdateStartYear";
import type { ProfessionalEducationUpdateEndYear } from "./professionalEducationUpdateEndYear";
import type { ProfessionalEducationUpdateIsCompleted } from "./professionalEducationUpdateIsCompleted";
import type { ProfessionalEducationUpdateWorkloadHours } from "./professionalEducationUpdateWorkloadHours";
import type { ProfessionalEducationUpdateCertificateUrl } from "./professionalEducationUpdateCertificateUrl";
import type { ProfessionalEducationUpdateNotes } from "./professionalEducationUpdateNotes";

/**
 * Schema for updating a professional education record (PATCH - partial update).
 */
export type ProfessionalEducationUpdate = {
  /** Education level */
  level?: ProfessionalEducationUpdateLevel;
  /** Name of the course/degree */
  courseName?: ProfessionalEducationUpdateCourseName;
  /** Educational institution name */
  institution?: ProfessionalEducationUpdateInstitution;
  /** Year started */
  startYear?: ProfessionalEducationUpdateStartYear;
  /** Year completed */
  endYear?: ProfessionalEducationUpdateEndYear;
  /** Whether the education is completed */
  isCompleted?: ProfessionalEducationUpdateIsCompleted;
  /** Total workload in hours */
  workloadHours?: ProfessionalEducationUpdateWorkloadHours;
  /** URL to certificate/diploma */
  certificateUrl?: ProfessionalEducationUpdateCertificateUrl;
  /** Additional notes */
  notes?: ProfessionalEducationUpdateNotes;
};
