/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalType } from "./professionalType.js";
import type { ProfessionalQualificationDetailResponseGraduationYear } from "./professionalQualificationDetailResponseGraduationYear.js";
import type { CouncilType } from "./councilType.js";
import type { ProfessionalSpecialtyDetailResponse } from "./professionalSpecialtyDetailResponse.js";
import type { ProfessionalEducationResponse } from "./professionalEducationResponse.js";
import type { ProfessionalDocumentResponse } from "./professionalDocumentResponse.js";
import type { ProfessionalQualificationDetailResponseCreatedAt } from "./professionalQualificationDetailResponseCreatedAt.js";
import type { ProfessionalQualificationDetailResponseUpdatedAt } from "./professionalQualificationDetailResponseUpdatedAt.js";

/**
 * Schema for professional qualification with nested data.
 */
export type ProfessionalQualificationDetailResponse = {
  id: string;
  organizationProfessionalId: string;
  organizationId: string;
  professionalType: ProfessionalType;
  isPrimary: boolean;
  graduationYear?: ProfessionalQualificationDetailResponseGraduationYear;
  councilType: CouncilType;
  councilNumber: string;
  councilState: string;
  specialties?: ProfessionalSpecialtyDetailResponse[];
  educations?: ProfessionalEducationResponse[];
  documents?: ProfessionalDocumentResponse[];
  /** True if professional is a doctor with no specialties (clínico geral) */
  isGeneralist?: boolean;
  isVerified?: boolean;
  createdAt?: ProfessionalQualificationDetailResponseCreatedAt;
  updatedAt?: ProfessionalQualificationDetailResponseUpdatedAt;
};
