/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalVersionCreatePersonalInfo } from "./professionalVersionCreatePersonalInfo";
import type { QualificationInput } from "./qualificationInput";
import type { CompanyInput } from "./companyInput";
import type { BankAccountInput } from "./bankAccountInput";
import type { SourceType } from "./sourceType";
import type { ProfessionalVersionCreateSourceId } from "./professionalVersionCreateSourceId";
import type { ProfessionalVersionCreateNotes } from "./professionalVersionCreateNotes";

/**
 * Schema for creating a new professional version.
 */
export type ProfessionalVersionCreate = {
  /** Professional personal information */
  personalInfo?: ProfessionalVersionCreatePersonalInfo;
  /** Professional qualifications */
  qualifications?: QualificationInput[];
  /** Professional companies */
  companies?: CompanyInput[];
  /** Bank accounts */
  bankAccounts?: BankAccountInput[];
  /** How this version was created */
  sourceType?: SourceType;
  /** ID of the source entity (e.g., ScreeningProcess ID) */
  sourceId?: ProfessionalVersionCreateSourceId;
  /** Notes about this version */
  notes?: ProfessionalVersionCreateNotes;
};
