/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalVersionResponseProfessionalId } from "./professionalVersionResponseProfessionalId.js";
import type { ProfessionalVersionResponseDataSnapshot } from "./professionalVersionResponseDataSnapshot.js";
import type { SourceType } from "./sourceType.js";
import type { ProfessionalVersionResponseSourceId } from "./professionalVersionResponseSourceId.js";
import type { ProfessionalVersionResponseAppliedAt } from "./professionalVersionResponseAppliedAt.js";
import type { ProfessionalVersionResponseAppliedBy } from "./professionalVersionResponseAppliedBy.js";
import type { ProfessionalVersionResponseRejectedAt } from "./professionalVersionResponseRejectedAt.js";
import type { ProfessionalVersionResponseRejectedBy } from "./professionalVersionResponseRejectedBy.js";
import type { ProfessionalVersionResponseRejectionReason } from "./professionalVersionResponseRejectionReason.js";
import type { ProfessionalVersionResponseNotes } from "./professionalVersionResponseNotes.js";
import type { ProfessionalVersionResponseCreatedBy } from "./professionalVersionResponseCreatedBy.js";
import type { ProfessionalVersionResponseUpdatedBy } from "./professionalVersionResponseUpdatedBy.js";

/**
 * Response schema for a professional version.
 */
export type ProfessionalVersionResponse = {
  id: string;
  organizationId: string;
  professionalId?: ProfessionalVersionResponseProfessionalId;
  versionNumber: number;
  dataSnapshot: ProfessionalVersionResponseDataSnapshot;
  isCurrent: boolean;
  sourceType: SourceType;
  sourceId?: ProfessionalVersionResponseSourceId;
  appliedAt?: ProfessionalVersionResponseAppliedAt;
  appliedBy?: ProfessionalVersionResponseAppliedBy;
  rejectedAt?: ProfessionalVersionResponseRejectedAt;
  rejectedBy?: ProfessionalVersionResponseRejectedBy;
  rejectionReason?: ProfessionalVersionResponseRejectionReason;
  notes?: ProfessionalVersionResponseNotes;
  createdAt: Date;
  updatedAt: Date;
  createdBy?: ProfessionalVersionResponseCreatedBy;
  updatedBy?: ProfessionalVersionResponseUpdatedBy;
  isApplied: boolean;
  isRejected: boolean;
  isPending: boolean;
  isFromScreening: boolean;
};
