/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for completing professional data step.

No data required - the use case validates that:
- Professional is linked to the process
- Professional has at least one qualification
- Professional type matches expected (if configured)
- Professional has expected specialty (if configured)
 */
export type ProfessionalDataStepCompleteRequest = { [key: string]: unknown };
