/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalQualificationUpdateIsPrimary } from "./professionalQualificationUpdateIsPrimary.js";
import type { ProfessionalQualificationUpdateGraduationYear } from "./professionalQualificationUpdateGraduationYear.js";
import type { ProfessionalQualificationUpdateCouncilNumber } from "./professionalQualificationUpdateCouncilNumber.js";
import type { ProfessionalQualificationUpdateCouncilState } from "./professionalQualificationUpdateCouncilState.js";

/**
 * Schema for updating a professional qualification (PATCH - partial update).
 */
export type ProfessionalQualificationUpdate = {
  /** Whether this is the primary qualification */
  isPrimary?: ProfessionalQualificationUpdateIsPrimary;
  /** Year of graduation */
  graduationYear?: ProfessionalQualificationUpdateGraduationYear;
  /** Council registration number */
  councilNumber?: ProfessionalQualificationUpdateCouncilNumber;
  /** State where the council registration is valid (2 chars, e.g., SP, RJ) */
  councilState?: ProfessionalQualificationUpdateCouncilState;
};
