/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalDocumentUpdateFileUrl } from "./professionalDocumentUpdateFileUrl";
import type { ProfessionalDocumentUpdateFileName } from "./professionalDocumentUpdateFileName";
import type { ProfessionalDocumentUpdateFileSize } from "./professionalDocumentUpdateFileSize";
import type { ProfessionalDocumentUpdateMimeType } from "./professionalDocumentUpdateMimeType";
import type { ProfessionalDocumentUpdateExpiresAt } from "./professionalDocumentUpdateExpiresAt";
import type { ProfessionalDocumentUpdateNotes } from "./professionalDocumentUpdateNotes";

/**
 * Schema for updating a professional document (PATCH - partial update).
 */
export type ProfessionalDocumentUpdate = {
  /** URL to the uploaded file */
  fileUrl?: ProfessionalDocumentUpdateFileUrl;
  /** Original file name */
  fileName?: ProfessionalDocumentUpdateFileName;
  /** File size in bytes */
  fileSize?: ProfessionalDocumentUpdateFileSize;
  /** MIME type of the file */
  mimeType?: ProfessionalDocumentUpdateMimeType;
  /** Expiration date for documents with validity */
  expiresAt?: ProfessionalDocumentUpdateExpiresAt;
  /** Additional notes about this document */
  notes?: ProfessionalDocumentUpdateNotes;
};
