/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalSpecialtyDetailResponseRqeNumber } from "./professionalSpecialtyDetailResponseRqeNumber.js";
import type { ProfessionalSpecialtyDetailResponseRqeState } from "./professionalSpecialtyDetailResponseRqeState.js";
import type { ResidencyStatus } from "./residencyStatus.js";
import type { ProfessionalSpecialtyDetailResponseResidencyInstitution } from "./professionalSpecialtyDetailResponseResidencyInstitution.js";
import type { ProfessionalSpecialtyDetailResponseResidencyExpectedCompletion } from "./professionalSpecialtyDetailResponseResidencyExpectedCompletion.js";
import type { ProfessionalSpecialtyDetailResponseCertificateUrl } from "./professionalSpecialtyDetailResponseCertificateUrl.js";
import type { ProfessionalSpecialtyDetailResponseSpecialty } from "./professionalSpecialtyDetailResponseSpecialty.js";
import type { ProfessionalDocumentResponse } from "./professionalDocumentResponse.js";
import type { ProfessionalSpecialtyDetailResponseCreatedAt } from "./professionalSpecialtyDetailResponseCreatedAt.js";
import type { ProfessionalSpecialtyDetailResponseUpdatedAt } from "./professionalSpecialtyDetailResponseUpdatedAt.js";

/**
 * Schema for professional specialty with nested documents.
 */
export type ProfessionalSpecialtyDetailResponse = {
  id: string;
  qualificationId: string;
  specialtyId: string;
  isPrimary: boolean;
  rqeNumber?: ProfessionalSpecialtyDetailResponseRqeNumber;
  rqeState?: ProfessionalSpecialtyDetailResponseRqeState;
  residencyStatus: ResidencyStatus;
  residencyInstitution?: ProfessionalSpecialtyDetailResponseResidencyInstitution;
  residencyExpectedCompletion?: ProfessionalSpecialtyDetailResponseResidencyExpectedCompletion;
  certificateUrl?: ProfessionalSpecialtyDetailResponseCertificateUrl;
  specialty?: ProfessionalSpecialtyDetailResponseSpecialty;
  documents?: ProfessionalDocumentResponse[];
  isVerified?: boolean;
  createdAt?: ProfessionalSpecialtyDetailResponseCreatedAt;
  updatedAt?: ProfessionalSpecialtyDetailResponseUpdatedAt;
};
