/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalCompanyDetailResponseLeftAt } from "./professionalCompanyDetailResponseLeftAt.js";
import type { ProfessionalCompanyDetailResponseCompany } from "./professionalCompanyDetailResponseCompany.js";
import type { ProfessionalCompanyDetailResponseCreatedAt } from "./professionalCompanyDetailResponseCreatedAt.js";
import type { ProfessionalCompanyDetailResponseUpdatedAt } from "./professionalCompanyDetailResponseUpdatedAt.js";

/**
 * Schema for professional-company link with full company details.
 */
export type ProfessionalCompanyDetailResponse = {
  id: string;
  organizationProfessionalId: string;
  companyId: string;
  joinedAt: string;
  leftAt?: ProfessionalCompanyDetailResponseLeftAt;
  company?: ProfessionalCompanyDetailResponseCompany;
  createdAt?: ProfessionalCompanyDetailResponseCreatedAt;
  updatedAt?: ProfessionalCompanyDetailResponseUpdatedAt;
};
