/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalSpecialtyUpdateIsPrimary } from "./professionalSpecialtyUpdateIsPrimary";
import type { ProfessionalSpecialtyUpdateRqeNumber } from "./professionalSpecialtyUpdateRqeNumber";
import type { ProfessionalSpecialtyUpdateRqeState } from "./professionalSpecialtyUpdateRqeState";
import type { ProfessionalSpecialtyUpdateResidencyStatus } from "./professionalSpecialtyUpdateResidencyStatus";
import type { ProfessionalSpecialtyUpdateResidencyInstitution } from "./professionalSpecialtyUpdateResidencyInstitution";
import type { ProfessionalSpecialtyUpdateResidencyExpectedCompletion } from "./professionalSpecialtyUpdateResidencyExpectedCompletion";
import type { ProfessionalSpecialtyUpdateCertificateUrl } from "./professionalSpecialtyUpdateCertificateUrl";

/**
 * Schema for updating a professional specialty (PATCH - partial update).
 */
export type ProfessionalSpecialtyUpdate = {
  /** Whether this is the primary specialty */
  isPrimary?: ProfessionalSpecialtyUpdateIsPrimary;
  /** RQE number (for doctors) */
  rqeNumber?: ProfessionalSpecialtyUpdateRqeNumber;
  /** State where RQE is registered (e.g., SP, RJ) */
  rqeState?: ProfessionalSpecialtyUpdateRqeState;
  /** Current residency/training status */
  residencyStatus?: ProfessionalSpecialtyUpdateResidencyStatus;
  /** Institution where residency is being done */
  residencyInstitution?: ProfessionalSpecialtyUpdateResidencyInstitution;
  /** Expected residency completion date (YYYY-MM-DD) */
  residencyExpectedCompletion?: ProfessionalSpecialtyUpdateResidencyExpectedCompletion;
  /** URL to specialty certificate */
  certificateUrl?: ProfessionalSpecialtyUpdateCertificateUrl;
};
