/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalCompanyUpdateJoinedAt } from "./professionalCompanyUpdateJoinedAt";
import type { ProfessionalCompanyUpdateLeftAt } from "./professionalCompanyUpdateLeftAt";

/**
 * Schema for updating a professional-company link (PATCH - partial update).
 */
export type ProfessionalCompanyUpdate = {
  /** Timestamp when professional joined the company */
  joinedAt?: ProfessionalCompanyUpdateJoinedAt;
  /** Timestamp when professional left the company */
  leftAt?: ProfessionalCompanyUpdateLeftAt;
};
