/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalCompanyResponseLeftAt } from "./professionalCompanyResponseLeftAt";
import type { ProfessionalCompanyResponseCompany } from "./professionalCompanyResponseCompany";
import type { ProfessionalCompanyResponseCreatedAt } from "./professionalCompanyResponseCreatedAt";
import type { ProfessionalCompanyResponseUpdatedAt } from "./professionalCompanyResponseUpdatedAt";

/**
 * Schema for professional-company link response.
 */
export type ProfessionalCompanyResponse = {
  id: string;
  organizationProfessionalId: string;
  companyId: string;
  joinedAt: string;
  leftAt?: ProfessionalCompanyResponseLeftAt;
  company?: ProfessionalCompanyResponseCompany;
  createdAt?: ProfessionalCompanyResponseCreatedAt;
  updatedAt?: ProfessionalCompanyResponseUpdatedAt;
};
