/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalVersionDetailResponseProfessionalId } from "./professionalVersionDetailResponseProfessionalId";
import type { ProfessionalVersionDetailResponseDataSnapshot } from "./professionalVersionDetailResponseDataSnapshot";
import type { SourceType } from "./sourceType";
import type { ProfessionalVersionDetailResponseSourceId } from "./professionalVersionDetailResponseSourceId";
import type { ProfessionalVersionDetailResponseAppliedAt } from "./professionalVersionDetailResponseAppliedAt";
import type { ProfessionalVersionDetailResponseAppliedBy } from "./professionalVersionDetailResponseAppliedBy";
import type { ProfessionalVersionDetailResponseRejectedAt } from "./professionalVersionDetailResponseRejectedAt";
import type { ProfessionalVersionDetailResponseRejectedBy } from "./professionalVersionDetailResponseRejectedBy";
import type { ProfessionalVersionDetailResponseRejectionReason } from "./professionalVersionDetailResponseRejectionReason";
import type { ProfessionalVersionDetailResponseNotes } from "./professionalVersionDetailResponseNotes";
import type { ProfessionalVersionDetailResponseCreatedBy } from "./professionalVersionDetailResponseCreatedBy";
import type { ProfessionalVersionDetailResponseUpdatedBy } from "./professionalVersionDetailResponseUpdatedBy";
import type { ProfessionalChangeDiffResponse } from "./professionalChangeDiffResponse";

/**
 * Detailed response schema including diffs.
 */
export type ProfessionalVersionDetailResponse = {
  id: string;
  organizationId: string;
  professionalId?: ProfessionalVersionDetailResponseProfessionalId;
  versionNumber: number;
  dataSnapshot: ProfessionalVersionDetailResponseDataSnapshot;
  isCurrent: boolean;
  sourceType: SourceType;
  sourceId?: ProfessionalVersionDetailResponseSourceId;
  appliedAt?: ProfessionalVersionDetailResponseAppliedAt;
  appliedBy?: ProfessionalVersionDetailResponseAppliedBy;
  rejectedAt?: ProfessionalVersionDetailResponseRejectedAt;
  rejectedBy?: ProfessionalVersionDetailResponseRejectedBy;
  rejectionReason?: ProfessionalVersionDetailResponseRejectionReason;
  notes?: ProfessionalVersionDetailResponseNotes;
  createdAt: Date;
  updatedAt: Date;
  createdBy?: ProfessionalVersionDetailResponseCreatedBy;
  updatedBy?: ProfessionalVersionDetailResponseUpdatedBy;
  isApplied: boolean;
  isRejected: boolean;
  isPending: boolean;
  isFromScreening: boolean;
  diffs?: ProfessionalChangeDiffResponse[];
};
