/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { EducationLevel } from "./educationLevel.js";
import type { ProfessionalEducationResponseStartYear } from "./professionalEducationResponseStartYear.js";
import type { ProfessionalEducationResponseEndYear } from "./professionalEducationResponseEndYear.js";
import type { ProfessionalEducationResponseWorkloadHours } from "./professionalEducationResponseWorkloadHours.js";
import type { ProfessionalEducationResponseCertificateUrl } from "./professionalEducationResponseCertificateUrl.js";
import type { ProfessionalEducationResponseNotes } from "./professionalEducationResponseNotes.js";
import type { ProfessionalEducationResponseCreatedAt } from "./professionalEducationResponseCreatedAt.js";
import type { ProfessionalEducationResponseUpdatedAt } from "./professionalEducationResponseUpdatedAt.js";

/**
 * Schema for professional education response.
 */
export type ProfessionalEducationResponse = {
  id: string;
  qualificationId: string;
  level: EducationLevel;
  courseName: string;
  institution: string;
  startYear?: ProfessionalEducationResponseStartYear;
  endYear?: ProfessionalEducationResponseEndYear;
  isCompleted: boolean;
  workloadHours?: ProfessionalEducationResponseWorkloadHours;
  certificateUrl?: ProfessionalEducationResponseCertificateUrl;
  notes?: ProfessionalEducationResponseNotes;
  isVerified?: boolean;
  createdAt?: ProfessionalEducationResponseCreatedAt;
  updatedAt?: ProfessionalEducationResponseUpdatedAt;
};
