/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { StepType } from "./stepType.js";
import type { StepStatus } from "./stepStatus.js";
import type { ProfessionalDataStepResponseAssignedTo } from "./professionalDataStepResponseAssignedTo.js";
import type { ProfessionalDataStepResponseReviewNotes } from "./professionalDataStepResponseReviewNotes.js";
import type { ProfessionalDataStepResponseRejectionReason } from "./professionalDataStepResponseRejectionReason.js";
import type { ProfessionalDataStepResponseStartedAt } from "./professionalDataStepResponseStartedAt.js";
import type { ProfessionalDataStepResponseCompletedAt } from "./professionalDataStepResponseCompletedAt.js";
import type { ProfessionalDataStepResponseCompletedBy } from "./professionalDataStepResponseCompletedBy.js";
import type { ProfessionalDataStepResponseReviewedAt } from "./professionalDataStepResponseReviewedAt.js";
import type { ProfessionalDataStepResponseReviewedBy } from "./professionalDataStepResponseReviewedBy.js";
import type { ProfessionalDataStepResponseProfessionalId } from "./professionalDataStepResponseProfessionalId.js";
import type { ProfessionalDataStepResponseProfessionalVersionId } from "./professionalDataStepResponseProfessionalVersionId.js";

/**
 * Response schema for professional data step.

Includes reference to the professional record.
 */
export type ProfessionalDataStepResponse = {
  id: string;
  stepType: StepType;
  order: number;
  status: StepStatus;
  assignedTo?: ProfessionalDataStepResponseAssignedTo;
  reviewNotes?: ProfessionalDataStepResponseReviewNotes;
  rejectionReason?: ProfessionalDataStepResponseRejectionReason;
  createdAt: Date;
  updatedAt: Date;
  startedAt?: ProfessionalDataStepResponseStartedAt;
  completedAt?: ProfessionalDataStepResponseCompletedAt;
  completedBy?: ProfessionalDataStepResponseCompletedBy;
  reviewedAt?: ProfessionalDataStepResponseReviewedAt;
  reviewedBy?: ProfessionalDataStepResponseReviewedBy;
  professionalId?: ProfessionalDataStepResponseProfessionalId;
  professionalVersionId?: ProfessionalDataStepResponseProfessionalVersionId;
};
