/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalCompanyCreateLeftAt } from "./professionalCompanyCreateLeftAt.js";

/**
 * Schema for creating a professional-company link.
 */
export type ProfessionalCompanyCreate = {
  /** The company UUID */
  companyId: string;
  /** Timestamp when professional joined the company */
  joinedAt: Date;
  /** Timestamp when professional left the company */
  leftAt?: ProfessionalCompanyCreateLeftAt;
};
