/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalDocumentResponseQualificationId } from "./professionalDocumentResponseQualificationId.js";
import type { ProfessionalDocumentResponseSpecialtyId } from "./professionalDocumentResponseSpecialtyId.js";
import type { ProfessionalDocumentResponseFileSize } from "./professionalDocumentResponseFileSize.js";
import type { ProfessionalDocumentResponseMimeType } from "./professionalDocumentResponseMimeType.js";
import type { ProfessionalDocumentResponseExpiresAt } from "./professionalDocumentResponseExpiresAt.js";
import type { ProfessionalDocumentResponseNotes } from "./professionalDocumentResponseNotes.js";
import type { ProfessionalDocumentResponseDocumentTypeCode } from "./professionalDocumentResponseDocumentTypeCode.js";
import type { ProfessionalDocumentResponseDocumentTypeName } from "./professionalDocumentResponseDocumentTypeName.js";
import type { ProfessionalDocumentResponseDocumentCategory } from "./professionalDocumentResponseDocumentCategory.js";
import type { DocumentSourceType } from "./documentSourceType.js";
import type { ProfessionalDocumentResponseScreeningId } from "./professionalDocumentResponseScreeningId.js";
import type { ProfessionalDocumentResponsePromotedAt } from "./professionalDocumentResponsePromotedAt.js";
import type { ProfessionalDocumentResponsePromotedBy } from "./professionalDocumentResponsePromotedBy.js";
import type { ProfessionalDocumentResponseCreatedAt } from "./professionalDocumentResponseCreatedAt.js";
import type { ProfessionalDocumentResponseUpdatedAt } from "./professionalDocumentResponseUpdatedAt.js";

/**
 * Schema for professional document response.
 */
export type ProfessionalDocumentResponse = {
  id: string;
  organizationProfessionalId: string;
  documentTypeId: string;
  qualificationId?: ProfessionalDocumentResponseQualificationId;
  specialtyId?: ProfessionalDocumentResponseSpecialtyId;
  fileUrl: string;
  fileName: string;
  fileSize?: ProfessionalDocumentResponseFileSize;
  mimeType?: ProfessionalDocumentResponseMimeType;
  expiresAt?: ProfessionalDocumentResponseExpiresAt;
  notes?: ProfessionalDocumentResponseNotes;
  documentTypeCode?: ProfessionalDocumentResponseDocumentTypeCode;
  documentTypeName?: ProfessionalDocumentResponseDocumentTypeName;
  documentCategory?: ProfessionalDocumentResponseDocumentCategory;
  isVerified?: boolean;
  isPending?: boolean;
  sourceType?: DocumentSourceType;
  screeningId?: ProfessionalDocumentResponseScreeningId;
  promotedAt?: ProfessionalDocumentResponsePromotedAt;
  promotedBy?: ProfessionalDocumentResponsePromotedBy;
  createdAt?: ProfessionalDocumentResponseCreatedAt;
  updatedAt?: ProfessionalDocumentResponseUpdatedAt;
};
