/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalVersionResponseProfessionalId } from "./professionalVersionResponseProfessionalId";
import type { ProfessionalVersionResponseDataSnapshot } from "./professionalVersionResponseDataSnapshot";
import type { SourceType } from "./sourceType";
import type { ProfessionalVersionResponseSourceId } from "./professionalVersionResponseSourceId";
import type { ProfessionalVersionResponseAppliedAt } from "./professionalVersionResponseAppliedAt";
import type { ProfessionalVersionResponseAppliedBy } from "./professionalVersionResponseAppliedBy";
import type { ProfessionalVersionResponseRejectedAt } from "./professionalVersionResponseRejectedAt";
import type { ProfessionalVersionResponseRejectedBy } from "./professionalVersionResponseRejectedBy";
import type { ProfessionalVersionResponseRejectionReason } from "./professionalVersionResponseRejectionReason";
import type { ProfessionalVersionResponseNotes } from "./professionalVersionResponseNotes";
import type { ProfessionalVersionResponseCreatedBy } from "./professionalVersionResponseCreatedBy";
import type { ProfessionalVersionResponseUpdatedBy } from "./professionalVersionResponseUpdatedBy";

/**
 * Response schema for a professional version.
 */
export type ProfessionalVersionResponse = {
  id: string;
  organizationId: string;
  professionalId?: ProfessionalVersionResponseProfessionalId;
  versionNumber: number;
  dataSnapshot: ProfessionalVersionResponseDataSnapshot;
  isCurrent: boolean;
  sourceType: SourceType;
  sourceId?: ProfessionalVersionResponseSourceId;
  appliedAt?: ProfessionalVersionResponseAppliedAt;
  appliedBy?: ProfessionalVersionResponseAppliedBy;
  rejectedAt?: ProfessionalVersionResponseRejectedAt;
  rejectedBy?: ProfessionalVersionResponseRejectedBy;
  rejectionReason?: ProfessionalVersionResponseRejectionReason;
  notes?: ProfessionalVersionResponseNotes;
  createdAt: Date;
  updatedAt: Date;
  createdBy?: ProfessionalVersionResponseCreatedBy;
  updatedBy?: ProfessionalVersionResponseUpdatedBy;
  isApplied: boolean;
  isRejected: boolean;
  isPending: boolean;
  isFromScreening: boolean;
};
