/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalType } from "./professionalType.js";
import type { ProfessionalQualificationResponseGraduationYear } from "./professionalQualificationResponseGraduationYear.js";
import type { CouncilType } from "./councilType.js";
import type { ProfessionalQualificationResponseCreatedAt } from "./professionalQualificationResponseCreatedAt.js";
import type { ProfessionalQualificationResponseUpdatedAt } from "./professionalQualificationResponseUpdatedAt.js";

/**
 * Schema for professional qualification response.
 */
export type ProfessionalQualificationResponse = {
  id: string;
  organizationProfessionalId: string;
  organizationId: string;
  professionalType: ProfessionalType;
  isPrimary: boolean;
  graduationYear?: ProfessionalQualificationResponseGraduationYear;
  councilType: CouncilType;
  councilNumber: string;
  councilState: string;
  /** True if professional is a doctor with no specialties (clínico geral) */
  isGeneralist?: boolean;
  isVerified?: boolean;
  createdAt?: ProfessionalQualificationResponseCreatedAt;
  updatedAt?: ProfessionalQualificationResponseUpdatedAt;
};
