/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalDocumentCreateFileSize } from "./professionalDocumentCreateFileSize.js";
import type { ProfessionalDocumentCreateMimeType } from "./professionalDocumentCreateMimeType.js";
import type { ProfessionalDocumentCreateExpiresAt } from "./professionalDocumentCreateExpiresAt.js";
import type { ProfessionalDocumentCreateNotes } from "./professionalDocumentCreateNotes.js";
import type { ProfessionalDocumentCreateQualificationId } from "./professionalDocumentCreateQualificationId.js";
import type { ProfessionalDocumentCreateSpecialtyId } from "./professionalDocumentCreateSpecialtyId.js";
import type { ProfessionalDocumentCreateScreeningId } from "./professionalDocumentCreateScreeningId.js";

/**
 * Schema for creating a professional document.
 */
export type ProfessionalDocumentCreate = {
  /** Reference to the document type configuration */
  documentTypeId: string;
  /**
   * URL to the uploaded file
   * @maxLength 2048
   */
  fileUrl: string;
  /**
   * Original file name
   * @maxLength 255
   */
  fileName: string;
  /** File size in bytes */
  fileSize?: ProfessionalDocumentCreateFileSize;
  /** MIME type of the file */
  mimeType?: ProfessionalDocumentCreateMimeType;
  /** Expiration date for documents with validity */
  expiresAt?: ProfessionalDocumentCreateExpiresAt;
  /** Additional notes about this document */
  notes?: ProfessionalDocumentCreateNotes;
  /** Professional qualification ID (for QUALIFICATION category) */
  qualificationId?: ProfessionalDocumentCreateQualificationId;
  /** Professional specialty ID (for SPECIALTY category) */
  specialtyId?: ProfessionalDocumentCreateSpecialtyId;
  /** Screening process ID when document is uploaded during screening */
  screeningId?: ProfessionalDocumentCreateScreeningId;
};
