/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalSpecialtyResponseRqeNumber } from "./professionalSpecialtyResponseRqeNumber";
import type { ProfessionalSpecialtyResponseRqeState } from "./professionalSpecialtyResponseRqeState";
import type { ResidencyStatus } from "./residencyStatus";
import type { ProfessionalSpecialtyResponseResidencyInstitution } from "./professionalSpecialtyResponseResidencyInstitution";
import type { ProfessionalSpecialtyResponseResidencyExpectedCompletion } from "./professionalSpecialtyResponseResidencyExpectedCompletion";
import type { ProfessionalSpecialtyResponseCertificateUrl } from "./professionalSpecialtyResponseCertificateUrl";
import type { ProfessionalSpecialtyResponseSpecialty } from "./professionalSpecialtyResponseSpecialty";
import type { ProfessionalSpecialtyResponseCreatedAt } from "./professionalSpecialtyResponseCreatedAt";
import type { ProfessionalSpecialtyResponseUpdatedAt } from "./professionalSpecialtyResponseUpdatedAt";

/**
 * Schema for professional specialty response.
 */
export type ProfessionalSpecialtyResponse = {
  id: string;
  qualificationId: string;
  specialtyId: string;
  isPrimary: boolean;
  rqeNumber?: ProfessionalSpecialtyResponseRqeNumber;
  rqeState?: ProfessionalSpecialtyResponseRqeState;
  residencyStatus: ResidencyStatus;
  residencyInstitution?: ProfessionalSpecialtyResponseResidencyInstitution;
  residencyExpectedCompletion?: ProfessionalSpecialtyResponseResidencyExpectedCompletion;
  certificateUrl?: ProfessionalSpecialtyResponseCertificateUrl;
  specialty?: ProfessionalSpecialtyResponseSpecialty;
  isVerified?: boolean;
  createdAt?: ProfessionalSpecialtyResponseCreatedAt;
  updatedAt?: ProfessionalSpecialtyResponseUpdatedAt;
};
