/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { QualificationInputId } from "./qualificationInputId";
import type { ProfessionalType } from "./professionalType";
import type { QualificationInputGraduationYear } from "./qualificationInputGraduationYear";
import type { CouncilType } from "./councilType";
import type { QualificationInputCouncilState } from "./qualificationInputCouncilState";
import type { SpecialtyInput } from "./specialtyInput";
import type { EducationInput } from "./educationInput";

/**
 * Input schema for professional qualification with nested entities.
 */
export type QualificationInput = {
  /** Existing qualification ID */
  id?: QualificationInputId;
  /** Type of professional */
  professionalType: ProfessionalType;
  isPrimary?: boolean;
  graduationYear?: QualificationInputGraduationYear;
  /** Council type */
  councilType: CouncilType;
  /** @maxLength 50 */
  councilNumber: string;
  /**
   * Council state
   * @pattern ^[A-Z]{2}$
   */
  councilState: QualificationInputCouncilState;
  specialties?: SpecialtyInput[];
  educations?: EducationInput[];
};
