/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { QualificationNestedUpdateId } from "./qualificationNestedUpdateId";
import type { QualificationNestedUpdateProfessionalType } from "./qualificationNestedUpdateProfessionalType";
import type { QualificationNestedUpdateIsPrimary } from "./qualificationNestedUpdateIsPrimary";
import type { QualificationNestedUpdateGraduationYear } from "./qualificationNestedUpdateGraduationYear";
import type { QualificationNestedUpdateCouncilType } from "./qualificationNestedUpdateCouncilType";
import type { QualificationNestedUpdateCouncilNumber } from "./qualificationNestedUpdateCouncilNumber";
import type { QualificationNestedUpdateCouncilState } from "./qualificationNestedUpdateCouncilState";
import type { QualificationNestedUpdateSpecialties } from "./qualificationNestedUpdateSpecialties";
import type { QualificationNestedUpdateEducations } from "./qualificationNestedUpdateEducations";

/**
 * Schema for updating a qualification with nested specialties and educations.
 */
export type QualificationNestedUpdate = {
  /** Qualification ID (required for update, omit for create) */
  id?: QualificationNestedUpdateId;
  /** Type of healthcare professional (immutable for updates) */
  professionalType?: QualificationNestedUpdateProfessionalType;
  /** Whether this is the primary qualification */
  isPrimary?: QualificationNestedUpdateIsPrimary;
  /** Year of graduation */
  graduationYear?: QualificationNestedUpdateGraduationYear;
  /** Council type (immutable for updates) */
  councilType?: QualificationNestedUpdateCouncilType;
  /** Council registration number */
  councilNumber?: QualificationNestedUpdateCouncilNumber;
  /** State where the council registration is valid (e.g., SP, RJ) */
  councilState?: QualificationNestedUpdateCouncilState;
  /** Specialties for this qualification (null = no changes, [] = remove all) */
  specialties?: QualificationNestedUpdateSpecialties;
  /** Education records for this qualification (null = no changes, [] = remove all) */
  educations?: QualificationNestedUpdateEducations;
};
