/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Council state
 * @pattern ^[A-Z]{2}$
 */
export type QualificationInputCouncilState =
  (typeof QualificationInputCouncilState)[keyof typeof QualificationInputCouncilState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QualificationInputCouncilState = {
  AC: "AC",
  AL: "AL",
  AM: "AM",
  AP: "AP",
  BA: "BA",
  CE: "CE",
  DF: "DF",
  ES: "ES",
  GO: "GO",
  MA: "MA",
  MG: "MG",
  MS: "MS",
  MT: "MT",
  PA: "PA",
  PB: "PB",
  PE: "PE",
  PI: "PI",
  PR: "PR",
  RJ: "RJ",
  RN: "RN",
  RO: "RO",
  RR: "RR",
  RS: "RS",
  SC: "SC",
  SE: "SE",
  SP: "SP",
  TO: "TO",
} as const;
