/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ProfessionalType } from "./professionalType";
import type { QualificationNestedCreateGraduationYear } from "./qualificationNestedCreateGraduationYear";
import type { CouncilType } from "./councilType";
import type { QualificationNestedCreateCouncilState } from "./qualificationNestedCreateCouncilState";
import type { SpecialtyNestedCreate } from "./specialtyNestedCreate";
import type { EducationNestedCreate } from "./educationNestedCreate";

/**
 * Schema for creating a qualification with nested specialties and educations.
 */
export type QualificationNestedCreate = {
  /** Type of healthcare professional (DOCTOR, NURSE, etc.) */
  professionalType: ProfessionalType;
  /** Whether this is the primary qualification */
  isPrimary?: boolean;
  /** Year of graduation */
  graduationYear?: QualificationNestedCreateGraduationYear;
  /** Council type (CRM, COREN, etc.) */
  councilType: CouncilType;
  /**
   * Council registration number
   * @maxLength 20
   */
  councilNumber: string;
  /**
   * State where the council registration is valid (e.g., SP, RJ)
   * @pattern ^[A-Z]{2}$
   */
  councilState: QualificationNestedCreateCouncilState;
  /** Specialties for this qualification */
  specialties?: SpecialtyNestedCreate[];
  /** Education records for this qualification */
  educations?: EducationNestedCreate[];
};
