/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Summary of the primary professional qualification.
 */
export type QualificationSummary = {
  professionalType: string;
  councilType: string;
  councilNumber: string;
  councilState: string;
  /** True if professional is a doctor with no specialties (clínico geral) */
  isGeneralist?: boolean;
};
