/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Medical residency status.

Tracks the progress of a professional through their
residency/specialization program.
 */
export type ResidencyStatus =
  (typeof ResidencyStatus)[keyof typeof ResidencyStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResidencyStatus = {
  R1: "R1",
  R2: "R2",
  R3: "R3",
  R4: "R4",
  R5: "R5",
  R6: "R6",
  COMPLETED: "COMPLETED",
} as const;
