/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewDocumentRequestNotes } from "./reviewDocumentRequestNotes.js";
import type { ReviewDocumentRequestRejectionReason } from "./reviewDocumentRequestRejectionReason.js";

/**
 * Request schema for reviewing a single document.
 */
export type ReviewDocumentRequest = {
  /** True to approve, False to request correction */
  approved: boolean;
  /** Optional notes from the reviewer */
  notes?: ReviewDocumentRequestNotes;
  /** Required reason if rejecting (approved=False) */
  rejectionReason?: ReviewDocumentRequestRejectionReason;
};
