/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for rejecting via alert (risk confirmed, process rejected).
 */
export type ScreeningAlertReject = {
  /**
   * Notes explaining the rejection
   * @minLength 5
   * @maxLength 2000
   */
  rejectionNotes: string;
};
