/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for resolving an alert (no risk, process continues).
 */
export type ScreeningAlertResolve = {
  /**
   * Notes explaining the resolution
   * @minLength 5
   * @maxLength 2000
   */
  resolutionNotes: string;
};
