/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for cancelling a screening process.
 */
export type ScreeningProcessCancel = {
  /**
   * Cancellation reason (required)
   * @minLength 10
   * @maxLength 2000
   */
  reason: string;
};
