/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Status of a screening process throughout its lifecycle.

Tracks the overall macro state of the screening from creation to completion.
Detailed progress is tracked via the status of each configured step.
 */
export type ScreeningStatus =
  (typeof ScreeningStatus)[keyof typeof ScreeningStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScreeningStatus = {
  IN_PROGRESS: "IN_PROGRESS",
  PENDING_SUPERVISOR: "PENDING_SUPERVISOR",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
} as const;
