/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { AlertCategory } from "./alertCategory.js";

/**
 * Schema for creating a screening alert.
 */
export type ScreeningAlertCreate = {
  /**
   * Detailed reason for the alert
   * @minLength 10
   * @maxLength 2000
   */
  reason: string;
  /** Category of the alert */
  category: AlertCategory;
};
