/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Status of a document in the screening workflow.

Tracks the full lifecycle from requirement to approval.

Flow:
PENDING_UPLOAD → PENDING_REVIEW → APPROVED
                      │
                      └──→ CORRECTION_NEEDED → PENDING_REVIEW (after re-upload)

Special states:
- REUSED: Document reused from a previous screening
- SKIPPED: Optional document explicitly skipped
 */
export type ScreeningDocumentStatus =
  (typeof ScreeningDocumentStatus)[keyof typeof ScreeningDocumentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScreeningDocumentStatus = {
  PENDING_UPLOAD: "PENDING_UPLOAD",
  PENDING_REVIEW: "PENDING_REVIEW",
  APPROVED: "APPROVED",
  CORRECTION_NEEDED: "CORRECTION_NEEDED",
  REUSED: "REUSED",
  SKIPPED: "SKIPPED",
} as const;
