/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { StepType } from "./stepType";
import type { StepStatus } from "./stepStatus";
import type { ScreeningProcessStepResponseAssignedTo } from "./screeningProcessStepResponseAssignedTo";
import type { ScreeningProcessStepResponseDataReferences } from "./screeningProcessStepResponseDataReferences";
import type { ScreeningProcessStepResponseConversationNotes } from "./screeningProcessStepResponseConversationNotes";
import type { ScreeningProcessStepResponseConversationOutcome } from "./screeningProcessStepResponseConversationOutcome";
import type { ScreeningProcessStepResponseReviewNotes } from "./screeningProcessStepResponseReviewNotes";
import type { ScreeningProcessStepResponseRejectionReason } from "./screeningProcessStepResponseRejectionReason";
import type { ScreeningProcessStepResponseClientValidationOutcome } from "./screeningProcessStepResponseClientValidationOutcome";
import type { ScreeningProcessStepResponseClientValidationNotes } from "./screeningProcessStepResponseClientValidationNotes";
import type { ScreeningProcessStepResponseClientValidatedBy } from "./screeningProcessStepResponseClientValidatedBy";
import type { ScreeningProcessStepResponseClientValidatedAt } from "./screeningProcessStepResponseClientValidatedAt";
import type { ScreeningProcessStepResponseStartedAt } from "./screeningProcessStepResponseStartedAt";
import type { ScreeningProcessStepResponseSubmittedAt } from "./screeningProcessStepResponseSubmittedAt";
import type { ScreeningProcessStepResponseSubmittedBy } from "./screeningProcessStepResponseSubmittedBy";
import type { ScreeningProcessStepResponseReviewedAt } from "./screeningProcessStepResponseReviewedAt";
import type { ScreeningProcessStepResponseReviewedBy } from "./screeningProcessStepResponseReviewedBy";

/**
 * Schema for screening process step response.
 */
export type ScreeningProcessStepResponse = {
  id: string;
  processId: string;
  stepType: StepType;
  order: number;
  isRequired: boolean;
  status: StepStatus;
  assignedTo: ScreeningProcessStepResponseAssignedTo;
  dataReferences: ScreeningProcessStepResponseDataReferences;
  conversationNotes: ScreeningProcessStepResponseConversationNotes;
  conversationOutcome: ScreeningProcessStepResponseConversationOutcome;
  reviewNotes: ScreeningProcessStepResponseReviewNotes;
  rejectionReason: ScreeningProcessStepResponseRejectionReason;
  clientValidationOutcome: ScreeningProcessStepResponseClientValidationOutcome;
  clientValidationNotes: ScreeningProcessStepResponseClientValidationNotes;
  clientValidatedBy: ScreeningProcessStepResponseClientValidatedBy;
  clientValidatedAt: ScreeningProcessStepResponseClientValidatedAt;
  startedAt: ScreeningProcessStepResponseStartedAt;
  submittedAt: ScreeningProcessStepResponseSubmittedAt;
  submittedBy: ScreeningProcessStepResponseSubmittedBy;
  reviewedAt: ScreeningProcessStepResponseReviewedAt;
  reviewedBy: ScreeningProcessStepResponseReviewedBy;
  createdAt: Date;
  updatedAt: Date;
};
