/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ScreeningDocumentSummaryDocumentTypeName } from "./screeningDocumentSummaryDocumentTypeName.js";
import type { ScreeningDocumentSummaryUploadedAt } from "./screeningDocumentSummaryUploadedAt.js";

/**
 * Summary of a document in the upload step response.
 */
export type ScreeningDocumentSummary = {
  id: string;
  documentTypeId: string;
  documentTypeName?: ScreeningDocumentSummaryDocumentTypeName;
  isRequired: boolean;
  order: number;
  status: string;
  isUploaded: boolean;
  uploadedAt?: ScreeningDocumentSummaryUploadedAt;
};
