/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { StepType } from "./stepType.js";
import type { StepStatus } from "./stepStatus.js";
import type { ScreeningProcessStepResponseAssignedTo } from "./screeningProcessStepResponseAssignedTo.js";
import type { ScreeningProcessStepResponseDataReferences } from "./screeningProcessStepResponseDataReferences.js";
import type { ScreeningProcessStepResponseConversationNotes } from "./screeningProcessStepResponseConversationNotes.js";
import type { ScreeningProcessStepResponseConversationOutcome } from "./screeningProcessStepResponseConversationOutcome.js";
import type { ScreeningProcessStepResponseReviewNotes } from "./screeningProcessStepResponseReviewNotes.js";
import type { ScreeningProcessStepResponseRejectionReason } from "./screeningProcessStepResponseRejectionReason.js";
import type { ScreeningProcessStepResponseClientValidationOutcome } from "./screeningProcessStepResponseClientValidationOutcome.js";
import type { ScreeningProcessStepResponseClientValidationNotes } from "./screeningProcessStepResponseClientValidationNotes.js";
import type { ScreeningProcessStepResponseClientValidatedBy } from "./screeningProcessStepResponseClientValidatedBy.js";
import type { ScreeningProcessStepResponseClientValidatedAt } from "./screeningProcessStepResponseClientValidatedAt.js";
import type { ScreeningProcessStepResponseStartedAt } from "./screeningProcessStepResponseStartedAt.js";
import type { ScreeningProcessStepResponseSubmittedAt } from "./screeningProcessStepResponseSubmittedAt.js";
import type { ScreeningProcessStepResponseSubmittedBy } from "./screeningProcessStepResponseSubmittedBy.js";
import type { ScreeningProcessStepResponseReviewedAt } from "./screeningProcessStepResponseReviewedAt.js";
import type { ScreeningProcessStepResponseReviewedBy } from "./screeningProcessStepResponseReviewedBy.js";

/**
 * Schema for screening process step response.
 */
export type ScreeningProcessStepResponse = {
  id: string;
  processId: string;
  stepType: StepType;
  order: number;
  isRequired: boolean;
  status: StepStatus;
  assignedTo: ScreeningProcessStepResponseAssignedTo;
  dataReferences: ScreeningProcessStepResponseDataReferences;
  conversationNotes: ScreeningProcessStepResponseConversationNotes;
  conversationOutcome: ScreeningProcessStepResponseConversationOutcome;
  reviewNotes: ScreeningProcessStepResponseReviewNotes;
  rejectionReason: ScreeningProcessStepResponseRejectionReason;
  clientValidationOutcome: ScreeningProcessStepResponseClientValidationOutcome;
  clientValidationNotes: ScreeningProcessStepResponseClientValidationNotes;
  clientValidatedBy: ScreeningProcessStepResponseClientValidatedBy;
  clientValidatedAt: ScreeningProcessStepResponseClientValidatedAt;
  startedAt: ScreeningProcessStepResponseStartedAt;
  submittedAt: ScreeningProcessStepResponseSubmittedAt;
  submittedBy: ScreeningProcessStepResponseSubmittedBy;
  reviewedAt: ScreeningProcessStepResponseReviewedAt;
  reviewedBy: ScreeningProcessStepResponseReviewedBy;
  createdAt: Date;
  updatedAt: Date;
};
