/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ScreeningStatus } from "./screeningStatus";
import type { ScreeningProcessDetailResponseProfessionalCpf } from "./screeningProcessDetailResponseProfessionalCpf";
import type { ScreeningProcessDetailResponseProfessionalName } from "./screeningProcessDetailResponseProfessionalName";
import type { ScreeningProcessDetailResponseProfessionalPhone } from "./screeningProcessDetailResponseProfessionalPhone";
import type { ScreeningProcessDetailResponseProfessionalEmail } from "./screeningProcessDetailResponseProfessionalEmail";
import type { ScreeningProcessDetailResponseOrganizationProfessionalId } from "./screeningProcessDetailResponseOrganizationProfessionalId";
import type { ScreeningProcessDetailResponseExpectedProfessionalType } from "./screeningProcessDetailResponseExpectedProfessionalType";
import type { ScreeningProcessDetailResponseExpectedSpecialtyId } from "./screeningProcessDetailResponseExpectedSpecialtyId";
import type { ScreeningProcessDetailResponseOwnerId } from "./screeningProcessDetailResponseOwnerId";
import type { ScreeningProcessDetailResponseCurrentActorId } from "./screeningProcessDetailResponseCurrentActorId";
import type { ScreeningProcessDetailResponseClientCompanyId } from "./screeningProcessDetailResponseClientCompanyId";
import type { ScreeningProcessDetailResponseProfessionalContractId } from "./screeningProcessDetailResponseProfessionalContractId";
import type { ScreeningProcessDetailResponseClientContractId } from "./screeningProcessDetailResponseClientContractId";
import type { ScreeningProcessDetailResponseCurrentStepType } from "./screeningProcessDetailResponseCurrentStepType";
import type { ScreeningProcessDetailResponseRejectionReason } from "./screeningProcessDetailResponseRejectionReason";
import type { ScreeningProcessDetailResponseNotes } from "./screeningProcessDetailResponseNotes";
import type { ScreeningProcessDetailResponseExpiresAt } from "./screeningProcessDetailResponseExpiresAt";
import type { ScreeningProcessDetailResponseCompletedAt } from "./screeningProcessDetailResponseCompletedAt";
import type { ScreeningProcessDetailResponseCreatedBy } from "./screeningProcessDetailResponseCreatedBy";
import type { ScreeningProcessDetailResponseUpdatedBy } from "./screeningProcessDetailResponseUpdatedBy";
import type { ScreeningProcessDetailResponseSteps } from "./screeningProcessDetailResponseSteps";
import type { ScreeningProcessDetailResponseRequiredDocuments } from "./screeningProcessDetailResponseRequiredDocuments";

/**
 * Schema for detailed screening process response with nested data.
 */
export type ScreeningProcessDetailResponse = {
  id: string;
  organizationId: string;
  status: ScreeningStatus;
  professionalCpf: ScreeningProcessDetailResponseProfessionalCpf;
  professionalName: ScreeningProcessDetailResponseProfessionalName;
  professionalPhone: ScreeningProcessDetailResponseProfessionalPhone;
  professionalEmail: ScreeningProcessDetailResponseProfessionalEmail;
  organizationProfessionalId: ScreeningProcessDetailResponseOrganizationProfessionalId;
  expectedProfessionalType: ScreeningProcessDetailResponseExpectedProfessionalType;
  expectedSpecialtyId: ScreeningProcessDetailResponseExpectedSpecialtyId;
  ownerId: ScreeningProcessDetailResponseOwnerId;
  currentActorId: ScreeningProcessDetailResponseCurrentActorId;
  clientCompanyId: ScreeningProcessDetailResponseClientCompanyId;
  professionalContractId: ScreeningProcessDetailResponseProfessionalContractId;
  clientContractId: ScreeningProcessDetailResponseClientContractId;
  currentStepType: ScreeningProcessDetailResponseCurrentStepType;
  rejectionReason: ScreeningProcessDetailResponseRejectionReason;
  notes: ScreeningProcessDetailResponseNotes;
  createdAt: Date;
  updatedAt: Date;
  expiresAt: ScreeningProcessDetailResponseExpiresAt;
  completedAt: ScreeningProcessDetailResponseCompletedAt;
  createdBy: ScreeningProcessDetailResponseCreatedBy;
  updatedBy: ScreeningProcessDetailResponseUpdatedBy;
  steps?: ScreeningProcessDetailResponseSteps;
  requiredDocuments?: ScreeningProcessDetailResponseRequiredDocuments;
};
