/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ScreeningProcessCreateProfessionalEmail } from "./screeningProcessCreateProfessionalEmail";
import type { ScreeningProcessCreateExpectedSpecialtyId } from "./screeningProcessCreateExpectedSpecialtyId";
import type { ScreeningProcessCreateOwnerId } from "./screeningProcessCreateOwnerId";
import type { ScreeningProcessCreateClientCompanyId } from "./screeningProcessCreateClientCompanyId";
import type { ScreeningProcessCreateNotes } from "./screeningProcessCreateNotes";

/**
 * Schema for creating a screening process (Step 1 - Conversation).

This creates the screening with initial professional data collected
during the first phone call (conversation step).
 */
export type ScreeningProcessCreate = {
  /**
   * Professional's CPF (11 digits)
   * @pattern ^[0-9]{11}$
   */
  professionalCpf: string;
  /**
   * Professional's full name
   * @maxLength 255
   */
  professionalName: string;
  /**
   * Professional's phone number
   * @pattern ^\+[1-9]\d{1,14}$
   */
  professionalPhone: string;
  /** Professional's email (optional) */
  professionalEmail?: ScreeningProcessCreateProfessionalEmail;
  /**
   * Expected professional type (DOCTOR, NURSE, etc.)
   * @maxLength 50
   */
  expectedProfessionalType: string;
  /** Expected specialty ID (for doctors) */
  expectedSpecialtyId?: ScreeningProcessCreateExpectedSpecialtyId;
  /** User responsible for this screening (owner) */
  ownerId?: ScreeningProcessCreateOwnerId;
  /** Client company (empresa contratante) */
  clientCompanyId?: ScreeningProcessCreateClientCompanyId;
  /** Include payment info step (bank account + company data) */
  includePaymentInfo?: boolean;
  /** Include supervisor review step (escalated review) */
  includeSupervisorReview?: boolean;
  /** Include client validation step (client approval). Automatically set to True if client_company_id is provided. */
  includeClientValidation?: boolean;
  /** Notes from the initial conversation */
  notes?: ScreeningProcessCreateNotes;
};
