/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ScreeningStatus } from "./screeningStatus.js";
import type { ScreeningProcessResponseProfessionalCpf } from "./screeningProcessResponseProfessionalCpf.js";
import type { ScreeningProcessResponseProfessionalName } from "./screeningProcessResponseProfessionalName.js";
import type { ScreeningProcessResponseProfessionalPhone } from "./screeningProcessResponseProfessionalPhone.js";
import type { ScreeningProcessResponseProfessionalEmail } from "./screeningProcessResponseProfessionalEmail.js";
import type { ScreeningProcessResponseOrganizationProfessionalId } from "./screeningProcessResponseOrganizationProfessionalId.js";
import type { ScreeningProcessResponseExpectedProfessionalType } from "./screeningProcessResponseExpectedProfessionalType.js";
import type { ScreeningProcessResponseExpectedSpecialtyId } from "./screeningProcessResponseExpectedSpecialtyId.js";
import type { ScreeningProcessResponseOwnerId } from "./screeningProcessResponseOwnerId.js";
import type { ScreeningProcessResponseCurrentActorId } from "./screeningProcessResponseCurrentActorId.js";
import type { ScreeningProcessResponseClientCompanyId } from "./screeningProcessResponseClientCompanyId.js";
import type { ScreeningProcessResponseProfessionalContractId } from "./screeningProcessResponseProfessionalContractId.js";
import type { ScreeningProcessResponseClientContractId } from "./screeningProcessResponseClientContractId.js";
import type { ScreeningProcessResponseCurrentStepType } from "./screeningProcessResponseCurrentStepType.js";
import type { ScreeningProcessResponseRejectionReason } from "./screeningProcessResponseRejectionReason.js";
import type { ScreeningProcessResponseNotes } from "./screeningProcessResponseNotes.js";
import type { ScreeningProcessResponseExpiresAt } from "./screeningProcessResponseExpiresAt.js";
import type { ScreeningProcessResponseCompletedAt } from "./screeningProcessResponseCompletedAt.js";
import type { ScreeningProcessResponseCreatedBy } from "./screeningProcessResponseCreatedBy.js";
import type { ScreeningProcessResponseUpdatedBy } from "./screeningProcessResponseUpdatedBy.js";

/**
 * Schema for full screening process response.
 */
export type ScreeningProcessResponse = {
  id: string;
  organizationId: string;
  status: ScreeningStatus;
  professionalCpf: ScreeningProcessResponseProfessionalCpf;
  professionalName: ScreeningProcessResponseProfessionalName;
  professionalPhone: ScreeningProcessResponseProfessionalPhone;
  professionalEmail: ScreeningProcessResponseProfessionalEmail;
  organizationProfessionalId: ScreeningProcessResponseOrganizationProfessionalId;
  expectedProfessionalType: ScreeningProcessResponseExpectedProfessionalType;
  expectedSpecialtyId: ScreeningProcessResponseExpectedSpecialtyId;
  ownerId: ScreeningProcessResponseOwnerId;
  currentActorId: ScreeningProcessResponseCurrentActorId;
  clientCompanyId: ScreeningProcessResponseClientCompanyId;
  professionalContractId: ScreeningProcessResponseProfessionalContractId;
  clientContractId: ScreeningProcessResponseClientContractId;
  currentStepType: ScreeningProcessResponseCurrentStepType;
  rejectionReason: ScreeningProcessResponseRejectionReason;
  notes: ScreeningProcessResponseNotes;
  createdAt: Date;
  updatedAt: Date;
  expiresAt: ScreeningProcessResponseExpiresAt;
  completedAt: ScreeningProcessResponseCompletedAt;
  createdBy: ScreeningProcessResponseCreatedBy;
  updatedBy: ScreeningProcessResponseUpdatedBy;
};
