/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ScreeningStatus } from "./screeningStatus.js";
import type { ScreeningProcessDetailResponseProfessionalCpf } from "./screeningProcessDetailResponseProfessionalCpf.js";
import type { ScreeningProcessDetailResponseProfessionalName } from "./screeningProcessDetailResponseProfessionalName.js";
import type { ScreeningProcessDetailResponseProfessionalPhone } from "./screeningProcessDetailResponseProfessionalPhone.js";
import type { ScreeningProcessDetailResponseProfessionalEmail } from "./screeningProcessDetailResponseProfessionalEmail.js";
import type { ScreeningProcessDetailResponseOrganizationProfessionalId } from "./screeningProcessDetailResponseOrganizationProfessionalId.js";
import type { ScreeningProcessDetailResponseExpectedProfessionalType } from "./screeningProcessDetailResponseExpectedProfessionalType.js";
import type { ScreeningProcessDetailResponseExpectedSpecialtyId } from "./screeningProcessDetailResponseExpectedSpecialtyId.js";
import type { ScreeningProcessDetailResponseOwnerId } from "./screeningProcessDetailResponseOwnerId.js";
import type { ScreeningProcessDetailResponseCurrentActorId } from "./screeningProcessDetailResponseCurrentActorId.js";
import type { ScreeningProcessDetailResponseClientCompanyId } from "./screeningProcessDetailResponseClientCompanyId.js";
import type { ScreeningProcessDetailResponseProfessionalContractId } from "./screeningProcessDetailResponseProfessionalContractId.js";
import type { ScreeningProcessDetailResponseClientContractId } from "./screeningProcessDetailResponseClientContractId.js";
import type { ScreeningProcessDetailResponseCurrentStepType } from "./screeningProcessDetailResponseCurrentStepType.js";
import type { ScreeningProcessDetailResponseRejectionReason } from "./screeningProcessDetailResponseRejectionReason.js";
import type { ScreeningProcessDetailResponseNotes } from "./screeningProcessDetailResponseNotes.js";
import type { ScreeningProcessDetailResponseExpiresAt } from "./screeningProcessDetailResponseExpiresAt.js";
import type { ScreeningProcessDetailResponseCompletedAt } from "./screeningProcessDetailResponseCompletedAt.js";
import type { ScreeningProcessDetailResponseCreatedBy } from "./screeningProcessDetailResponseCreatedBy.js";
import type { ScreeningProcessDetailResponseUpdatedBy } from "./screeningProcessDetailResponseUpdatedBy.js";
import type { ScreeningProcessDetailResponseSteps } from "./screeningProcessDetailResponseSteps.js";
import type { ScreeningProcessDetailResponseRequiredDocuments } from "./screeningProcessDetailResponseRequiredDocuments.js";

/**
 * Schema for detailed screening process response with nested data.
 */
export type ScreeningProcessDetailResponse = {
  id: string;
  organizationId: string;
  status: ScreeningStatus;
  professionalCpf: ScreeningProcessDetailResponseProfessionalCpf;
  professionalName: ScreeningProcessDetailResponseProfessionalName;
  professionalPhone: ScreeningProcessDetailResponseProfessionalPhone;
  professionalEmail: ScreeningProcessDetailResponseProfessionalEmail;
  organizationProfessionalId: ScreeningProcessDetailResponseOrganizationProfessionalId;
  expectedProfessionalType: ScreeningProcessDetailResponseExpectedProfessionalType;
  expectedSpecialtyId: ScreeningProcessDetailResponseExpectedSpecialtyId;
  ownerId: ScreeningProcessDetailResponseOwnerId;
  currentActorId: ScreeningProcessDetailResponseCurrentActorId;
  clientCompanyId: ScreeningProcessDetailResponseClientCompanyId;
  professionalContractId: ScreeningProcessDetailResponseProfessionalContractId;
  clientContractId: ScreeningProcessDetailResponseClientContractId;
  currentStepType: ScreeningProcessDetailResponseCurrentStepType;
  rejectionReason: ScreeningProcessDetailResponseRejectionReason;
  notes: ScreeningProcessDetailResponseNotes;
  createdAt: Date;
  updatedAt: Date;
  expiresAt: ScreeningProcessDetailResponseExpiresAt;
  completedAt: ScreeningProcessDetailResponseCompletedAt;
  createdBy: ScreeningProcessDetailResponseCreatedBy;
  updatedBy: ScreeningProcessDetailResponseUpdatedBy;
  steps?: ScreeningProcessDetailResponseSteps;
  requiredDocuments?: ScreeningProcessDetailResponseRequiredDocuments;
};
