/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { AlertCategory } from "./alertCategory.js";
import type { AlertNote } from "./alertNote.js";
import type { ScreeningAlertResponseResolvedAt } from "./screeningAlertResponseResolvedAt.js";
import type { ScreeningAlertResponseResolvedBy } from "./screeningAlertResponseResolvedBy.js";

/**
 * Response schema for a screening alert.
 */
export type ScreeningAlertResponse = {
  id: string;
  processId: string;
  reason: string;
  category: AlertCategory;
  notes: AlertNote[];
  isResolved: boolean;
  resolvedAt?: ScreeningAlertResponseResolvedAt;
  resolvedBy?: ScreeningAlertResponseResolvedBy;
  createdAt: Date;
  createdBy: string;
  updatedAt: Date;
};
