/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ScreeningStatus } from "./screeningStatus.js";
import type { StepTypeInfo } from "./stepTypeInfo.js";
import type { ScreeningProcessListResponseProfessionalCpf } from "./screeningProcessListResponseProfessionalCpf.js";
import type { ScreeningProcessListResponseProfessionalName } from "./screeningProcessListResponseProfessionalName.js";
import type { ScreeningProcessListResponseProfessionalPhone } from "./screeningProcessListResponseProfessionalPhone.js";
import type { ScreeningProcessListResponseProfessionalEmail } from "./screeningProcessListResponseProfessionalEmail.js";
import type { ScreeningProcessListResponseExpectedProfessionalType } from "./screeningProcessListResponseExpectedProfessionalType.js";
import type { ScreeningProcessListResponseOwnerId } from "./screeningProcessListResponseOwnerId.js";
import type { ScreeningProcessListResponseCurrentActorId } from "./screeningProcessListResponseCurrentActorId.js";
import type { ScreeningProcessListResponseOrganizationProfessionalId } from "./screeningProcessListResponseOrganizationProfessionalId.js";
import type { ScreeningProcessListResponseClientCompanyId } from "./screeningProcessListResponseClientCompanyId.js";
import type { ScreeningProcessListResponseExpiresAt } from "./screeningProcessListResponseExpiresAt.js";

/**
 * Schema for screening process list (minimal fields, no relationships).
 */
export type ScreeningProcessListResponse = {
  id: string;
  status: ScreeningStatus;
  currentStepType: StepTypeInfo;
  configuredStepTypes: StepTypeInfo[];
  professionalCpf: ScreeningProcessListResponseProfessionalCpf;
  professionalName: ScreeningProcessListResponseProfessionalName;
  professionalPhone: ScreeningProcessListResponseProfessionalPhone;
  professionalEmail: ScreeningProcessListResponseProfessionalEmail;
  expectedProfessionalType: ScreeningProcessListResponseExpectedProfessionalType;
  ownerId: ScreeningProcessListResponseOwnerId;
  currentActorId: ScreeningProcessListResponseCurrentActorId;
  supervisorId: string;
  organizationProfessionalId: ScreeningProcessListResponseOrganizationProfessionalId;
  clientCompanyId: ScreeningProcessListResponseClientCompanyId;
  createdAt: Date;
  updatedAt: Date;
  expiresAt: ScreeningProcessListResponseExpiresAt;
};
