/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { ScreeningDocumentResponseDescription } from "./screeningDocumentResponseDescription.js";
import type { ScreeningDocumentStatus } from "./screeningDocumentStatus.js";
import type { ScreeningDocumentResponseProfessionalDocumentId } from "./screeningDocumentResponseProfessionalDocumentId.js";
import type { ScreeningDocumentResponseUploadedAt } from "./screeningDocumentResponseUploadedAt.js";
import type { ScreeningDocumentResponseUploadedBy } from "./screeningDocumentResponseUploadedBy.js";
import type { ScreeningDocumentResponseReviewNotes } from "./screeningDocumentResponseReviewNotes.js";
import type { ScreeningDocumentResponseRejectionReason } from "./screeningDocumentResponseRejectionReason.js";
import type { ScreeningDocumentResponseReviewedAt } from "./screeningDocumentResponseReviewedAt.js";
import type { ScreeningDocumentResponseReviewedBy } from "./screeningDocumentResponseReviewedBy.js";
import type { ScreeningDocumentResponseReviewHistoryItem } from "./screeningDocumentResponseReviewHistoryItem.js";
import type { ScreeningDocumentResponseCreatedBy } from "./screeningDocumentResponseCreatedBy.js";
import type { ScreeningDocumentResponseUpdatedBy } from "./screeningDocumentResponseUpdatedBy.js";

/**
 * Full response schema for a screening document.
 */
export type ScreeningDocumentResponse = {
  id: string;
  uploadStepId: string;
  documentTypeId: string;
  isRequired: boolean;
  order: number;
  description?: ScreeningDocumentResponseDescription;
  status: ScreeningDocumentStatus;
  professionalDocumentId?: ScreeningDocumentResponseProfessionalDocumentId;
  uploadedAt?: ScreeningDocumentResponseUploadedAt;
  uploadedBy?: ScreeningDocumentResponseUploadedBy;
  reviewNotes?: ScreeningDocumentResponseReviewNotes;
  rejectionReason?: ScreeningDocumentResponseRejectionReason;
  reviewedAt?: ScreeningDocumentResponseReviewedAt;
  reviewedBy?: ScreeningDocumentResponseReviewedBy;
  reviewHistory?: ScreeningDocumentResponseReviewHistoryItem[];
  createdAt: Date;
  updatedAt: Date;
  createdBy?: ScreeningDocumentResponseCreatedBy;
  updatedBy?: ScreeningDocumentResponseUpdatedBy;
  isUploaded?: boolean;
  isReviewed?: boolean;
  isApproved?: boolean;
  needsUpload?: boolean;
  needsReview?: boolean;
  needsCorrection?: boolean;
  isComplete?: boolean;
};
