/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

export type SearchSpecialtiesApiV1SpecialtiesSearchGetParams = {
  /**
   * Search query (min 2 characters)
   * @minLength 2
   */
  q: string;
  page?: number | null;
  pageSize?: number | null;
  /**
 * List of fields to sort by (format: field:asc or field:desc).

**Available fields**
- `id`: ID (UUID v7 is time-ordered)
- `code`: Specialty code
- `name`: Specialty name

**Default:** name:asc
 */
  sortBy?: string[] | null;
};
