/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Source of a professional version change.

Tracks how/where the change originated for audit purposes.
 */
export type SourceType = (typeof SourceType)[keyof typeof SourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SourceType = {
  DIRECT: "DIRECT",
  SCREENING: "SCREENING",
  IMPORT: "IMPORT",
  API: "API",
} as const;
