/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { SpecialtyResponseDescription } from "./specialtyResponseDescription";
import type { SpecialtyResponseCreatedAt } from "./specialtyResponseCreatedAt";
import type { SpecialtyResponseUpdatedAt } from "./specialtyResponseUpdatedAt";

/**
 * Schema for specialty response.
 */
export type SpecialtyResponse = {
  id: string;
  code: string;
  name: string;
  description?: SpecialtyResponseDescription;
  createdAt?: SpecialtyResponseCreatedAt;
  updatedAt?: SpecialtyResponseUpdatedAt;
};
