/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { SpecialtyNestedUpdateId } from "./specialtyNestedUpdateId";
import type { SpecialtyNestedUpdateSpecialtyId } from "./specialtyNestedUpdateSpecialtyId";
import type { SpecialtyNestedUpdateIsPrimary } from "./specialtyNestedUpdateIsPrimary";
import type { SpecialtyNestedUpdateRqeNumber } from "./specialtyNestedUpdateRqeNumber";
import type { SpecialtyNestedUpdateRqeState } from "./specialtyNestedUpdateRqeState";
import type { SpecialtyNestedUpdateResidencyStatus } from "./specialtyNestedUpdateResidencyStatus";
import type { SpecialtyNestedUpdateResidencyInstitution } from "./specialtyNestedUpdateResidencyInstitution";
import type { SpecialtyNestedUpdateResidencyExpectedCompletion } from "./specialtyNestedUpdateResidencyExpectedCompletion";
import type { SpecialtyNestedUpdateCertificateUrl } from "./specialtyNestedUpdateCertificateUrl";

/**
 * Schema for updating a specialty within a composite operation.
 */
export type SpecialtyNestedUpdate = {
  /** Specialty ID (required for update, omit for create, send only ID to keep unchanged) */
  id?: SpecialtyNestedUpdateId;
  /** The specialty UUID (required for create) */
  specialtyId?: SpecialtyNestedUpdateSpecialtyId;
  /** Whether this is the primary specialty */
  isPrimary?: SpecialtyNestedUpdateIsPrimary;
  /** RQE number (for doctors) */
  rqeNumber?: SpecialtyNestedUpdateRqeNumber;
  /** State where RQE is registered (e.g., SP, RJ) */
  rqeState?: SpecialtyNestedUpdateRqeState;
  /** Current residency/training status */
  residencyStatus?: SpecialtyNestedUpdateResidencyStatus;
  /** Institution where residency is being done */
  residencyInstitution?: SpecialtyNestedUpdateResidencyInstitution;
  /** Expected residency completion date (YYYY-MM-DD) */
  residencyExpectedCompletion?: SpecialtyNestedUpdateResidencyExpectedCompletion;
  /** URL to specialty certificate */
  certificateUrl?: SpecialtyNestedUpdateCertificateUrl;
};
