/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { SpecialtyNestedCreateRqeNumber } from "./specialtyNestedCreateRqeNumber.js";
import type { SpecialtyNestedCreateRqeState } from "./specialtyNestedCreateRqeState.js";
import type { ResidencyStatus } from "./residencyStatus.js";
import type { SpecialtyNestedCreateResidencyInstitution } from "./specialtyNestedCreateResidencyInstitution.js";
import type { SpecialtyNestedCreateResidencyExpectedCompletion } from "./specialtyNestedCreateResidencyExpectedCompletion.js";
import type { SpecialtyNestedCreateCertificateUrl } from "./specialtyNestedCreateCertificateUrl.js";

/**
 * Schema for creating a specialty within a composite operation.
 */
export type SpecialtyNestedCreate = {
  /** The specialty UUID (must exist in global specialties table) */
  specialtyId: string;
  /** Whether this is the primary specialty */
  isPrimary?: boolean;
  /** RQE number (for doctors) */
  rqeNumber?: SpecialtyNestedCreateRqeNumber;
  /** State where RQE is registered (e.g., SP, RJ) */
  rqeState?: SpecialtyNestedCreateRqeState;
  /** Current residency/training status */
  residencyStatus?: ResidencyStatus;
  /** Institution where residency is being done */
  residencyInstitution?: SpecialtyNestedCreateResidencyInstitution;
  /** Expected residency completion date (YYYY-MM-DD) */
  residencyExpectedCompletion?: SpecialtyNestedCreateResidencyExpectedCompletion;
  /** URL to specialty certificate */
  certificateUrl?: SpecialtyNestedCreateCertificateUrl;
};
