/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * RQE number (for doctors)
 */
export type SpecialtyNestedCreateRqeNumber = string | null;
