/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { StepType } from "./stepType.js";
import type { StepStatus } from "./stepStatus.js";

/**
 * Minimal schema for step summary in process detail.

Used to show a list of steps without full details.
Ordered by 'order' field.
 */
export type StepSummaryResponse = {
  id: string;
  stepType: StepType;
  order: number;
  status: StepStatus;
  /** Whether this is the current active step */
  isCurrent?: boolean;
};
