/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Status of an individual screening step.

Tracks the progress of a single step within the screening process.
 */
export type StepStatus = (typeof StepStatus)[keyof typeof StepStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StepStatus = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SKIPPED: "SKIPPED",
  CANCELLED: "CANCELLED",
  CORRECTION_NEEDED: "CORRECTION_NEEDED",
} as const;
