/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for uploading a document.

The actual file is uploaded directly to Firebase by the frontend.
This endpoint registers the uploaded file in the screening workflow.
 */
export type UploadDocumentRequest = {
  /** ID of the ProfessionalDocument created after Firebase upload */
  professionalDocumentId: string;
};
