/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { UserMeResponsePhone } from "./userMeResponsePhone.js";
import type { UserMeResponseCpf } from "./userMeResponseCpf.js";
import type { UserMeResponseAvatarUrl } from "./userMeResponseAvatarUrl.js";
import type { UserMeResponseEmailVerifiedAt } from "./userMeResponseEmailVerifiedAt.js";
import type { RoleInfo } from "./roleInfo.js";
import type { PermissionInfo } from "./permissionInfo.js";
import type { OrganizationMembershipInfo } from "./organizationMembershipInfo.js";

/**
 * Response schema for GET /auth/me endpoint.
 */
export type UserMeResponse = {
  id: string;
  email: string;
  fullName: string;
  phone?: UserMeResponsePhone;
  cpf?: UserMeResponseCpf;
  avatarUrl?: UserMeResponseAvatarUrl;
  isActive: boolean;
  emailVerifiedAt?: UserMeResponseEmailVerifiedAt;
  createdAt: Date;
  updatedAt: Date;
  roles?: RoleInfo[];
  permissions?: PermissionInfo[];
  organizations?: OrganizationMembershipInfo[];
};
