/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { UserMeUpdateFullName } from "./userMeUpdateFullName.js";
import type { UserMeUpdatePhone } from "./userMeUpdatePhone.js";
import type { UserMeUpdateCpf } from "./userMeUpdateCpf.js";
import type { UserMeUpdateAvatarUrl } from "./userMeUpdateAvatarUrl.js";

/**
 * Schema for updating current user's profile (PATCH - partial update).

Email is not editable through this endpoint as it requires Firebase sync.
 */
export type UserMeUpdate = {
  fullName?: UserMeUpdateFullName;
  phone?: UserMeUpdatePhone;
  cpf?: UserMeUpdateCpf;
  avatarUrl?: UserMeUpdateAvatarUrl;
};
