/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Quero Plantão API
 * REST API para gestão de plantões médicos
 * OpenAPI spec version: 0.1.0
 */
import type { UserMeResponsePhone } from "./userMeResponsePhone";
import type { UserMeResponseCpf } from "./userMeResponseCpf";
import type { UserMeResponseAvatarUrl } from "./userMeResponseAvatarUrl";
import type { UserMeResponseEmailVerifiedAt } from "./userMeResponseEmailVerifiedAt";
import type { SrcModulesUsersDomainSchemasUserRoleInfo } from "./srcModulesUsersDomainSchemasUserRoleInfo";
import type { PermissionInfo } from "./permissionInfo";
import type { OrganizationMembershipInfo } from "./organizationMembershipInfo";

/**
 * Response schema for GET /auth/me endpoint.
 */
export type UserMeResponse = {
  id: string;
  email: string;
  fullName: string;
  phone?: UserMeResponsePhone;
  cpf?: UserMeResponseCpf;
  avatarUrl?: UserMeResponseAvatarUrl;
  isActive: boolean;
  emailVerifiedAt?: UserMeResponseEmailVerifiedAt;
  createdAt: Date;
  updatedAt: Date;
  roles?: SrcModulesUsersDomainSchemasUserRoleInfo[];
  permissions?: PermissionInfo[];
  organizations?: OrganizationMembershipInfo[];
};
