"""Error code constants for the application."""

from enum import StrEnum


class AuthErrorCodes(StrEnum):
    """Authentication and authorization error codes."""

    # Token errors
    MISSING_TOKEN = "AUTH_MISSING_TOKEN"
    INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    EXPIRED_TOKEN = "AUTH_EXPIRED_TOKEN"
    REVOKED_TOKEN = "AUTH_REVOKED_TOKEN"
    MALFORMED_TOKEN = "AUTH_MALFORMED_TOKEN"

    # Firebase errors
    FIREBASE_ERROR = "AUTH_FIREBASE_ERROR"
    FIREBASE_INIT_ERROR = "AUTH_FIREBASE_INIT_ERROR"
    FIREBASE_VERIFICATION_ERROR = "AUTH_FIREBASE_VERIFICATION_ERROR"

    # User errors
    USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    USER_INACTIVE = "AUTH_USER_INACTIVE"

    # Cache errors
    CACHE_ERROR = "AUTH_CACHE_ERROR"
    CACHE_CONNECTION_ERROR = "AUTH_CACHE_CONNECTION_ERROR"

    # Authorization errors
    INSUFFICIENT_PERMISSIONS = "AUTH_INSUFFICIENT_PERMISSIONS"
    ROLE_REQUIRED = "AUTH_ROLE_REQUIRED"


class OrganizationErrorCodes(StrEnum):
    """Organization-related error codes."""

    # Organization errors
    MISSING_ORGANIZATION_ID = "ORG_MISSING_ID"
    ORGANIZATION_NOT_FOUND = "ORG_NOT_FOUND"
    ORGANIZATION_INACTIVE = "ORG_INACTIVE"
    INVALID_ORGANIZATION_ID = "ORG_INVALID_ID"

    # Membership errors
    USER_NOT_MEMBER = "ORG_USER_NOT_MEMBER"
    MEMBERSHIP_INACTIVE = "ORG_MEMBERSHIP_INACTIVE"
    MEMBERSHIP_PENDING = "ORG_MEMBERSHIP_PENDING"
    MEMBERSHIP_EXPIRED = "ORG_MEMBERSHIP_EXPIRED"

    # Child organization errors
    CHILD_ORGANIZATION_NOT_FOUND = "ORG_CHILD_NOT_FOUND"
    CHILD_ORGANIZATION_INACTIVE = "ORG_CHILD_INACTIVE"
    CHILD_NOT_ALLOWED = "ORG_CHILD_NOT_ALLOWED"
    INVALID_CHILD_ORGANIZATION_ID = "ORG_INVALID_CHILD_ID"
    NOT_CHILD_OF_PARENT = "ORG_NOT_CHILD_OF_PARENT"

    # Cache errors
    CACHE_ERROR = "ORG_CACHE_ERROR"
