"""Error code constants for the application."""

from enum import StrEnum


class AuthErrorCodes(StrEnum):
    """Authentication and authorization error codes."""

    # Token errors
    MISSING_TOKEN = "AUTH_MISSING_TOKEN"
    INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    EXPIRED_TOKEN = "AUTH_EXPIRED_TOKEN"
    REVOKED_TOKEN = "AUTH_REVOKED_TOKEN"
    MALFORMED_TOKEN = "AUTH_MALFORMED_TOKEN"

    # Firebase errors
    FIREBASE_ERROR = "AUTH_FIREBASE_ERROR"
    FIREBASE_INIT_ERROR = "AUTH_FIREBASE_INIT_ERROR"
    FIREBASE_VERIFICATION_ERROR = "AUTH_FIREBASE_VERIFICATION_ERROR"

    # User errors
    USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    USER_INACTIVE = "AUTH_USER_INACTIVE"

    # Cache errors
    CACHE_ERROR = "AUTH_CACHE_ERROR"
    CACHE_CONNECTION_ERROR = "AUTH_CACHE_CONNECTION_ERROR"

    # Authorization errors
    INSUFFICIENT_PERMISSIONS = "AUTH_INSUFFICIENT_PERMISSIONS"
    ROLE_REQUIRED = "AUTH_ROLE_REQUIRED"


class OrganizationErrorCodes(StrEnum):
    """Organization-related error codes."""

    # Organization errors
    MISSING_ORGANIZATION_ID = "ORG_MISSING_ID"
    ORGANIZATION_NOT_FOUND = "ORG_NOT_FOUND"
    ORGANIZATION_INACTIVE = "ORG_INACTIVE"
    INVALID_ORGANIZATION_ID = "ORG_INVALID_ID"

    # Membership errors
    USER_NOT_MEMBER = "ORG_USER_NOT_MEMBER"
    MEMBERSHIP_INACTIVE = "ORG_MEMBERSHIP_INACTIVE"
    MEMBERSHIP_PENDING = "ORG_MEMBERSHIP_PENDING"
    MEMBERSHIP_EXPIRED = "ORG_MEMBERSHIP_EXPIRED"

    # Child organization errors
    CHILD_ORGANIZATION_NOT_FOUND = "ORG_CHILD_NOT_FOUND"
    CHILD_ORGANIZATION_INACTIVE = "ORG_CHILD_INACTIVE"
    CHILD_NOT_ALLOWED = "ORG_CHILD_NOT_ALLOWED"
    INVALID_CHILD_ORGANIZATION_ID = "ORG_INVALID_CHILD_ID"
    NOT_CHILD_OF_PARENT = "ORG_NOT_CHILD_OF_PARENT"

    # Cache errors
    CACHE_ERROR = "ORG_CACHE_ERROR"


class ProfessionalErrorCodes(StrEnum):
    """Professional module error codes."""

    # Professional errors (OrganizationProfessional)
    PROFESSIONAL_NOT_FOUND = "PROF_NOT_FOUND"
    CPF_ALREADY_EXISTS = "PROF_CPF_ALREADY_EXISTS"
    EMAIL_ALREADY_EXISTS = "PROF_EMAIL_ALREADY_EXISTS"

    # Qualification errors
    QUALIFICATION_NOT_FOUND = "PROF_QUALIFICATION_NOT_FOUND"
    QUALIFICATION_NOT_BELONGS = "PROF_QUALIFICATION_NOT_BELONGS"
    COUNCIL_REGISTRATION_EXISTS = "PROF_COUNCIL_REGISTRATION_EXISTS"
    INVALID_COUNCIL_TYPE = "PROF_INVALID_COUNCIL_TYPE"

    # Specialty errors
    SPECIALTY_NOT_FOUND = "PROF_SPECIALTY_NOT_FOUND"
    SPECIALTY_ALREADY_ASSIGNED = "PROF_SPECIALTY_ALREADY_ASSIGNED"
    DUPLICATE_SPECIALTY_IDS = "PROF_DUPLICATE_SPECIALTY_IDS"
    GLOBAL_SPECIALTY_NOT_FOUND = "PROF_GLOBAL_SPECIALTY_NOT_FOUND"

    # Education errors
    EDUCATION_NOT_FOUND = "PROF_EDUCATION_NOT_FOUND"
    QUALIFICATION_ID_REQUIRED = "PROF_QUALIFICATION_ID_REQUIRED"
    LEVEL_REQUIRED = "PROF_LEVEL_REQUIRED"
    COURSE_NAME_REQUIRED = "PROF_COURSE_NAME_REQUIRED"
    INSTITUTION_REQUIRED = "PROF_INSTITUTION_REQUIRED"

    # Document errors
    DOCUMENT_NOT_FOUND = "PROF_DOCUMENT_NOT_FOUND"
    DOCUMENT_QUALIFICATION_CATEGORY = "PROF_DOCUMENT_QUALIFICATION_CATEGORY"
    DOCUMENT_SPECIALTY_CATEGORY = "PROF_DOCUMENT_SPECIALTY_CATEGORY"

    # Company errors
    COMPANY_NOT_FOUND = "PROF_COMPANY_NOT_FOUND"
    COMPANY_ALREADY_LINKED = "PROF_COMPANY_ALREADY_LINKED"

    # Bank errors
    BANK_NOT_FOUND = "PROF_BANK_NOT_FOUND"

    # Version errors
    VERSION_NOT_FOUND = "PROF_VERSION_NOT_FOUND"
    VERSION_ALREADY_APPLIED = "PROF_VERSION_ALREADY_APPLIED"
    VERSION_ALREADY_REJECTED = "PROF_VERSION_ALREADY_REJECTED"
    VERSION_NOT_PENDING = "PROF_VERSION_NOT_PENDING"
    VERSION_FEATURE_NOT_SUPPORTED = "PROF_VERSION_FEATURE_NOT_SUPPORTED"


class ScreeningErrorCodes(StrEnum):
    """Error codes for Screening module."""

    # Process errors
    SCREENING_PROCESS_NOT_FOUND = "SCREENING_PROCESS_NOT_FOUND"
    SCREENING_PROCESS_ACTIVE_EXISTS = "SCREENING_PROCESS_ACTIVE_EXISTS"
    SCREENING_PROCESS_INVALID_STATUS = "SCREENING_PROCESS_INVALID_STATUS"
    SCREENING_PROCESS_ALREADY_COMPLETED = "SCREENING_PROCESS_ALREADY_COMPLETED"
    SCREENING_PROCESS_CANNOT_APPROVE = "SCREENING_PROCESS_CANNOT_APPROVE"
    SCREENING_PROCESS_CANNOT_REJECT = "SCREENING_PROCESS_CANNOT_REJECT"
    SCREENING_PROCESS_CANNOT_CANCEL = "SCREENING_PROCESS_CANNOT_CANCEL"
    SCREENING_PROCESS_HAS_REJECTED_DOCUMENTS = (
        "SCREENING_PROCESS_HAS_REJECTED_DOCUMENTS"
    )
    SCREENING_PROCESS_INCOMPLETE_STEPS = "SCREENING_PROCESS_INCOMPLETE_STEPS"

    # Step errors
    SCREENING_STEP_NOT_FOUND = "SCREENING_STEP_NOT_FOUND"
    SCREENING_STEP_ALREADY_COMPLETED = "SCREENING_STEP_ALREADY_COMPLETED"
    SCREENING_STEP_SKIPPED = "SCREENING_STEP_SKIPPED"
    SCREENING_STEP_NOT_IN_PROGRESS = "SCREENING_STEP_NOT_IN_PROGRESS"
    SCREENING_STEP_NOT_PENDING = "SCREENING_STEP_NOT_PENDING"
    SCREENING_STEP_INVALID_TYPE = "SCREENING_STEP_INVALID_TYPE"
    SCREENING_STEP_CANNOT_GO_BACK = "SCREENING_STEP_CANNOT_GO_BACK"
    SCREENING_STEP_NOT_ASSIGNED_TO_USER = "SCREENING_STEP_NOT_ASSIGNED_TO_USER"

    # Conversation step errors
    SCREENING_CONVERSATION_REJECTED = "SCREENING_CONVERSATION_REJECTED"

    # Professional data step errors
    SCREENING_PROFESSIONAL_NOT_LINKED = "SCREENING_PROFESSIONAL_NOT_LINKED"
    SCREENING_PROFESSIONAL_NO_QUALIFICATION = "SCREENING_PROFESSIONAL_NO_QUALIFICATION"
    SCREENING_PROFESSIONAL_TYPE_MISMATCH = "SCREENING_PROFESSIONAL_TYPE_MISMATCH"
    SCREENING_SPECIALTY_MISMATCH = "SCREENING_SPECIALTY_MISMATCH"

    # Document step errors
    SCREENING_DOCUMENTS_NOT_UPLOADED = "SCREENING_DOCUMENTS_NOT_UPLOADED"
    SCREENING_DOCUMENTS_MISSING_REQUIRED = "SCREENING_DOCUMENTS_MISSING_REQUIRED"
    SCREENING_DOCUMENTS_PENDING_REVIEW = "SCREENING_DOCUMENTS_PENDING_REVIEW"
    SCREENING_DOCUMENTS_NOT_REVIEWED = "SCREENING_DOCUMENTS_NOT_REVIEWED"
    SCREENING_DOCUMENT_NOT_FOUND = "SCREENING_DOCUMENT_NOT_FOUND"
    SCREENING_DOCUMENT_INVALID_STATUS = "SCREENING_DOCUMENT_INVALID_STATUS"
    SCREENING_DOCUMENT_TYPE_MISMATCH = "SCREENING_DOCUMENT_TYPE_MISMATCH"
    SCREENING_DOCUMENT_REUSE_PENDING = "SCREENING_DOCUMENT_REUSE_PENDING"

    # Alert errors
    SCREENING_ALERT_NOT_FOUND = "SCREENING_ALERT_NOT_FOUND"
    SCREENING_ALERT_ALREADY_EXISTS = "SCREENING_ALERT_ALREADY_EXISTS"
    SCREENING_ALERT_ALREADY_RESOLVED = "SCREENING_ALERT_ALREADY_RESOLVED"
    SCREENING_PROCESS_BLOCKED_BY_ALERT = "SCREENING_PROCESS_BLOCKED_BY_ALERT"


class UserErrorCodes(StrEnum):
    """User management error codes."""

    # User errors
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_MEMBER = "USER_ALREADY_MEMBER"
    USER_NOT_MEMBER = "USER_NOT_MEMBER"

    # Invitation errors
    INVITATION_ALREADY_SENT = "USER_INVITATION_ALREADY_SENT"
    INVITATION_NOT_FOUND = "USER_INVITATION_NOT_FOUND"
    INVITATION_EXPIRED = "USER_INVITATION_EXPIRED"
    INVITATION_ALREADY_ACCEPTED = "USER_INVITATION_ALREADY_ACCEPTED"
    INVITATION_INVALID_TOKEN = "USER_INVITATION_INVALID_TOKEN"

    # Membership errors
    MEMBERSHIP_NOT_FOUND = "USER_MEMBERSHIP_NOT_FOUND"
    CANNOT_REMOVE_OWNER = "USER_CANNOT_REMOVE_OWNER"
    CANNOT_REMOVE_SELF = "USER_CANNOT_REMOVE_SELF"

    # Role errors
    ROLE_NOT_FOUND = "USER_ROLE_NOT_FOUND"
    INVALID_ROLE = "USER_INVALID_ROLE"


class DocumentTypeErrorCodes(StrEnum):
    """DocumentType module error codes."""

    # Document type errors
    DOCUMENT_TYPE_NOT_FOUND = "DOC_TYPE_NOT_FOUND"
    DOCUMENT_TYPE_IN_USE = "DOC_TYPE_IN_USE"
