"""remove_professional_soft_delete_add_cascade

Revision ID: 000000000013
Revises: 000000000012
Create Date: 2026-02-02 10:24:14.448380

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "000000000013"
down_revision: Union[str, Sequence[str], None] = "000000000012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute(
        """
        CREATE OR REPLACE FUNCTION f_unaccent(text)
        RETURNS text AS
        $func$
        SELECT public.unaccent('public.unaccent', $1)
        $func$
        LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT;
        """
    )
    op.add_column("document_types", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("document_types", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.alter_column(
        "document_types",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "document_types",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sqlmodel.sql.sqltypes.AutoString(length=255),
        existing_nullable=False,
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'documentcategory')
               AND NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'document_category') THEN
                ALTER TYPE documentcategory RENAME TO document_category;
            END IF;
        END $$;
        """
    )
    op.execute(
        "ALTER TABLE document_types ALTER COLUMN category TYPE document_category "
        "USING category::text::document_category"
    )
    op.alter_column(
        "document_types",
        "help_text",
        existing_type=sa.VARCHAR(length=1000),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.create_unique_constraint(
        "uq_document_types_code_org", "document_types", ["code", "organization_id"]
    )
    op.drop_constraint(
        op.f("document_types_organization_id_fkey"),
        "document_types",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "document_types", "organizations", ["organization_id"], ["id"]
    )
    op.drop_index(
        op.f("idx_organization_professionals_search_trgm"),
        table_name="organization_professionals",
        postgresql_ops={
            "((((COALESCE(f_unaccent(lower(full_name::text)), ''::text) || ' '::text) || COALESCE(f_unaccent(lower(email::text)), ''::text)) || ' '::text) || COALESCE(cpf, ''::character varying)::text)": "gin_trgm_ops"
        },
        postgresql_using="gin",
        postgresql_where="(deleted_at IS NULL)",
    )
    op.create_index(
        "idx_organization_professionals_search_trgm",
        "organization_professionals",
        [
            sa.literal_column(
                "(COALESCE(f_unaccent(lower(full_name)), '') || ' ' || COALESCE(f_unaccent(lower(email)), '') || ' ' || COALESCE(cpf, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={
            "(COALESCE(f_unaccent(lower(full_name)), '') || ' ' || COALESCE(f_unaccent(lower(email)), '') || ' ' || COALESCE(cpf, ''))": "gin_trgm_ops"
        },
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.alter_column(
        "professional_documents",
        "source_type",
        existing_type=postgresql.ENUM("DIRECT", "SCREENING", name="documentsourcetype"),
        comment=None,
        existing_comment="How this document was created (DIRECT or SCREENING)",
        existing_nullable=False,
    )
    op.alter_column(
        "professional_documents",
        "is_pending",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="True if document is pending screening approval",
        existing_nullable=False,
    )
    op.alter_column(
        "professional_documents",
        "document_type_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        "professional_documents",
        "screening_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Screening process that created this document",
        existing_nullable=True,
    )
    op.alter_column(
        "professional_documents",
        "promoted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When document was promoted from pending",
        existing_nullable=True,
    )
    op.alter_column(
        "professional_documents",
        "promoted_by",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="User who promoted the document from pending",
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("professional_documents_qualification_id_fkey"),
        "professional_documents",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_professional_documents_screening_id"),
        "professional_documents",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("professional_documents_specialty_id_fkey"),
        "professional_documents",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "professional_documents",
        "professional_qualifications",
        ["qualification_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "professional_documents", "document_types", ["document_type_id"], ["id"]
    )
    op.create_foreign_key(
        None,
        "professional_documents",
        "professional_specialties",
        ["specialty_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "professional_documents", "screening_processes", ["screening_id"], ["id"]
    )
    op.drop_index(
        op.f("idx_professional_educations_search_trgm"),
        table_name="professional_educations",
        postgresql_ops={
            "((COALESCE(f_unaccent(lower(course_name::text)), ''::text) || ' '::text) || COALESCE(f_unaccent(lower(institution::text)), ''::text))": "gin_trgm_ops"
        },
        postgresql_using="gin",
        postgresql_where="(deleted_at IS NULL)",
    )
    op.create_index(
        "idx_professional_educations_search_trgm",
        "professional_educations",
        [
            sa.literal_column(
                "(COALESCE(f_unaccent(lower(course_name)), '') || ' ' || COALESCE(f_unaccent(lower(institution)), ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={
            "(COALESCE(f_unaccent(lower(course_name)), '') || ' ' || COALESCE(f_unaccent(lower(institution)), ''))": "gin_trgm_ops"
        },
    )
    op.drop_constraint(
        op.f("professional_educations_qualification_id_fkey"),
        "professional_educations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "professional_educations",
        "professional_qualifications",
        ["qualification_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("professional_educations", "deleted_at")
    op.drop_constraint(
        op.f("professional_qualifications_organization_professional_id_fkey"),
        "professional_qualifications",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "professional_qualifications",
        "organization_professionals",
        ["organization_professional_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("professional_qualifications", "deleted_at")
    op.drop_constraint(
        op.f("professional_specialties_qualification_id_fkey"),
        "professional_specialties",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "professional_specialties",
        "professional_qualifications",
        ["qualification_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("professional_specialties", "deleted_at")
    op.alter_column(
        "screening_alerts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_constraint(
        op.f("fk_screening_alerts_process_id_screening_processes"),
        "screening_alerts",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "screening_alerts", "screening_processes", ["process_id"], ["id"]
    )
    op.alter_column(
        "screening_document_review_steps",
        "correction_needed_count",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Documents needing correction (re-upload)",
        existing_nullable=False,
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'screening_document_status')
               AND NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'screeningdocumentstatus') THEN
                ALTER TYPE screening_document_status RENAME TO screeningdocumentstatus;
            END IF;
        END $$;
        """
    )
    op.execute(
        "ALTER TABLE screening_documents ALTER COLUMN status TYPE screeningdocumentstatus "
        "USING status::text::screeningdocumentstatus"
    )
    op.alter_column(
        "screening_documents",
        "document_type_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.create_unique_constraint(
        "uq_screening_documents_step_doc_type",
        "screening_documents",
        ["upload_step_id", "document_type_id"],
    )
    op.create_foreign_key(
        None, "screening_documents", "document_types", ["document_type_id"], ["id"]
    )
    op.drop_column("screening_documents", "alert_reason")
    op.alter_column(
        "screening_processes",
        "supervisor_id",
        existing_type=sa.UUID(),
        nullable=False,
        comment=None,
        existing_comment="Supervisor responsible for reviewing alerts",
    )
    op.create_index(
        "ix_screening_processes_supervisor",
        "screening_processes",
        ["supervisor_id"],
        unique=False,
    )
    op.drop_index(
        op.f("idx_specialties_search_trgm"),
        table_name="specialties",
        postgresql_ops={
            "((COALESCE(lower(code::text), ''::text) || ' '::text) || COALESCE(f_unaccent(lower(name::text)), ''::text))": "gin_trgm_ops"
        },
        postgresql_using="gin",
        postgresql_where="(deleted_at IS NULL)",
    )
    op.create_index(
        "idx_specialties_search_trgm",
        "specialties",
        [
            sa.literal_column(
                "(COALESCE(lower(code), '') || ' ' || COALESCE(f_unaccent(lower(name)), ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={
            "(COALESCE(lower(code), '') || ' ' || COALESCE(f_unaccent(lower(name)), ''))": "gin_trgm_ops"
        },
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_specialties_search_trgm",
        table_name="specialties",
        postgresql_using="gin",
        postgresql_ops={"": "gin_trgm_ops"},
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("idx_specialties_search_trgm"),
        "specialties",
        [
            sa.literal_column(
                "((COALESCE(lower(code::text), ''::text) || ' '::text) || COALESCE(f_unaccent(lower(name::text)), ''::text))"
            )
        ],
        unique=False,
        postgresql_ops={
            "((COALESCE(lower(code::text), ''::text) || ' '::text) || COALESCE(f_unaccent(lower(name::text)), ''::text))": "gin_trgm_ops"
        },
        postgresql_using="gin",
        postgresql_where="(deleted_at IS NULL)",
    )
    op.drop_index("ix_screening_processes_supervisor", table_name="screening_processes")
    op.alter_column(
        "screening_processes",
        "supervisor_id",
        existing_type=sa.UUID(),
        nullable=True,
        comment="Supervisor responsible for reviewing alerts",
    )
    op.add_column(
        "screening_documents",
        sa.Column(
            "alert_reason", sa.VARCHAR(length=1000), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "screening_documents", type_="foreignkey")
    op.drop_constraint(
        "uq_screening_documents_step_doc_type", "screening_documents", type_="unique"
    )
    op.alter_column(
        "screening_documents",
        "document_type_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'screeningdocumentstatus')
               AND NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'screening_document_status') THEN
                ALTER TYPE screeningdocumentstatus RENAME TO screening_document_status;
            END IF;
        END $$;
        """
    )
    op.execute(
        "ALTER TABLE screening_documents ALTER COLUMN status TYPE screening_document_status "
        "USING status::text::screening_document_status"
    )
    op.alter_column(
        "screening_document_review_steps",
        "correction_needed_count",
        existing_type=sa.INTEGER(),
        comment="Documents needing correction (re-upload)",
        existing_nullable=False,
    )
    op.drop_constraint(None, "screening_alerts", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_screening_alerts_process_id_screening_processes"),
        "screening_alerts",
        "screening_processes",
        ["process_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "screening_alerts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.add_column(
        "professional_specialties",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "professional_specialties", type_="foreignkey")
    op.create_foreign_key(
        op.f("professional_specialties_qualification_id_fkey"),
        "professional_specialties",
        "professional_qualifications",
        ["qualification_id"],
        ["id"],
    )
    op.add_column(
        "professional_qualifications",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "professional_qualifications", type_="foreignkey")
    op.create_foreign_key(
        op.f("professional_qualifications_organization_professional_id_fkey"),
        "professional_qualifications",
        "organization_professionals",
        ["organization_professional_id"],
        ["id"],
    )
    op.add_column(
        "professional_educations",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "professional_educations", type_="foreignkey")
    op.create_foreign_key(
        op.f("professional_educations_qualification_id_fkey"),
        "professional_educations",
        "professional_qualifications",
        ["qualification_id"],
        ["id"],
    )
    op.drop_index(
        "idx_professional_educations_search_trgm",
        table_name="professional_educations",
        postgresql_using="gin",
        postgresql_ops={"": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("idx_professional_educations_search_trgm"),
        "professional_educations",
        [
            sa.literal_column(
                "((COALESCE(f_unaccent(lower(course_name::text)), ''::text) || ' '::text) || COALESCE(f_unaccent(lower(institution::text)), ''::text))"
            )
        ],
        unique=False,
        postgresql_ops={
            "((COALESCE(f_unaccent(lower(course_name::text)), ''::text) || ' '::text) || COALESCE(f_unaccent(lower(institution::text)), ''::text))": "gin_trgm_ops"
        },
        postgresql_using="gin",
        postgresql_where="(deleted_at IS NULL)",
    )
    op.drop_constraint(None, "professional_documents", type_="foreignkey")
    op.drop_constraint(None, "professional_documents", type_="foreignkey")
    op.drop_constraint(None, "professional_documents", type_="foreignkey")
    op.drop_constraint(None, "professional_documents", type_="foreignkey")
    op.create_foreign_key(
        op.f("professional_documents_specialty_id_fkey"),
        "professional_documents",
        "professional_specialties",
        ["specialty_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_professional_documents_screening_id"),
        "professional_documents",
        "screening_processes",
        ["screening_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("professional_documents_qualification_id_fkey"),
        "professional_documents",
        "professional_qualifications",
        ["qualification_id"],
        ["id"],
    )
    op.alter_column(
        "professional_documents",
        "promoted_by",
        existing_type=sa.UUID(),
        comment="User who promoted the document from pending",
        existing_nullable=True,
    )
    op.alter_column(
        "professional_documents",
        "promoted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When document was promoted from pending",
        existing_nullable=True,
    )
    op.alter_column(
        "professional_documents",
        "screening_id",
        existing_type=sa.UUID(),
        comment="Screening process that created this document",
        existing_nullable=True,
    )
    op.alter_column(
        "professional_documents",
        "document_type_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.alter_column(
        "professional_documents",
        "is_pending",
        existing_type=sa.BOOLEAN(),
        comment="True if document is pending screening approval",
        existing_nullable=False,
    )
    op.alter_column(
        "professional_documents",
        "source_type",
        existing_type=postgresql.ENUM("DIRECT", "SCREENING", name="documentsourcetype"),
        comment="How this document was created (DIRECT or SCREENING)",
        existing_nullable=False,
    )
    op.drop_index(
        "idx_organization_professionals_search_trgm",
        table_name="organization_professionals",
        postgresql_using="gin",
        postgresql_ops={"": "gin_trgm_ops"},
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("idx_organization_professionals_search_trgm"),
        "organization_professionals",
        [
            sa.literal_column(
                "((((COALESCE(f_unaccent(lower(full_name::text)), ''::text) || ' '::text) || COALESCE(f_unaccent(lower(email::text)), ''::text)) || ' '::text) || COALESCE(cpf, ''::character varying)::text)"
            )
        ],
        unique=False,
        postgresql_ops={
            "((((COALESCE(f_unaccent(lower(full_name::text)), ''::text) || ' '::text) || COALESCE(f_unaccent(lower(email::text)), ''::text)) || ' '::text) || COALESCE(cpf, ''::character varying)::text)": "gin_trgm_ops"
        },
        postgresql_using="gin",
        postgresql_where="(deleted_at IS NULL)",
    )
    op.drop_constraint(None, "document_types", type_="foreignkey")
    op.create_foreign_key(
        op.f("document_types_organization_id_fkey"),
        "document_types",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_document_types_code_org", "document_types", type_="unique")
    op.alter_column(
        "document_types",
        "help_text",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=1000),
        existing_nullable=True,
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'document_category')
               AND NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'documentcategory') THEN
                ALTER TYPE document_category RENAME TO documentcategory;
            END IF;
        END $$;
        """
    )
    op.execute(
        "ALTER TABLE document_types ALTER COLUMN category TYPE documentcategory "
        "USING category::text::documentcategory"
    )
    op.alter_column(
        "document_types",
        "name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "document_types",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("document_types", "updated_by")
    op.drop_column("document_types", "created_by")
    # ### end Alembic commands ###
