"""add screening

Revision ID: 6c70dbce726c
Revises: f9a5840a42d0
Create Date: 2026-01-20 11:53:58.918805

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6c70dbce726c"
down_revision: Union[str, Sequence[str], None] = "f9a5840a42d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Enum types that already exist in the database (use create_type=False)
professional_type_enum = postgresql.ENUM(
    "DOCTOR",
    "NURSE",
    "NURSING_TECH",
    "PHARMACIST",
    "DENTIST",
    "PHYSIOTHERAPIST",
    "PSYCHOLOGIST",
    "NUTRITIONIST",
    "BIOMEDIC",
    "OTHER",
    name="professional_type",
    create_type=False,
)

document_type_enum = postgresql.ENUM(
    "ID_DOCUMENT",
    "PHOTO",
    "CRIMINAL_RECORD",
    "ADDRESS_PROOF",
    "CV",
    "DIPLOMA",
    "CRM_REGISTRATION_CERTIFICATE",
    "CRM_FINANCIAL_CERTIFICATE",
    "CRM_ETHICS_CERTIFICATE",
    "RESIDENCY_CERTIFICATE",
    "SPECIALIST_TITLE",
    "SBA_DIPLOMA",
    "OTHER",
    name="document_type",
    create_type=False,
)

document_category_enum = postgresql.ENUM(
    "PROFILE",
    "QUALIFICATION",
    "SPECIALTY",
    name="document_category",
    create_type=False,
)

# New enum types to be created in this migration
step_type_enum = postgresql.ENUM(
    "CONVERSATION",
    "PROFESSIONAL_DATA",
    "QUALIFICATION",
    "SPECIALTY",
    "EDUCATION",
    "DOCUMENTS",
    "COMPANY",
    "BANK_ACCOUNT",
    "DOCUMENT_REVIEW",
    "SUPERVISOR_REVIEW",
    name="step_type",
    create_type=False,
)

screening_status_enum = postgresql.ENUM(
    "DRAFT",
    "CONVERSATION",
    "IN_PROGRESS",
    "PENDING_REVIEW",
    "UNDER_REVIEW",
    "PENDING_CORRECTION",
    "ESCALATED",
    "APPROVED",
    "REJECTED",
    "EXPIRED",
    "CANCELLED",
    name="screening_status",
    create_type=False,
)

step_status_enum = postgresql.ENUM(
    "PENDING",
    "IN_PROGRESS",
    "COMPLETED",
    "APPROVED",
    "REJECTED",
    "SKIPPED",
    "CORRECTION_NEEDED",
    name="step_status",
    create_type=False,
)

conversation_outcome_enum = postgresql.ENUM(
    "PROCEED",
    "REJECT",
    name="conversation_outcome",
    create_type=False,
)

document_review_status_enum = postgresql.ENUM(
    "PENDING",
    "APPROVED",
    "REJECTED",
    "ALERT",
    name="document_review_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # Create new enum types first
    step_type_enum.create(op.get_bind(), checkfirst=True)
    screening_status_enum.create(op.get_bind(), checkfirst=True)
    step_status_enum.create(op.get_bind(), checkfirst=True)
    conversation_outcome_enum.create(op.get_bind(), checkfirst=True)
    document_review_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screening_templates",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.Column(
            "professional_type",
            professional_type_enum,
            nullable=True,
        ),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("default_expiration_days", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_screening_templates_organization_id",
        "screening_templates",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_screening_templates_professional_type",
        "screening_templates",
        ["professional_type"],
        unique=False,
    )
    op.create_index(
        "uq_screening_templates_org_default",
        "screening_templates",
        ["organization_id"],
        unique=True,
        postgresql_where="is_default = true AND deleted_at IS NULL",
    )
    op.create_index(
        "uq_screening_templates_org_name",
        "screening_templates",
        ["organization_id", "name"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_table(
        "screening_template_steps",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("step_type", step_type_enum, nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "instructions", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.Column("depends_on", sa.JSON(), nullable=True),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["screening_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "template_id", "order", name="uq_screening_template_steps_template_order"
        ),
        sa.UniqueConstraint(
            "template_id",
            "step_type",
            name="uq_screening_template_steps_template_step_type",
        ),
    )
    op.create_table(
        "screening_processes",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("status", screening_status_enum, nullable=False),
        sa.Column(
            "professional_cpf",
            sqlmodel.sql.sqltypes.AutoString(length=11),
            nullable=True,
        ),
        sa.Column(
            "professional_email",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "professional_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "professional_phone",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=True,
        ),
        sa.Column(
            "access_token", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_step_type", step_type_enum, nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("escalated_to", sa.Uuid(), nullable=True),
        sa.Column(
            "escalation_reason",
            sqlmodel.sql.sqltypes.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column(
            "rejection_reason",
            sqlmodel.sql.sqltypes.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column(
            "notes", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("organization_professional_id", sa.Uuid(), nullable=True),
        sa.Column("professional_contract_id", sa.Uuid(), nullable=True),
        sa.Column("client_contract_id", sa.Uuid(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "review_notes", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["client_contract_id"],
            ["client_contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_professional_id"],
            ["organization_professionals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["professional_contract_id"],
            ["professional_contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["screening_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_screening_processes_access_token",
        "screening_processes",
        ["access_token"],
        unique=True,
        postgresql_where="access_token IS NOT NULL",
    )
    op.create_index(
        "ix_screening_processes_assigned_to",
        "screening_processes",
        ["assigned_to"],
        unique=False,
    )
    op.create_index(
        "ix_screening_processes_escalated_to",
        "screening_processes",
        ["escalated_to"],
        unique=False,
    )
    op.create_index(
        "ix_screening_processes_organization_id",
        "screening_processes",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_screening_processes_professional_id",
        "screening_processes",
        ["organization_professional_id"],
        unique=False,
    )
    op.create_index(
        "ix_screening_processes_status", "screening_processes", ["status"], unique=False
    )
    op.create_index(
        "uq_screening_processes_org_cpf_active",
        "screening_processes",
        ["organization_id", "professional_cpf"],
        unique=True,
        postgresql_where="status NOT IN ('APPROVED', 'REJECTED', 'EXPIRED', 'CANCELLED') AND deleted_at IS NULL AND professional_cpf IS NOT NULL",
    )
    op.create_table(
        "screening_process_steps",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("step_type", step_type_enum, nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("status", step_status_enum, nullable=False),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("data_references", sa.JSON(), nullable=True),
        sa.Column(
            "conversation_notes",
            sqlmodel.sql.sqltypes.AutoString(length=4000),
            nullable=True,
        ),
        sa.Column("conversation_outcome", conversation_outcome_enum, nullable=True),
        sa.Column(
            "review_notes", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.Column(
            "rejection_reason",
            sqlmodel.sql.sqltypes.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column("process_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["process_id"],
            ["screening_processes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "process_id",
            "step_type",
            name="uq_screening_process_steps_process_step_type",
        ),
    )
    op.create_index(
        "ix_screening_process_steps_assigned_to",
        "screening_process_steps",
        ["assigned_to"],
        unique=False,
    )
    op.create_index(
        "ix_screening_process_steps_process_id",
        "screening_process_steps",
        ["process_id"],
        unique=False,
    )
    op.create_index(
        "ix_screening_process_steps_status",
        "screening_process_steps",
        ["status"],
        unique=False,
    )
    op.create_table(
        "screening_required_documents",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_type", document_type_enum, nullable=False),
        sa.Column("document_category", document_category_enum, nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("process_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["process_id"],
            ["screening_processes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "process_id",
            "document_type",
            name="uq_screening_required_documents_process_doc_type",
        ),
    )
    op.create_index(
        "ix_screening_required_documents_category",
        "screening_required_documents",
        ["document_category"],
        unique=False,
    )
    op.create_index(
        "ix_screening_required_documents_process_id",
        "screening_required_documents",
        ["process_id"],
        unique=False,
    )
    op.create_table(
        "screening_document_reviews",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("status", document_review_status_enum, nullable=False),
        sa.Column(
            "review_notes", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.Column(
            "rejection_reason",
            sqlmodel.sql.sqltypes.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column(
            "alert_reason", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("process_id", sa.Uuid(), nullable=False),
        sa.Column("process_step_id", sa.Uuid(), nullable=True),
        sa.Column("professional_document_id", sa.Uuid(), nullable=False),
        sa.Column("required_document_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["process_id"],
            ["screening_processes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["process_step_id"],
            ["screening_process_steps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["professional_document_id"],
            ["professional_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["required_document_id"],
            ["screening_required_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "process_id",
            "professional_document_id",
            name="uq_screening_doc_reviews_process_prof_doc",
        ),
    )
    op.create_index(
        "ix_screening_document_reviews_process_id",
        "screening_document_reviews",
        ["process_id"],
        unique=False,
    )
    op.create_index(
        "ix_screening_document_reviews_status",
        "screening_document_reviews",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_screening_document_reviews_step_id",
        "screening_document_reviews",
        ["process_step_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_screening_document_reviews_step_id", table_name="screening_document_reviews"
    )
    op.drop_index(
        "ix_screening_document_reviews_status", table_name="screening_document_reviews"
    )
    op.drop_index(
        "ix_screening_document_reviews_process_id",
        table_name="screening_document_reviews",
    )
    op.drop_table("screening_document_reviews")
    op.drop_index(
        "ix_screening_required_documents_process_id",
        table_name="screening_required_documents",
    )
    op.drop_index(
        "ix_screening_required_documents_category",
        table_name="screening_required_documents",
    )
    op.drop_table("screening_required_documents")
    op.drop_index(
        "ix_screening_process_steps_status", table_name="screening_process_steps"
    )
    op.drop_index(
        "ix_screening_process_steps_process_id", table_name="screening_process_steps"
    )
    op.drop_index(
        "ix_screening_process_steps_assigned_to", table_name="screening_process_steps"
    )
    op.drop_table("screening_process_steps")
    op.drop_index(
        "uq_screening_processes_org_cpf_active",
        table_name="screening_processes",
        postgresql_where="status NOT IN ('APPROVED', 'REJECTED', 'EXPIRED', 'CANCELLED') AND deleted_at IS NULL AND professional_cpf IS NOT NULL",
    )
    op.drop_index("ix_screening_processes_status", table_name="screening_processes")
    op.drop_index(
        "ix_screening_processes_professional_id", table_name="screening_processes"
    )
    op.drop_index(
        "ix_screening_processes_organization_id", table_name="screening_processes"
    )
    op.drop_index(
        "ix_screening_processes_escalated_to", table_name="screening_processes"
    )
    op.drop_index(
        "ix_screening_processes_assigned_to", table_name="screening_processes"
    )
    op.drop_index(
        "ix_screening_processes_access_token",
        table_name="screening_processes",
        postgresql_where="access_token IS NOT NULL",
    )
    op.drop_table("screening_processes")
    op.drop_table("screening_template_steps")
    op.drop_index(
        "uq_screening_templates_org_name",
        table_name="screening_templates",
        postgresql_where="deleted_at IS NULL",
    )
    op.drop_index(
        "uq_screening_templates_org_default",
        table_name="screening_templates",
        postgresql_where="is_default = true AND deleted_at IS NULL",
    )
    op.drop_index(
        "ix_screening_templates_professional_type", table_name="screening_templates"
    )
    op.drop_index(
        "ix_screening_templates_organization_id", table_name="screening_templates"
    )
    op.drop_table("screening_templates")

    # Drop enum types created in this migration (not document_type and document_category - they existed before)
    sa.Enum(name="document_review_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="conversation_outcome").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="step_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="screening_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="step_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
