"""professionals indexes

Revision ID: 9fd32650c669
Revises: b2c3d4e5f6g7
Create Date: 2026-01-21 11:28:13.286047

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fd32650c669"
down_revision: Union[str, Sequence[str], None] = "b2c3d4e5f6g7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_organization_professionals_organization_id"),
        table_name="organization_professionals",
    )
    op.create_index(
        "idx_organization_professionals_created_at",
        "organization_professionals",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # GIN trigram index - must use raw SQL for expression indexes
    op.execute("""
        CREATE INDEX idx_organization_professionals_full_name_trgm
        ON organization_professionals
        USING gin (f_unaccent(lower(full_name)) gin_trgm_ops)
        WHERE deleted_at IS NULL
    """)
    op.create_index(
        "idx_organization_professionals_is_active",
        "organization_professionals",
        ["is_active"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "idx_organization_professionals_org_active",
        "organization_professionals",
        ["organization_id", "is_active"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # GIN trigram index - must use raw SQL for expression indexes
    op.execute("""
        CREATE INDEX idx_organization_professionals_search_trgm
        ON organization_professionals
        USING gin (
            (COALESCE(f_unaccent(lower(full_name)), '') || ' ' ||
             COALESCE(f_unaccent(lower(email)), '') || ' ' ||
             COALESCE(cpf, '')) gin_trgm_ops
        )
        WHERE deleted_at IS NULL
    """)
    op.create_index(
        "idx_professional_documents_category",
        "professional_documents",
        ["document_category"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "idx_professional_documents_expires",
        "professional_documents",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND expires_at IS NOT NULL"),
    )
    # GIN trigram index - must use raw SQL for expression indexes
    op.execute("""
        CREATE INDEX idx_professional_documents_filename_trgm
        ON professional_documents
        USING gin (f_unaccent(lower(file_name)) gin_trgm_ops)
        WHERE deleted_at IS NULL
    """)
    op.create_index(
        "idx_professional_documents_type",
        "professional_documents",
        ["document_type"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "idx_professional_educations_completed",
        "professional_educations",
        ["is_completed"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "idx_professional_educations_level",
        "professional_educations",
        ["level"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # GIN trigram index - must use raw SQL for expression indexes
    op.execute("""
        CREATE INDEX idx_professional_educations_search_trgm
        ON professional_educations
        USING gin (
            (COALESCE(f_unaccent(lower(course_name)), '') || ' ' ||
             COALESCE(f_unaccent(lower(institution)), '')) gin_trgm_ops
        )
        WHERE deleted_at IS NULL
    """)
    op.drop_index(
        op.f("ix_professional_qualifications_org_professional_id"),
        table_name="professional_qualifications",
    )
    op.create_index(
        "idx_professional_qualifications_council",
        "professional_qualifications",
        ["council_type", "council_state"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # GIN trigram index - must use raw SQL for expression indexes
    op.execute("""
        CREATE INDEX idx_professional_qualifications_council_trgm
        ON professional_qualifications
        USING gin (lower(council_number) gin_trgm_ops)
        WHERE deleted_at IS NULL
    """)
    op.create_index(
        "idx_professional_qualifications_org_type",
        "professional_qualifications",
        ["organization_id", "professional_type"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "idx_professional_qualifications_type",
        "professional_qualifications",
        ["professional_type"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "idx_specialties_name",
        "specialties",
        ["name"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # GIN trigram index - must use raw SQL for expression indexes
    op.execute("""
        CREATE INDEX idx_specialties_search_trgm
        ON specialties
        USING gin (
            (COALESCE(lower(code), '') || ' ' ||
             COALESCE(f_unaccent(lower(name)), '')) gin_trgm_ops
        )
        WHERE deleted_at IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_specialties_search_trgm", table_name="specialties")
    op.drop_index("idx_specialties_name", table_name="specialties")
    op.drop_index(
        "idx_professional_qualifications_type", table_name="professional_qualifications"
    )
    op.drop_index(
        "idx_professional_qualifications_org_type",
        table_name="professional_qualifications",
    )
    op.drop_index(
        "idx_professional_qualifications_council_trgm",
        table_name="professional_qualifications",
    )
    op.drop_index(
        "idx_professional_qualifications_council",
        table_name="professional_qualifications",
    )
    op.create_index(
        op.f("ix_professional_qualifications_org_professional_id"),
        "professional_qualifications",
        ["organization_professional_id"],
        unique=False,
    )
    op.drop_index(
        "idx_professional_educations_search_trgm", table_name="professional_educations"
    )
    op.drop_index(
        "idx_professional_educations_level", table_name="professional_educations"
    )
    op.drop_index(
        "idx_professional_educations_completed", table_name="professional_educations"
    )
    op.drop_index(
        "idx_professional_documents_type", table_name="professional_documents"
    )
    op.drop_index(
        "idx_professional_documents_filename_trgm", table_name="professional_documents"
    )
    op.drop_index(
        "idx_professional_documents_expires", table_name="professional_documents"
    )
    op.drop_index(
        "idx_professional_documents_category", table_name="professional_documents"
    )
    op.drop_index(
        "idx_organization_professionals_search_trgm",
        table_name="organization_professionals",
    )
    op.drop_index(
        "idx_organization_professionals_org_active",
        table_name="organization_professionals",
    )
    op.drop_index(
        "idx_organization_professionals_is_active",
        table_name="organization_professionals",
    )
    op.drop_index(
        "idx_organization_professionals_full_name_trgm",
        table_name="organization_professionals",
    )
    op.drop_index(
        "idx_organization_professionals_created_at",
        table_name="organization_professionals",
    )
    op.create_index(
        op.f("ix_organization_professionals_organization_id"),
        "organization_professionals",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###
