"""add professionals

Revision ID: a16d735522cf
Revises: 3b2baefd4a62
Create Date: 2026-01-19 14:36:24.460044

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a16d735522cf"
down_revision: Union[str, Sequence[str], None] = "3b2baefd4a62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banks",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column(
            "ispb_code", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "short_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_banks_code"),
        sa.UniqueConstraint("ispb_code", name="uq_banks_ispb_code"),
    )
    op.create_table(
        "specialties",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "professional_type",
            sa.Enum(
                "DOCTOR",
                "NURSE",
                "NURSING_TECH",
                "PHARMACIST",
                "DENTIST",
                "PHYSIOTHERAPIST",
                "PSYCHOLOGIST",
                "NUTRITIONIST",
                "BIOMEDIC",
                "OTHER",
                name="professional_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_generalist", sa.Boolean(), nullable=False),
        sa.Column("requires_residency", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_specialties_code"),
    )
    op.create_table(
        "companies",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.Uuid(), nullable=True),
        sa.Column(
            "address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column(
            "complement", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "neighborhood", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column(
            "state_code", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
        ),
        sa.Column(
            "state_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "postal_code", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True
        ),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("cnpj", sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
        sa.Column(
            "legal_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "trade_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "state_registration",
            sqlmodel.sql.sqltypes.AutoString(length=30),
            nullable=True,
        ),
        sa.Column(
            "municipal_registration",
            sqlmodel.sql.sqltypes.AutoString(length=30),
            nullable=True,
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cnpj", name="uq_companies_cnpj"),
    )
    op.create_table(
        "professional_profiles",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.Uuid(), nullable=True),
        sa.Column(
            "address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column(
            "complement", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "neighborhood", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column(
            "state_code", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
        ),
        sa.Column(
            "state_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "postal_code", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True
        ),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("cpf", sqlmodel.sql.sqltypes.AutoString(length=11), nullable=True),
        sa.Column("birth_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "nationality", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", name="gender", create_constraint=True),
            nullable=True,
        ),
        sa.Column(
            "marital_status",
            sa.Enum(
                "SINGLE",
                "MARRIED",
                "DIVORCED",
                "WIDOWED",
                "SEPARATED",
                "CIVIL_UNION",
                name="marital_status",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "avatar_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True
        ),
        sa.Column("profile_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf", name="uq_professional_profiles_cpf"),
        sa.UniqueConstraint("user_id", name="uq_professional_profiles_user_id"),
    )
    op.create_table(
        "bank_accounts",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.Uuid(), nullable=True),
        sa.Column(
            "agency", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column(
            "agency_digit", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
        ),
        sa.Column(
            "account_number",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
        sa.Column(
            "account_digit", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
        ),
        sa.Column(
            "account_type",
            sa.Enum("CHECKING", "SAVINGS", name="account_type", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "holder_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "holder_document",
            sqlmodel.sql.sqltypes.AutoString(length=14),
            nullable=False,
        ),
        sa.Column(
            "pix_key_type",
            sa.Enum(
                "CPF",
                "CNPJ",
                "EMAIL",
                "PHONE",
                "RANDOM",
                name="pix_key_type",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "pix_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("bank_id", sa.Uuid(), nullable=False),
        sa.Column("professional_id", sa.Uuid(), nullable=True),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(professional_id IS NOT NULL AND company_id IS NULL) OR (professional_id IS NULL AND company_id IS NOT NULL)",
            name="ck_bank_accounts_owner",
        ),
        sa.ForeignKeyConstraint(
            ["bank_id"],
            ["banks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professional_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bank_id",
            "agency",
            "account_number",
            "company_id",
            name="uq_bank_accounts_company_account",
        ),
        sa.UniqueConstraint(
            "bank_id",
            "agency",
            "account_number",
            "professional_id",
            name="uq_bank_accounts_professional_account",
        ),
    )
    op.create_index(
        "uq_bank_accounts_company_primary",
        "bank_accounts",
        ["company_id"],
        unique=True,
        postgresql_where="is_primary = true AND company_id IS NOT NULL",
    )
    op.create_index(
        "uq_bank_accounts_professional_primary",
        "bank_accounts",
        ["professional_id"],
        unique=True,
        postgresql_where="is_primary = true AND professional_id IS NOT NULL",
    )
    op.create_table(
        "professional_companies",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("professional_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professional_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "professional_id",
            "company_id",
            name="uq_professional_companies_professional_company",
        ),
    )
    op.create_table(
        "professional_qualifications",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.Uuid(), nullable=True),
        sa.Column(
            "professional_type",
            sa.Enum(
                "DOCTOR",
                "NURSE",
                "NURSING_TECH",
                "PHARMACIST",
                "DENTIST",
                "PHYSIOTHERAPIST",
                "PSYCHOLOGIST",
                "NUTRITIONIST",
                "BIOMEDIC",
                "OTHER",
                name="professional_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("graduation_year", sa.Integer(), nullable=True),
        sa.Column(
            "council_type",
            sa.Enum(
                "CRM",
                "COREN",
                "CRF",
                "CRO",
                "CREFITO",
                "CRP",
                "CRN",
                "CRBM",
                "OTHER",
                name="council_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "council_number",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
        sa.Column(
            "council_state", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False
        ),
        sa.Column("professional_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professional_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "professional_id",
            "professional_type",
            name="uq_professional_qualifications_professional_type",
        ),
    )
    op.create_table(
        "professional_educations",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.Uuid(), nullable=True),
        sa.Column(
            "level",
            sa.Enum(
                "TECHNICAL",
                "UNDERGRADUATE",
                "SPECIALIZATION",
                "MASTERS",
                "DOCTORATE",
                "POSTDOC",
                "COURSE",
                "FELLOWSHIP",
                name="education_level",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "course_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "institution", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("start_year", sa.Integer(), nullable=True),
        sa.Column("end_year", sa.Integer(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("workload_hours", sa.Integer(), nullable=True),
        sa.Column(
            "certificate_url",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("qualification_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["qualification_id"],
            ["professional_qualifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "professional_specialties",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.Uuid(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column(
            "rqe_number", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.Column(
            "rqe_state", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
        ),
        sa.Column(
            "residency_status",
            sa.Enum(
                "R1",
                "R2",
                "R3",
                "R4",
                "R5",
                "R6",
                "COMPLETED",
                name="residency_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "residency_institution",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "residency_expected_completion",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "certificate_url",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column("qualification_id", sa.Uuid(), nullable=False),
        sa.Column("specialty_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["qualification_id"],
            ["professional_qualifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["specialty_id"],
            ["specialties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "qualification_id",
            "specialty_id",
            name="uq_professional_specialties_qualification_specialty",
        ),
    )
    op.create_table(
        "professional_documents",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.Uuid(), nullable=True),
        sa.Column(
            "document_type",
            sa.Enum(
                "ID_DOCUMENT",
                "CRIMINAL_RECORD",
                "ADDRESS_PROOF",
                "CV",
                "DIPLOMA",
                "CRM_REGISTRATION_CERTIFICATE",
                "CRM_FINANCIAL_CERTIFICATE",
                "CRM_ETHICS_CERTIFICATE",
                "RESIDENCY_CERTIFICATE",
                "SPECIALIST_TITLE",
                "SBA_DIPLOMA",
                "OTHER",
                name="document_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "document_category",
            sa.Enum(
                "PROFILE",
                "QUALIFICATION",
                "SPECIALTY",
                name="document_category",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "file_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False
        ),
        sa.Column(
            "file_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column(
            "mime_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("professional_id", sa.Uuid(), nullable=False),
        sa.Column("qualification_id", sa.Uuid(), nullable=True),
        sa.Column("specialty_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professional_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["qualification_id"],
            ["professional_qualifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["specialty_id"],
            ["professional_specialties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("professional_documents")
    op.drop_table("professional_specialties")
    op.drop_table("professional_educations")
    op.drop_table("professional_qualifications")
    op.drop_table("professional_companies")
    op.drop_index(
        "uq_bank_accounts_professional_primary",
        table_name="bank_accounts",
        postgresql_where="is_primary = true AND professional_id IS NOT NULL",
    )
    op.drop_index(
        "uq_bank_accounts_company_primary",
        table_name="bank_accounts",
        postgresql_where="is_primary = true AND company_id IS NOT NULL",
    )
    op.drop_table("bank_accounts")
    op.drop_table("professional_profiles")
    op.drop_table("companies")
    op.drop_table("specialties")
    op.drop_table("banks")

    # Drop ENUMs (PostgreSQL doesn't remove them automatically)
    sa.Enum(name="document_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="document_category").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="residency_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="education_level").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="council_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="pix_key_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="account_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="marital_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="gender").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="professional_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
