"""add contracts

Revision ID: f9a5840a42d0
Revises: 8ece189cb1b7
Create Date: 2026-01-20 09:20:49.292821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f9a5840a42d0"
down_revision: Union[str, Sequence[str], None] = "8ece189cb1b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_contracts",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "client_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "contract_number",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_SIGNATURES",
                "ACTIVE",
                "SUSPENDED",
                "TERMINATED",
                "EXPIRED",
                name="contract_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_client_contracts_organization_id",
        "client_contracts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_client_contracts_status", "client_contracts", ["status"], unique=False
    )
    op.create_index(
        "uq_client_contracts_org_number",
        "client_contracts",
        ["organization_id", "contract_number"],
        unique=True,
        postgresql_where="contract_number IS NOT NULL AND deleted_at IS NULL",
    )
    op.create_table(
        "units",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.Uuid(), nullable=True),
        sa.Column(
            "address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column(
            "complement", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "neighborhood", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column(
            "state_code", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
        ),
        sa.Column(
            "state_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "postal_code", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True
        ),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column(
            "unit_type",
            sa.Enum(
                "HOSPITAL",
                "CLINIC",
                "UPA",
                "UBS",
                "EMERGENCY_ROOM",
                "LABORATORY",
                "HOME_CARE",
                "SURGERY_CENTER",
                "DIALYSIS_CENTER",
                "IMAGING_CENTER",
                "MATERNITY",
                "REHABILITATION",
                "OTHER",
                name="unit_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("geofence_radius_meters", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_units_organization_id", "units", ["organization_id"], unique=False
    )
    op.create_index("ix_units_unit_type", "units", ["unit_type"], unique=False)
    op.create_index(
        "uq_units_org_code",
        "units",
        ["organization_id", "code"],
        unique=True,
        postgresql_where="code IS NOT NULL AND deleted_at IS NULL",
    )
    op.create_table(
        "sectors",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("geofence_radius_meters", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sectors_unit_id", "sectors", ["unit_id"], unique=False)
    op.create_index(
        "uq_sectors_unit_code",
        "sectors",
        ["unit_id", "code"],
        unique=True,
        postgresql_where="code IS NOT NULL AND deleted_at IS NULL",
    )
    op.create_table(
        "professional_contracts",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "contract_number",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_SIGNATURES",
                "ACTIVE",
                "SUSPENDED",
                "TERMINATED",
                "EXPIRED",
                name="contract_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("hourly_rate", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "notes", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.Column("organization_professional_id", sa.Uuid(), nullable=False),
        sa.Column("client_contract_id", sa.Uuid(), nullable=True),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("bank_account_id", sa.Uuid(), nullable=True),
        sa.Column("unit_id", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("professional_signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "termination_reason",
            sqlmodel.sql.sqltypes.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column("termination_notice_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_contract_id"],
            ["client_contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_professional_id"],
            ["organization_professionals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_professional_contracts_client_contract_id",
        "professional_contracts",
        ["client_contract_id"],
        unique=False,
    )
    op.create_index(
        "ix_professional_contracts_org_professional_id",
        "professional_contracts",
        ["organization_professional_id"],
        unique=False,
    )
    op.create_index(
        "ix_professional_contracts_status",
        "professional_contracts",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_professional_contracts_unit_id",
        "professional_contracts",
        ["unit_id"],
        unique=False,
    )
    op.create_index(
        "uq_professional_contracts_prof_number",
        "professional_contracts",
        ["organization_professional_id", "contract_number"],
        unique=True,
        postgresql_where="contract_number IS NOT NULL AND deleted_at IS NULL",
    )
    op.create_table(
        "contract_amendments",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.Uuid(), nullable=True),
        sa.Column("amendment_number", sa.Integer(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False
        ),
        sa.Column("previous_values", sa.JSON(), nullable=True),
        sa.Column("new_values", sa.JSON(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column(
            "notes", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("professional_signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["professional_contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_contract_amendments_contract_id",
        "contract_amendments",
        ["contract_id"],
        unique=False,
    )
    op.create_index(
        "ix_contract_amendments_effective_from",
        "contract_amendments",
        ["effective_from"],
        unique=False,
    )
    op.create_index(
        "uq_contract_amendments_contract_number",
        "contract_amendments",
        ["contract_id", "amendment_number"],
        unique=True,
    )
    op.create_table(
        "contract_documents",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.Uuid(), nullable=True),
        sa.Column(
            "file_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False
        ),
        sa.Column(
            "file_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column(
            "mime_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "notes", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("amendment_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["amendment_id"],
            ["contract_amendments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["professional_contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_contract_documents_amendment_id",
        "contract_documents",
        ["amendment_id"],
        unique=False,
    )
    op.create_index(
        "ix_contract_documents_contract_id",
        "contract_documents",
        ["contract_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_contract_documents_contract_id", table_name="contract_documents")
    op.drop_index("ix_contract_documents_amendment_id", table_name="contract_documents")
    op.drop_table("contract_documents")
    op.drop_index(
        "uq_contract_amendments_contract_number", table_name="contract_amendments"
    )
    op.drop_index(
        "ix_contract_amendments_effective_from", table_name="contract_amendments"
    )
    op.drop_index(
        "ix_contract_amendments_contract_id", table_name="contract_amendments"
    )
    op.drop_table("contract_amendments")
    op.drop_index(
        "uq_professional_contracts_prof_number",
        table_name="professional_contracts",
        postgresql_where="contract_number IS NOT NULL AND deleted_at IS NULL",
    )
    op.drop_index(
        "ix_professional_contracts_unit_id", table_name="professional_contracts"
    )
    op.drop_index(
        "ix_professional_contracts_status", table_name="professional_contracts"
    )
    op.drop_index(
        "ix_professional_contracts_org_professional_id",
        table_name="professional_contracts",
    )
    op.drop_index(
        "ix_professional_contracts_client_contract_id",
        table_name="professional_contracts",
    )
    op.drop_table("professional_contracts")
    op.drop_index(
        "uq_sectors_unit_code",
        table_name="sectors",
        postgresql_where="code IS NOT NULL AND deleted_at IS NULL",
    )
    op.drop_index("ix_sectors_unit_id", table_name="sectors")
    op.drop_table("sectors")
    op.drop_index(
        "uq_units_org_code",
        table_name="units",
        postgresql_where="code IS NOT NULL AND deleted_at IS NULL",
    )
    op.drop_index("ix_units_unit_type", table_name="units")
    op.drop_index("ix_units_organization_id", table_name="units")
    op.drop_table("units")
    op.drop_index(
        "uq_client_contracts_org_number",
        table_name="client_contracts",
        postgresql_where="contract_number IS NOT NULL AND deleted_at IS NULL",
    )
    op.drop_index("ix_client_contracts_status", table_name="client_contracts")
    op.drop_index("ix_client_contracts_organization_id", table_name="client_contracts")
    op.drop_table("client_contracts")
    # ### end Alembic commands ###
