"""add_screening_workflow

Revision ID: fa4b42729c2d
Revises: 069f6f87cb6c
Create Date: 2026-01-25 18:39:17.078039

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fa4b42729c2d"
down_revision: Union[str, Sequence[str], None] = "069f6f87cb6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create new ENUM types first
    interview_method = postgresql.ENUM(
        "PHONE_CALL",
        "VIDEO_CALL",
        "IN_PERSON",
        "WHATSAPP",
        name="interview_method",
        create_type=False,
    )
    interview_method.create(op.get_bind(), checkfirst=True)

    interview_outcome = postgresql.ENUM(
        "APPROVED",
        "REJECTED",
        "ESCALATED",
        "RESCHEDULED",
        name="interview_outcome",
        create_type=False,
    )
    interview_outcome.create(op.get_bind(), checkfirst=True)

    client_validation_outcome = postgresql.ENUM(
        "APPROVED",
        "REJECTED",
        "PENDING_INFO",
        name="client_validation_outcome",
        create_type=False,
    )
    client_validation_outcome.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_type_configs",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "category",
            sa.Enum("PROFILE", "QUALIFICATION", "SPECIALTY", name="documentcategory"),
            nullable=False,
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("help_text", sa.Text(), nullable=True),
        sa.Column("validation_instructions", sa.Text(), nullable=True),
        sa.Column(
            "validation_url",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column("requires_expiration", sa.Boolean(), nullable=False),
        sa.Column("default_validity_days", sa.Integer(), nullable=True),
        sa.Column(
            "required_for_professional_types",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_document_type_configs_code"),
    )
    op.create_index(
        "ix_document_type_configs_category",
        "document_type_configs",
        ["category"],
        unique=False,
    )
    op.create_index(
        "ix_document_type_configs_code_active",
        "document_type_configs",
        ["code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_document_type_configs_is_active",
        "document_type_configs",
        ["is_active"],
        unique=False,
    )
    op.create_table(
        "organization_screening_settings",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("requires_client_company", sa.Boolean(), nullable=False),
        sa.Column("requires_client_validation_step", sa.Boolean(), nullable=False),
        sa.Column("requires_interview", sa.Boolean(), nullable=False),
        sa.Column(
            "default_interview_method",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
        sa.Column("auto_approve_existing_documents", sa.Boolean(), nullable=False),
        sa.Column("document_validity_check", sa.Boolean(), nullable=False),
        sa.Column("escalation_enabled", sa.Boolean(), nullable=False),
        sa.Column("auto_escalate_alerts", sa.Boolean(), nullable=False),
        sa.Column("token_expiry_hours", sa.Integer(), nullable=False),
        sa.Column("allow_professional_self_service", sa.Boolean(), nullable=False),
        sa.Column("notify_on_submission", sa.Boolean(), nullable=False),
        sa.Column("notify_on_expiration", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", name="uq_organization_screening_settings_org_id"
        ),
    )
    # NOTE: GIN trigram indexes already exist from 9fd32650c669_professionals_indexes.py
    # Skipping drop/recreate of idx_organization_professionals_search_trgm
    # Skipping drop/recreate of idx_professional_educations_search_trgm
    op.add_column(
        "screening_process_steps",
        sa.Column("interview_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "screening_process_steps",
        sa.Column(
            "interview_method",
            sa.Enum(
                "PHONE_CALL",
                "VIDEO_CALL",
                "IN_PERSON",
                "WHATSAPP",
                name="interview_method",
                create_constraint=True,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "screening_process_steps",
        sa.Column(
            "interview_notes",
            sqlmodel.sql.sqltypes.AutoString(length=4000),
            nullable=True,
        ),
    )
    op.add_column(
        "screening_process_steps",
        sa.Column(
            "interview_outcome",
            sa.Enum(
                "APPROVED",
                "NEEDS_REVIEW",
                "REJECTED",
                name="interview_outcome",
                create_constraint=True,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "screening_process_steps",
        sa.Column(
            "interview_escalation_reason",
            sqlmodel.sql.sqltypes.AutoString(length=2000),
            nullable=True,
        ),
    )
    op.add_column(
        "screening_process_steps",
        sa.Column(
            "client_validation_outcome",
            sa.Enum(
                "APPROVED",
                "REJECTED",
                name="client_validation_outcome",
                create_constraint=True,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "screening_process_steps",
        sa.Column(
            "client_validation_notes",
            sqlmodel.sql.sqltypes.AutoString(length=2000),
            nullable=True,
        ),
    )
    op.add_column(
        "screening_process_steps",
        sa.Column(
            "client_validated_by",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "screening_process_steps",
        sa.Column("client_validated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "screening_processes",
        sa.Column(
            "expected_professional_type",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
    )
    op.add_column(
        "screening_processes",
        sa.Column("expected_specialty_id", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "screening_processes",
        sa.Column("current_assignee_id", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "screening_processes", sa.Column("verifier_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "screening_processes", sa.Column("client_company_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        "ix_screening_processes_client_company",
        "screening_processes",
        ["client_company_id"],
        unique=False,
    )
    op.create_index(
        "ix_screening_processes_current_assignee",
        "screening_processes",
        ["current_assignee_id"],
        unique=False,
    )
    op.create_index(
        "ix_screening_processes_verifier",
        "screening_processes",
        ["verifier_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "screening_processes", "companies", ["client_company_id"], ["id"]
    )
    op.add_column(
        "screening_required_documents",
        sa.Column("created_by", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "screening_required_documents",
        sa.Column("updated_by", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "screening_required_documents",
        sa.Column(
            "notes", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
    )
    op.add_column(
        "screening_required_documents",
        sa.Column("is_uploaded", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "screening_required_documents",
        sa.Column("is_existing", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "screening_required_documents",
        sa.Column("document_type_config_id", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "screening_required_documents",
        sa.Column("professional_document_id", sa.Uuid(), nullable=True),
    )
    op.alter_column(
        "screening_required_documents",
        "document_type",
        existing_type=postgresql.ENUM(
            "ID_DOCUMENT",
            "CRIMINAL_RECORD",
            "ADDRESS_PROOF",
            "CV",
            "DIPLOMA",
            "CRM_REGISTRATION_CERTIFICATE",
            "CRM_FINANCIAL_CERTIFICATE",
            "CRM_ETHICS_CERTIFICATE",
            "RESIDENCY_CERTIFICATE",
            "SPECIALIST_TITLE",
            "SBA_DIPLOMA",
            "OTHER",
            name="document_type",
        ),
        nullable=True,
    )
    op.create_index(
        "ix_screening_required_documents_doc_type_config",
        "screening_required_documents",
        ["document_type_config_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_screening_required_documents_process_doc_config",
        "screening_required_documents",
        ["process_id", "document_type_config_id"],
    )
    op.create_foreign_key(
        None,
        "screening_required_documents",
        "document_type_configs",
        ["document_type_config_id"],
        ["id"],
    )
    op.create_foreign_key(
        None,
        "screening_required_documents",
        "professional_documents",
        ["professional_document_id"],
        ["id"],
    )
    # NOTE: GIN trigram index idx_specialties_search_trgm already exists
    # Skipping drop/recreate
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: GIN trigram indexes were not modified in upgrade, so skip in downgrade
    op.drop_constraint(None, "screening_required_documents", type_="foreignkey")
    op.drop_constraint(None, "screening_required_documents", type_="foreignkey")
    op.drop_constraint(
        "uq_screening_required_documents_process_doc_config",
        "screening_required_documents",
        type_="unique",
    )
    op.drop_index(
        "ix_screening_required_documents_doc_type_config",
        table_name="screening_required_documents",
    )
    op.alter_column(
        "screening_required_documents",
        "document_type",
        existing_type=postgresql.ENUM(
            "ID_DOCUMENT",
            "CRIMINAL_RECORD",
            "ADDRESS_PROOF",
            "CV",
            "DIPLOMA",
            "CRM_REGISTRATION_CERTIFICATE",
            "CRM_FINANCIAL_CERTIFICATE",
            "CRM_ETHICS_CERTIFICATE",
            "RESIDENCY_CERTIFICATE",
            "SPECIALIST_TITLE",
            "SBA_DIPLOMA",
            "OTHER",
            name="document_type",
        ),
        nullable=False,
    )
    op.drop_column("screening_required_documents", "professional_document_id")
    op.drop_column("screening_required_documents", "document_type_config_id")
    op.drop_column("screening_required_documents", "is_existing")
    op.drop_column("screening_required_documents", "is_uploaded")
    op.drop_column("screening_required_documents", "notes")
    op.drop_column("screening_required_documents", "updated_by")
    op.drop_column("screening_required_documents", "created_by")
    op.drop_constraint(None, "screening_processes", type_="foreignkey")
    op.drop_index("ix_screening_processes_verifier", table_name="screening_processes")
    op.drop_index(
        "ix_screening_processes_current_assignee", table_name="screening_processes"
    )
    op.drop_index(
        "ix_screening_processes_client_company", table_name="screening_processes"
    )
    op.drop_column("screening_processes", "client_company_id")
    op.drop_column("screening_processes", "verifier_id")
    op.drop_column("screening_processes", "current_assignee_id")
    op.drop_column("screening_processes", "expected_specialty_id")
    op.drop_column("screening_processes", "expected_professional_type")
    op.drop_column("screening_process_steps", "client_validated_at")
    op.drop_column("screening_process_steps", "client_validated_by")
    op.drop_column("screening_process_steps", "client_validation_notes")
    op.drop_column("screening_process_steps", "client_validation_outcome")
    op.drop_column("screening_process_steps", "interview_escalation_reason")
    op.drop_column("screening_process_steps", "interview_outcome")
    op.drop_column("screening_process_steps", "interview_notes")
    op.drop_column("screening_process_steps", "interview_method")
    op.drop_column("screening_process_steps", "interview_date")
    # NOTE: GIN trigram indexes were not modified in upgrade, so skip in downgrade
    op.drop_table("organization_screening_settings")
    op.drop_index(
        "ix_document_type_configs_is_active", table_name="document_type_configs"
    )
    op.drop_index(
        "ix_document_type_configs_code_active",
        table_name="document_type_configs",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_document_type_configs_category", table_name="document_type_configs"
    )
    op.drop_table("document_type_configs")
    # ### end Alembic commands ###
