/**
 * Contracts module enums.
 *
 * AUTO-GENERATED by scripts/generate_ts_enums.py
 * DO NOT EDIT MANUALLY
 */

/**
 * Status of a contract throughout its lifecycle.
 * 
 * Tracks the contract from creation to termination.
 */
export enum ContractStatus {
  DRAFT = "DRAFT",
  PENDING_SIGNATURES = "PENDING_SIGNATURES",
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  TERMINATED = "TERMINATED",
  EXPIRED = "EXPIRED",
}

export const ContractStatusLabels: Record<ContractStatus, string> = {
  [ContractStatus.DRAFT]: "Rascunho",
  [ContractStatus.PENDING_SIGNATURES]: "Aguardando Assinaturas",
  [ContractStatus.ACTIVE]: "Ativo",
  [ContractStatus.SUSPENDED]: "Suspenso",
  [ContractStatus.TERMINATED]: "Rescindido",
  [ContractStatus.EXPIRED]: "Expirado",
};

export function getContractStatusLabel(value: ContractStatus): string {
  return ContractStatusLabels[value];
}
