/**
 * Organizations module enums.
 *
 * AUTO-GENERATED by scripts/generate_ts_enums.py
 * DO NOT EDIT MANUALLY
 */

/**
 * Types of healthcare organizations.
 * 
 * Defines the main category of the organization.
 */
export enum OrganizationType {
  HOSPITAL = "HOSPITAL",
  CLINIC = "CLINIC",
  LABORATORY = "LABORATORY",
  EMERGENCY_UNIT = "EMERGENCY_UNIT",
  HEALTH_CENTER = "HEALTH_CENTER",
  HOME_CARE = "HOME_CARE",
  OUTSOURCING_COMPANY = "OUTSOURCING_COMPANY",
  OTHER = "OTHER",
}

export const OrganizationTypeLabels: Record<OrganizationType, string> = {
  [OrganizationType.HOSPITAL]: "Hospital",
  [OrganizationType.CLINIC]: "Clínica",
  [OrganizationType.LABORATORY]: "Laboratório",
  [OrganizationType.EMERGENCY_UNIT]: "Pronto Socorro",
  [OrganizationType.HEALTH_CENTER]: "Centro de Saúde",
  [OrganizationType.HOME_CARE]: "Home Care",
  [OrganizationType.OUTSOURCING_COMPANY]: "Empresa Terceirizada",
  [OrganizationType.OTHER]: "Outro",
};

export function getOrganizationTypeLabel(value: OrganizationType): string {
  return OrganizationTypeLabels[value];
}

/**
 * Policy for data scope in queries.
 * 
 * Controls whether queries should return data only from the current
 * organization or from the entire family (parent + children/siblings).
 * 
 * Used at runtime to determine query scope for shared resources.
 */
export enum DataScopePolicy {
  ORGANIZATION_ONLY = "ORGANIZATION_ONLY",
  FAMILY = "FAMILY",
}

export const DataScopePolicyLabels: Record<DataScopePolicy, string> = {
  [DataScopePolicy.ORGANIZATION_ONLY]: "Somente Organização",
  [DataScopePolicy.FAMILY]: "Família",
};

export function getDataScopePolicyLabel(value: DataScopePolicy): string {
  return DataScopePolicyLabels[value];
}
