/**
 * Professionals module enums.
 *
 * AUTO-GENERATED by scripts/generate_ts_enums.py
 * DO NOT EDIT MANUALLY
 */

/**
 * Source type for professional documents.
 * 
 * Indicates how/where a document was created.
 */
export enum DocumentSourceType {
  DIRECT = "DIRECT",
  SCREENING = "SCREENING",
}

export const DocumentSourceTypeLabels: Record<DocumentSourceType, string> = {
  [DocumentSourceType.DIRECT]: "Upload Direto",
  [DocumentSourceType.SCREENING]: "Triagem",
};

export function getDocumentSourceTypeLabel(value: DocumentSourceType): string {
  return DocumentSourceTypeLabels[value];
}

/**
 * Types of professional councils in Brazil.
 * 
 * Each healthcare profession has its own regulatory council
 * responsible for registration and oversight.
 */
export enum CouncilType {
  CRM = "CRM",
  COREN = "COREN",
  CRF = "CRF",
  CRO = "CRO",
  CREFITO = "CREFITO",
  CRP = "CRP",
  CRN = "CRN",
  CRBM = "CRBM",
}

export const CouncilTypeLabels: Record<CouncilType, string> = {
  [CouncilType.CRM]: "Conselho Regional de Medicina",
  [CouncilType.COREN]: "Conselho Regional de Enfermagem",
  [CouncilType.CRF]: "Conselho Regional de Farmácia",
  [CouncilType.CRO]: "Conselho Regional de Odontologia",
  [CouncilType.CREFITO]: "Conselho Regional de Fisioterapia e Terapia Ocupacional",
  [CouncilType.CRP]: "Conselho Regional de Psicologia",
  [CouncilType.CRN]: "Conselho Regional de Nutricionistas",
  [CouncilType.CRBM]: "Conselho Regional de Biomedicina",
};

export function getCouncilTypeLabel(value: CouncilType): string {
  return CouncilTypeLabels[value];
}

/**
 * Types of healthcare professionals.
 * 
 * Defines the main category of healthcare worker.
 */
export enum ProfessionalType {
  DOCTOR = "DOCTOR",
  NURSE = "NURSE",
  NURSING_TECH = "NURSING_TECH",
  PHARMACIST = "PHARMACIST",
  DENTIST = "DENTIST",
  PHYSIOTHERAPIST = "PHYSIOTHERAPIST",
  PSYCHOLOGIST = "PSYCHOLOGIST",
  NUTRITIONIST = "NUTRITIONIST",
  BIOMEDIC = "BIOMEDIC",
}

export const ProfessionalTypeLabels: Record<ProfessionalType, string> = {
  [ProfessionalType.DOCTOR]: "Médico",
  [ProfessionalType.NURSE]: "Enfermeiro",
  [ProfessionalType.NURSING_TECH]: "Técnico de Enfermagem",
  [ProfessionalType.PHARMACIST]: "Farmacêutico",
  [ProfessionalType.DENTIST]: "Dentista",
  [ProfessionalType.PHYSIOTHERAPIST]: "Fisioterapeuta",
  [ProfessionalType.PSYCHOLOGIST]: "Psicólogo",
  [ProfessionalType.NUTRITIONIST]: "Nutricionista",
  [ProfessionalType.BIOMEDIC]: "Biomédico",
};

export function getProfessionalTypeLabel(value: ProfessionalType): string {
  return ProfessionalTypeLabels[value];
}

/**
 * Medical residency status.
 * 
 * Tracks the progress of a professional through their
 * residency/specialization program.
 */
export enum ResidencyStatus {
  R1 = "R1",
  R2 = "R2",
  R3 = "R3",
  R4 = "R4",
  R5 = "R5",
  R6 = "R6",
  COMPLETED = "COMPLETED",
}

export const ResidencyStatusLabels: Record<ResidencyStatus, string> = {
  [ResidencyStatus.R1]: "Residente 1º ano",
  [ResidencyStatus.R2]: "Residente 2º ano",
  [ResidencyStatus.R3]: "Residente 3º ano",
  [ResidencyStatus.R4]: "Residente 4º ano",
  [ResidencyStatus.R5]: "Residente 5º ano",
  [ResidencyStatus.R6]: "Residente 6º ano",
  [ResidencyStatus.COMPLETED]: "Concluída",
};

export function getResidencyStatusLabel(value: ResidencyStatus): string {
  return ResidencyStatusLabels[value];
}

/**
 * Gender options for professionals.
 */
export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
}

export const GenderLabels: Record<Gender, string> = {
  [Gender.MALE]: "Masculino",
  [Gender.FEMALE]: "Feminino",
};

export function getGenderLabel(value: Gender): string {
  return GenderLabels[value];
}

/**
 * Marital status options.
 */
export enum MaritalStatus {
  SINGLE = "SINGLE",
  MARRIED = "MARRIED",
  DIVORCED = "DIVORCED",
  WIDOWED = "WIDOWED",
  SEPARATED = "SEPARATED",
  CIVIL_UNION = "CIVIL_UNION",
}

export const MaritalStatusLabels: Record<MaritalStatus, string> = {
  [MaritalStatus.SINGLE]: "Solteiro(a)",
  [MaritalStatus.MARRIED]: "Casado(a)",
  [MaritalStatus.DIVORCED]: "Divorciado(a)",
  [MaritalStatus.WIDOWED]: "Viúvo(a)",
  [MaritalStatus.SEPARATED]: "Separado(a)",
  [MaritalStatus.CIVIL_UNION]: "União Estável",
};

export function getMaritalStatusLabel(value: MaritalStatus): string {
  return MaritalStatusLabels[value];
}

/**
 * Education level types.
 * 
 * Covers technical courses through doctoral degrees.
 */
export enum EducationLevel {
  TECHNICAL = "TECHNICAL",
  UNDERGRADUATE = "UNDERGRADUATE",
  SPECIALIZATION = "SPECIALIZATION",
  MASTERS = "MASTERS",
  DOCTORATE = "DOCTORATE",
  POSTDOC = "POSTDOC",
  COURSE = "COURSE",
  FELLOWSHIP = "FELLOWSHIP",
}

export const EducationLevelLabels: Record<EducationLevel, string> = {
  [EducationLevel.TECHNICAL]: "Curso Técnico",
  [EducationLevel.UNDERGRADUATE]: "Graduação",
  [EducationLevel.SPECIALIZATION]: "Especialização",
  [EducationLevel.MASTERS]: "Mestrado",
  [EducationLevel.DOCTORATE]: "Doutorado",
  [EducationLevel.POSTDOC]: "Pós-Doutorado",
  [EducationLevel.COURSE]: "Curso Livre",
  [EducationLevel.FELLOWSHIP]: "Fellowship",
};

export function getEducationLevelLabel(value: EducationLevel): string {
  return EducationLevelLabels[value];
}
