/**
 * Screening module enums.
 *
 * AUTO-GENERATED by scripts/generate_ts_enums.py
 * DO NOT EDIT MANUALLY
 */

/**
 * Fixed screening step types.
 * 
 * Each step corresponds to a specific data collection or review phase
 * in the professional screening process.
 * 
 * Order (fixed for MVP):
 * 1. CONVERSATION - Initial phone call (required)
 * 2. PROFESSIONAL_DATA - Personal + qualification + specialties + education (required)
 * 3. DOCUMENT_UPLOAD - Upload documents (required)
 * 4. DOCUMENT_REVIEW - Review uploaded documents (required)
 * 5. PAYMENT_INFO - Bank account + company if PJ (optional)
 * 6. SUPERVISOR_REVIEW - Escalated review (optional)
 * 7. CLIENT_VALIDATION - Client approval (optional)
 */
export enum StepType {
  CONVERSATION = "CONVERSATION",
  PROFESSIONAL_DATA = "PROFESSIONAL_DATA",
  DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD",
  DOCUMENT_REVIEW = "DOCUMENT_REVIEW",
  PAYMENT_INFO = "PAYMENT_INFO",
  SUPERVISOR_REVIEW = "SUPERVISOR_REVIEW",
  CLIENT_VALIDATION = "CLIENT_VALIDATION",
}

export const StepTypeLabels: Record<StepType, string> = {
  [StepType.CONVERSATION]: "Conversa Inicial",
  [StepType.PROFESSIONAL_DATA]: "Dados Profissionais",
  [StepType.DOCUMENT_UPLOAD]: "Upload de Documentos",
  [StepType.DOCUMENT_REVIEW]: "Revisão de Documentos",
  [StepType.PAYMENT_INFO]: "Informações de Pagamento",
  [StepType.SUPERVISOR_REVIEW]: "Revisão do Supervisor",
  [StepType.CLIENT_VALIDATION]: "Validação do Cliente",
};

export function getStepTypeLabel(value: StepType): string {
  return StepTypeLabels[value];
}

/**
 * Source of a professional version change.
 * 
 * Tracks how/where the change originated for audit purposes.
 */
export enum SourceType {
  DIRECT = "DIRECT",
  SCREENING = "SCREENING",
  IMPORT = "IMPORT",
  API = "API",
}

export const SourceTypeLabels: Record<SourceType, string> = {
  [SourceType.DIRECT]: "Direto",
  [SourceType.SCREENING]: "Triagem",
  [SourceType.IMPORT]: "Importação",
  [SourceType.API]: "API Externa",
};

export function getSourceTypeLabel(value: SourceType): string {
  return SourceTypeLabels[value];
}

/**
 * Type of change in a professional version diff.
 * 
 * Used in ProfessionalChangeDiff to categorize field changes.
 */
export enum ChangeType {
  ADDED = "ADDED",
  MODIFIED = "MODIFIED",
  REMOVED = "REMOVED",
}

export const ChangeTypeLabels: Record<ChangeType, string> = {
  [ChangeType.ADDED]: "Adicionado",
  [ChangeType.MODIFIED]: "Modificado",
  [ChangeType.REMOVED]: "Removido",
};

export function getChangeTypeLabel(value: ChangeType): string {
  return ChangeTypeLabels[value];
}

/**
 * Status of a screening process throughout its lifecycle.
 * 
 * Tracks the overall macro state of the screening from creation to completion.
 * Detailed progress is tracked via the status of each configured step.
 */
export enum ScreeningStatus {
  DRAFT = "DRAFT",
  IN_PROGRESS = "IN_PROGRESS",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export const ScreeningStatusLabels: Record<ScreeningStatus, string> = {
  [ScreeningStatus.DRAFT]: "Rascunho",
  [ScreeningStatus.IN_PROGRESS]: "Em Andamento",
  [ScreeningStatus.APPROVED]: "Aprovado",
  [ScreeningStatus.REJECTED]: "Rejeitado",
  [ScreeningStatus.EXPIRED]: "Expirado",
  [ScreeningStatus.CANCELLED]: "Cancelado",
};

export function getScreeningStatusLabel(value: ScreeningStatus): string {
  return ScreeningStatusLabels[value];
}

/**
 * Status of an individual screening step.
 * 
 * Tracks the progress of a single step within the screening process.
 */
export enum StepStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  SKIPPED = "SKIPPED",
  CANCELLED = "CANCELLED",
  CORRECTION_NEEDED = "CORRECTION_NEEDED",
}

export const StepStatusLabels: Record<StepStatus, string> = {
  [StepStatus.PENDING]: "Pendente",
  [StepStatus.IN_PROGRESS]: "Em Andamento",
  [StepStatus.COMPLETED]: "Concluído",
  [StepStatus.APPROVED]: "Aprovado",
  [StepStatus.REJECTED]: "Rejeitado",
  [StepStatus.SKIPPED]: "Pulado",
  [StepStatus.CANCELLED]: "Cancelado",
  [StepStatus.CORRECTION_NEEDED]: "Correção Necessária",
};

export function getStepStatusLabel(value: StepStatus): string {
  return StepStatusLabels[value];
}

/**
 * Status of a document in the screening workflow.
 * 
 * Tracks the full lifecycle from requirement to approval.
 * 
 * Flow:
 * PENDING_UPLOAD → PENDING_REVIEW → APPROVED
 * │
 * └──→ CORRECTION_NEEDED → PENDING_REVIEW (after re-upload)
 * 
 * Special states:
 * - REUSED: Document reused from a previous screening
 * - SKIPPED: Optional document explicitly skipped
 */
export enum ScreeningDocumentStatus {
  PENDING_UPLOAD = "PENDING_UPLOAD",
  PENDING_REVIEW = "PENDING_REVIEW",
  APPROVED = "APPROVED",
  CORRECTION_NEEDED = "CORRECTION_NEEDED",
  REUSED = "REUSED",
  SKIPPED = "SKIPPED",
}

export const ScreeningDocumentStatusLabels: Record<ScreeningDocumentStatus, string> = {
  [ScreeningDocumentStatus.PENDING_UPLOAD]: "Aguardando Upload",
  [ScreeningDocumentStatus.PENDING_REVIEW]: "Aguardando Revisão",
  [ScreeningDocumentStatus.APPROVED]: "Aprovado",
  [ScreeningDocumentStatus.CORRECTION_NEEDED]: "Correção Necessária",
  [ScreeningDocumentStatus.REUSED]: "Reutilizado",
  [ScreeningDocumentStatus.SKIPPED]: "Pulado",
};

export function getScreeningDocumentStatusLabel(value: ScreeningDocumentStatus): string {
  return ScreeningDocumentStatusLabels[value];
}

/**
 * Outcome of the initial conversation step.
 * 
 * Determines whether the screening proceeds or is rejected early.
 */
export enum ConversationOutcome {
  PROCEED = "PROCEED",
  REJECT = "REJECT",
}

export const ConversationOutcomeLabels: Record<ConversationOutcome, string> = {
  [ConversationOutcome.PROCEED]: "Prosseguir",
  [ConversationOutcome.REJECT]: "Rejeitar",
};

export function getConversationOutcomeLabel(value: ConversationOutcome): string {
  return ConversationOutcomeLabels[value];
}

/**
 * Outcome of client company validation.
 * 
 * Final decision from the contracting client.
 */
export enum ClientValidationOutcome {
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export const ClientValidationOutcomeLabels: Record<ClientValidationOutcome, string> = {
  [ClientValidationOutcome.APPROVED]: "Aprovado",
  [ClientValidationOutcome.REJECTED]: "Rejeitado",
};

export function getClientValidationOutcomeLabel(value: ClientValidationOutcome): string {
  return ClientValidationOutcomeLabels[value];
}
