/**
 * Shared module enums.
 *
 * AUTO-GENERATED by scripts/generate_ts_enums.py
 * DO NOT EDIT MANUALLY
 */

/**
 * Bank account types.
 * 
 * Defines the type of bank account for payment purposes.
 */
export enum AccountType {
  CHECKING = "CHECKING",
  SAVINGS = "SAVINGS",
}

export const AccountTypeLabels: Record<AccountType, string> = {
  [AccountType.CHECKING]: "Conta Corrente",
  [AccountType.SAVINGS]: "Conta Poupança",
};

export function getAccountTypeLabel(value: AccountType): string {
  return AccountTypeLabels[value];
}

/**
 * PIX key types.
 * 
 * Defines the type of PIX key for instant payments.
 */
export enum PixKeyType {
  CPF = "CPF",
  CNPJ = "CNPJ",
  EMAIL = "EMAIL",
  PHONE = "PHONE",
  RANDOM = "RANDOM",
}

export const PixKeyTypeLabels: Record<PixKeyType, string> = {
  [PixKeyType.CPF]: "CPF",
  [PixKeyType.CNPJ]: "CNPJ",
  [PixKeyType.EMAIL]: "E-mail",
  [PixKeyType.PHONE]: "Telefone",
  [PixKeyType.RANDOM]: "Chave Aleatória",
};

export function getPixKeyTypeLabel(value: PixKeyType): string {
  return PixKeyTypeLabels[value];
}

/**
 * Document category based on which entity it relates to.
 * 
 * Used to group documents by their relation to professional data.
 */
export enum DocumentCategory {
  PROFILE = "PROFILE",
  QUALIFICATION = "QUALIFICATION",
  SPECIALTY = "SPECIALTY",
}

export const DocumentCategoryLabels: Record<DocumentCategory, string> = {
  [DocumentCategory.PROFILE]: "Perfil",
  [DocumentCategory.QUALIFICATION]: "Qualificação",
  [DocumentCategory.SPECIALTY]: "Especialidade",
};

export function getDocumentCategoryLabel(value: DocumentCategory): string {
  return DocumentCategoryLabels[value];
}
