/**
 * Units module enums.
 *
 * AUTO-GENERATED by scripts/generate_ts_enums.py
 * DO NOT EDIT MANUALLY
 */

/**
 * Types of healthcare units/facilities.
 * 
 * Defines the main category of the work location.
 */
export enum UnitType {
  HOSPITAL = "HOSPITAL",
  CLINIC = "CLINIC",
  UPA = "UPA",
  UBS = "UBS",
  EMERGENCY_ROOM = "EMERGENCY_ROOM",
  LABORATORY = "LABORATORY",
  HOME_CARE = "HOME_CARE",
  SURGERY_CENTER = "SURGERY_CENTER",
  DIALYSIS_CENTER = "DIALYSIS_CENTER",
  IMAGING_CENTER = "IMAGING_CENTER",
  MATERNITY = "MATERNITY",
  REHABILITATION = "REHABILITATION",
  OTHER = "OTHER",
}

export const UnitTypeLabels: Record<UnitType, string> = {
  [UnitType.HOSPITAL]: "Hospital",
  [UnitType.CLINIC]: "Clínica",
  [UnitType.UPA]: "UPA",
  [UnitType.UBS]: "UBS",
  [UnitType.EMERGENCY_ROOM]: "Pronto Socorro",
  [UnitType.LABORATORY]: "Laboratório",
  [UnitType.HOME_CARE]: "Home Care",
  [UnitType.SURGERY_CENTER]: "Centro Cirúrgico",
  [UnitType.DIALYSIS_CENTER]: "Centro de Diálise",
  [UnitType.IMAGING_CENTER]: "Centro de Imagem",
  [UnitType.MATERNITY]: "Maternidade",
  [UnitType.REHABILITATION]: "Centro de Reabilitação",
  [UnitType.OTHER]: "Outro",
};

export function getUnitTypeLabel(value: UnitType): string {
  return UnitTypeLabels[value];
}
