"""Custom application exceptions."""

from src.app.exceptions.base import (
    AppException,
    AuthenticationError,
    AuthorizationError,
    ConflictError,
    NotFoundError,
    ValidationError,
)
from src.app.exceptions.auth_exceptions import (
    AuthException,
    CacheError,
    ExpiredTokenError,
    FirebaseAuthError,
    FirebaseInitError,
    InvalidTokenError,
    MissingTokenError,
    RevokedTokenError,
    UserInactiveError,
    UserNotFoundError,
)
from src.app.exceptions.professional_exceptions import (
    CompanyAlreadyLinkedError,
    CompanyNotFoundError,
    CouncilRegistrationExistsError,
    CourseNameRequiredError,
    DocumentNotFoundError,
    DocumentQualificationCategoryError,
    DocumentSpecialtyCategoryError,
    DuplicateSpecialtyIdsError,
    EducationNotFoundError,
    GlobalSpecialtyNotFoundError,
    InstitutionRequiredError,
    InvalidCouncilTypeError,
    LevelRequiredError,
    ProfessionalCpfExistsError,
    ProfessionalEmailExistsError,
    ProfessionalException,
    ProfessionalNotFoundError,
    QualificationIdRequiredError,
    QualificationNotBelongsError,
    QualificationNotFoundError,
    SpecialtyAlreadyAssignedError,
    SpecialtyNotFoundError,
)

__all__ = [
    # Base exceptions
    "AppException",
    "AuthenticationError",
    "AuthorizationError",
    "ConflictError",
    "NotFoundError",
    "ValidationError",
    # Auth exceptions
    "AuthException",
    "CacheError",
    "ExpiredTokenError",
    "FirebaseAuthError",
    "FirebaseInitError",
    "InvalidTokenError",
    "MissingTokenError",
    "RevokedTokenError",
    "UserInactiveError",
    "UserNotFoundError",
    # Professional exceptions
    "CompanyAlreadyLinkedError",
    "CompanyNotFoundError",
    "CouncilRegistrationExistsError",
    "CourseNameRequiredError",
    "DocumentNotFoundError",
    "DocumentQualificationCategoryError",
    "DocumentSpecialtyCategoryError",
    "DuplicateSpecialtyIdsError",
    "EducationNotFoundError",
    "GlobalSpecialtyNotFoundError",
    "InstitutionRequiredError",
    "InvalidCouncilTypeError",
    "LevelRequiredError",
    "ProfessionalCpfExistsError",
    "ProfessionalEmailExistsError",
    "ProfessionalException",
    "ProfessionalNotFoundError",
    "QualificationIdRequiredError",
    "QualificationNotBelongsError",
    "QualificationNotFoundError",
    "SpecialtyAlreadyAssignedError",
    "SpecialtyNotFoundError",
]
